/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessLocationsResponsePagination } from './AccessLocationsResponsePagination';
import {
    AccessLocationsResponsePaginationFromJSON,
    AccessLocationsResponsePaginationFromJSONTyped,
    AccessLocationsResponsePaginationToJSON,
    AccessLocationsResponsePaginationToJSONTyped,
} from './AccessLocationsResponsePagination';
import type { AccessMember } from './AccessMember';
import {
    AccessMemberFromJSON,
    AccessMemberFromJSONTyped,
    AccessMemberToJSON,
    AccessMemberToJSONTyped,
} from './AccessMember';

/**
 * @export
 * @interface AccessMembersResponse
 */
export interface AccessMembersResponse {
    /**
     * @type {Array<AccessMember>}
     * @memberof AccessMembersResponse
     */
    data: Array<AccessMember>;
    /**
     * @type {AccessLocationsResponsePagination}
     * @memberof AccessMembersResponse
     */
    pagination: AccessLocationsResponsePagination;
}

/**
 * Check if a given object implements the AccessMembersResponse interface.
 */
export function instanceOfAccessMembersResponse(value: object): value is AccessMembersResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AccessMembersResponseFromJSON(json: any): AccessMembersResponse {
    return AccessMembersResponseFromJSONTyped(json, false);
}

export function AccessMembersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessMembersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AccessMemberFromJSON)),
        'pagination': AccessLocationsResponsePaginationFromJSON(json['pagination']),
    };
}

export function AccessMembersResponseToJSON(json: any): AccessMembersResponse {
    return AccessMembersResponseToJSONTyped(json, false);
}

export function AccessMembersResponseToJSONTyped(value?: AccessMembersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AccessMemberToJSON)),
        'pagination': AccessLocationsResponsePaginationToJSON(value['pagination']),
    };
}
