/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AccessControlConfigStatusKisi
 */
export interface AccessControlConfigStatusKisi {
    /**
     * Whether KISI_API_KEY is set
     * @type {boolean}
     * @memberof AccessControlConfigStatusKisi
     */
    hasApiKey: boolean;
    /**
     * Kisi API base URL
     * @type {string}
     * @memberof AccessControlConfigStatusKisi
     */
    baseUrl: string;
}

/**
 * Check if a given object implements the AccessControlConfigStatusKisi interface.
 */
export function instanceOfAccessControlConfigStatusKisi(value: object): value is AccessControlConfigStatusKisi {
    if (!('hasApiKey' in value) || value['hasApiKey'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    return true;
}

export function AccessControlConfigStatusKisiFromJSON(json: any): AccessControlConfigStatusKisi {
    return AccessControlConfigStatusKisiFromJSONTyped(json, false);
}

export function AccessControlConfigStatusKisiFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessControlConfigStatusKisi {
    if (json == null) {
        return json;
    }
    return {
        
        'hasApiKey': json['hasApiKey'],
        'baseUrl': json['baseUrl'],
    };
}

export function AccessControlConfigStatusKisiToJSON(json: any): AccessControlConfigStatusKisi {
    return AccessControlConfigStatusKisiToJSONTyped(json, false);
}

export function AccessControlConfigStatusKisiToJSONTyped(value?: AccessControlConfigStatusKisi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasApiKey': value['hasApiKey'],
        'baseUrl': value['baseUrl'],
    };
}
