/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AccessGroup
 */
export interface AccessGroup {
    /**
     * Group ID
     * @type {string}
     * @memberof AccessGroup
     */
    id: string;
    /**
     * Group name
     * @type {string}
     * @memberof AccessGroup
     */
    name: string;
    /**
     * Description
     * @type {string}
     * @memberof AccessGroup
     */
    description?: string;
    /**
     * Location ID
     * @type {string}
     * @memberof AccessGroup
     */
    locationId?: string;
    /**
     * Provider-specific metadata
     * @type {{ [key: string]: any }}
     * @memberof AccessGroup
     */
    metadata?: { [key: string]: any };
    /**
     * Created timestamp (ISO 8601)
     * @type {string}
     * @memberof AccessGroup
     */
    createdAt?: string;
    /**
     * Updated timestamp (ISO 8601)
     * @type {string}
     * @memberof AccessGroup
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the AccessGroup interface.
 */
export function instanceOfAccessGroup(value: object): value is AccessGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AccessGroupFromJSON(json: any): AccessGroup {
    return AccessGroupFromJSONTyped(json, false);
}

export function AccessGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'locationId': json['locationId'] == null ? undefined : json['locationId'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function AccessGroupToJSON(json: any): AccessGroup {
    return AccessGroupToJSONTyped(json, false);
}

export function AccessGroupToJSONTyped(value?: AccessGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'locationId': value['locationId'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}
