/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AccessLocation
 */
export interface AccessLocation {
    /**
     * Location ID (provider-specific)
     * @type {string}
     * @memberof AccessLocation
     */
    id: string;
    /**
     * Location name
     * @type {string}
     * @memberof AccessLocation
     */
    name: string;
    /**
     * Address
     * @type {string}
     * @memberof AccessLocation
     */
    address?: string;
    /**
     * Description
     * @type {string}
     * @memberof AccessLocation
     */
    description?: string;
    /**
     * Provider-specific metadata
     * @type {{ [key: string]: any }}
     * @memberof AccessLocation
     */
    metadata?: { [key: string]: any };
    /**
     * Created timestamp (ISO 8601)
     * @type {string}
     * @memberof AccessLocation
     */
    createdAt?: string;
    /**
     * Updated timestamp (ISO 8601)
     * @type {string}
     * @memberof AccessLocation
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the AccessLocation interface.
 */
export function instanceOfAccessLocation(value: object): value is AccessLocation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AccessLocationFromJSON(json: any): AccessLocation {
    return AccessLocationFromJSONTyped(json, false);
}

export function AccessLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function AccessLocationToJSON(json: any): AccessLocation {
    return AccessLocationToJSONTyped(json, false);
}

export function AccessLocationToJSONTyped(value?: AccessLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'description': value['description'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}
