/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AccessEvent
 */
export interface AccessEvent {
    /**
     * Event ID
     * @type {string}
     * @memberof AccessEvent
     */
    id: string;
    /**
     * Event action (e.g., door.unlock, member.create)
     * @type {string}
     * @memberof AccessEvent
     */
    action: string;
    /**
     * Actor entity type
     * @type {string}
     * @memberof AccessEvent
     */
    actorType?: string;
    /**
     * Actor ID
     * @type {string}
     * @memberof AccessEvent
     */
    actorId?: string;
    /**
     * Actor email
     * @type {string}
     * @memberof AccessEvent
     */
    actorEmail?: string;
    /**
     * Object entity type
     * @type {string}
     * @memberof AccessEvent
     */
    objectType?: string;
    /**
     * Object ID
     * @type {string}
     * @memberof AccessEvent
     */
    objectId?: string;
    /**
     * Related door ID
     * @type {string}
     * @memberof AccessEvent
     */
    doorId?: string;
    /**
     * Human-readable event message
     * @type {string}
     * @memberof AccessEvent
     */
    message?: string;
    /**
     * Timestamp (ISO 8601)
     * @type {string}
     * @memberof AccessEvent
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the AccessEvent interface.
 */
export function instanceOfAccessEvent(value: object): value is AccessEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function AccessEventFromJSON(json: any): AccessEvent {
    return AccessEventFromJSONTyped(json, false);
}

export function AccessEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'action': json['action'],
        'actorType': json['actorType'] == null ? undefined : json['actorType'],
        'actorId': json['actorId'] == null ? undefined : json['actorId'],
        'actorEmail': json['actorEmail'] == null ? undefined : json['actorEmail'],
        'objectType': json['objectType'] == null ? undefined : json['objectType'],
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
        'doorId': json['doorId'] == null ? undefined : json['doorId'],
        'message': json['message'] == null ? undefined : json['message'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function AccessEventToJSON(json: any): AccessEvent {
    return AccessEventToJSONTyped(json, false);
}

export function AccessEventToJSONTyped(value?: AccessEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'action': value['action'],
        'actorType': value['actorType'],
        'actorId': value['actorId'],
        'actorEmail': value['actorEmail'],
        'objectType': value['objectType'],
        'objectId': value['objectId'],
        'doorId': value['doorId'],
        'message': value['message'],
        'createdAt': value['createdAt'],
    };
}
