/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessControlConfigStatusKisi } from './AccessControlConfigStatusKisi';
import {
    AccessControlConfigStatusKisiFromJSON,
    AccessControlConfigStatusKisiFromJSONTyped,
    AccessControlConfigStatusKisiToJSON,
    AccessControlConfigStatusKisiToJSONTyped,
} from './AccessControlConfigStatusKisi';
import type { AccessControlConfigStatusUnifiAccess } from './AccessControlConfigStatusUnifiAccess';
import {
    AccessControlConfigStatusUnifiAccessFromJSON,
    AccessControlConfigStatusUnifiAccessFromJSONTyped,
    AccessControlConfigStatusUnifiAccessToJSON,
    AccessControlConfigStatusUnifiAccessToJSONTyped,
} from './AccessControlConfigStatusUnifiAccess';

/**
 * @export
 * @interface AccessControlConfigStatus
 */
export interface AccessControlConfigStatus {
    /**
     * Whether an access control provider is configured
     * @type {boolean}
     * @memberof AccessControlConfigStatus
     */
    configured: boolean;
    /**
     * Active provider type (kisi or unifi-access)
     * @type {string | null}
     * @memberof AccessControlConfigStatus
     */
    provider: string | null;
    /**
     * @type {AccessControlConfigStatusKisi}
     * @memberof AccessControlConfigStatus
     */
    kisi: AccessControlConfigStatusKisi;
    /**
     * @type {AccessControlConfigStatusUnifiAccess}
     * @memberof AccessControlConfigStatus
     */
    unifiAccess: AccessControlConfigStatusUnifiAccess;
}

/**
 * Check if a given object implements the AccessControlConfigStatus interface.
 */
export function instanceOfAccessControlConfigStatus(value: object): value is AccessControlConfigStatus {
    if (!('unifiAccess' in value) || value['unifiAccess'] === undefined) return false;
    if (!('configured' in value) || value['configured'] === undefined) return false;
    if (!('kisi' in value) || value['kisi'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function AccessControlConfigStatusFromJSON(json: any): AccessControlConfigStatus {
    return AccessControlConfigStatusFromJSONTyped(json, false);
}

export function AccessControlConfigStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessControlConfigStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'],
        'provider': json['provider'],
        'kisi': AccessControlConfigStatusKisiFromJSON(json['kisi']),
        'unifiAccess': AccessControlConfigStatusUnifiAccessFromJSON(json['unifiAccess']),
    };
}

export function AccessControlConfigStatusToJSON(json: any): AccessControlConfigStatus {
    return AccessControlConfigStatusToJSONTyped(json, false);
}

export function AccessControlConfigStatusToJSONTyped(value?: AccessControlConfigStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'provider': value['provider'],
        'kisi': AccessControlConfigStatusKisiToJSON(value['kisi']),
        'unifiAccess': AccessControlConfigStatusUnifiAccessToJSON(value['unifiAccess']),
    };
}
