/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessHealthResponseCapabilities } from './AccessHealthResponseCapabilities';
import {
    AccessHealthResponseCapabilitiesFromJSON,
    AccessHealthResponseCapabilitiesFromJSONTyped,
    AccessHealthResponseCapabilitiesToJSON,
    AccessHealthResponseCapabilitiesToJSONTyped,
} from './AccessHealthResponseCapabilities';

/**
 * @export
 * @interface AccessHealthResponse
 */
export interface AccessHealthResponse {
    /**
     * Whether an access control provider is configured
     * @type {boolean}
     * @memberof AccessHealthResponse
     */
    configured: boolean;
    /**
     * Whether the provider backend is reachable
     * @type {boolean}
     * @memberof AccessHealthResponse
     */
    connected: boolean;
    /**
     * Active provider name (kisi, unifi-access)
     * @type {string}
     * @memberof AccessHealthResponse
     */
    provider?: string;
    /**
     * Provider capabilities
     * @type {AccessHealthResponseCapabilities}
     * @memberof AccessHealthResponse
     */
    capabilities?: AccessHealthResponseCapabilities;
}

/**
 * Check if a given object implements the AccessHealthResponse interface.
 */
export function instanceOfAccessHealthResponse(value: object): value is AccessHealthResponse {
    if (!('configured' in value) || value['configured'] === undefined) return false;
    if (!('connected' in value) || value['connected'] === undefined) return false;
    return true;
}

export function AccessHealthResponseFromJSON(json: any): AccessHealthResponse {
    return AccessHealthResponseFromJSONTyped(json, false);
}

export function AccessHealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessHealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'],
        'connected': json['connected'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'capabilities': json['capabilities'] == null ? undefined : AccessHealthResponseCapabilitiesFromJSON(json['capabilities']),
    };
}

export function AccessHealthResponseToJSON(json: any): AccessHealthResponse {
    return AccessHealthResponseToJSONTyped(json, false);
}

export function AccessHealthResponseToJSONTyped(value?: AccessHealthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'connected': value['connected'],
        'provider': value['provider'],
        'capabilities': AccessHealthResponseCapabilitiesToJSON(value['capabilities']),
    };
}
