/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AccessLocationsResponsePagination
 */
export interface AccessLocationsResponsePagination {
    /**
     * Current offset
     * @type {number}
     * @memberof AccessLocationsResponsePagination
     */
    offset: number;
    /**
     * Page size
     * @type {number}
     * @memberof AccessLocationsResponsePagination
     */
    limit: number;
    /**
     * Total item count
     * @type {number}
     * @memberof AccessLocationsResponsePagination
     */
    count: number;
}

/**
 * Check if a given object implements the AccessLocationsResponsePagination interface.
 */
export function instanceOfAccessLocationsResponsePagination(value: object): value is AccessLocationsResponsePagination {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function AccessLocationsResponsePaginationFromJSON(json: any): AccessLocationsResponsePagination {
    return AccessLocationsResponsePaginationFromJSONTyped(json, false);
}

export function AccessLocationsResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessLocationsResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'],
        'limit': json['limit'],
        'count': json['count'],
    };
}

export function AccessLocationsResponsePaginationToJSON(json: any): AccessLocationsResponsePagination {
    return AccessLocationsResponsePaginationToJSONTyped(json, false);
}

export function AccessLocationsResponsePaginationToJSONTyped(value?: AccessLocationsResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'limit': value['limit'],
        'count': value['count'],
    };
}
