/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessGroup } from './AccessGroup';
import {
    AccessGroupFromJSON,
    AccessGroupFromJSONTyped,
    AccessGroupToJSON,
    AccessGroupToJSONTyped,
} from './AccessGroup';
import type { AccessLocationsResponsePagination } from './AccessLocationsResponsePagination';
import {
    AccessLocationsResponsePaginationFromJSON,
    AccessLocationsResponsePaginationFromJSONTyped,
    AccessLocationsResponsePaginationToJSON,
    AccessLocationsResponsePaginationToJSONTyped,
} from './AccessLocationsResponsePagination';

/**
 * @export
 * @interface AccessGroupsResponse
 */
export interface AccessGroupsResponse {
    /**
     * @type {Array<AccessGroup>}
     * @memberof AccessGroupsResponse
     */
    data: Array<AccessGroup>;
    /**
     * @type {AccessLocationsResponsePagination}
     * @memberof AccessGroupsResponse
     */
    pagination: AccessLocationsResponsePagination;
}

/**
 * Check if a given object implements the AccessGroupsResponse interface.
 */
export function instanceOfAccessGroupsResponse(value: object): value is AccessGroupsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AccessGroupsResponseFromJSON(json: any): AccessGroupsResponse {
    return AccessGroupsResponseFromJSONTyped(json, false);
}

export function AccessGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AccessGroupFromJSON)),
        'pagination': AccessLocationsResponsePaginationFromJSON(json['pagination']),
    };
}

export function AccessGroupsResponseToJSON(json: any): AccessGroupsResponse {
    return AccessGroupsResponseToJSONTyped(json, false);
}

export function AccessGroupsResponseToJSONTyped(value?: AccessGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AccessGroupToJSON)),
        'pagination': AccessLocationsResponsePaginationToJSON(value['pagination']),
    };
}
