/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAuditActor } from './AdminAuditActor';
import {
    AdminAuditActorFromJSON,
    AdminAuditActorFromJSONTyped,
    AdminAuditActorToJSON,
    AdminAuditActorToJSONTyped,
} from './AdminAuditActor';

/**
 * @export
 * @interface AdminAuditEvent
 */
export interface AdminAuditEvent {
    /**
     * Unique event ID
     * @type {string}
     * @memberof AdminAuditEvent
     */
    id: string;
    /**
     * ISO 8601 timestamp
     * @type {string}
     * @memberof AdminAuditEvent
     */
    timestamp: string;
    /**
     * @type {AdminAuditActor}
     * @memberof AdminAuditEvent
     */
    actor: AdminAuditActor;
    /**
     * HTTP method (POST, PUT, DELETE, …)
     * @type {string}
     * @memberof AdminAuditEvent
     */
    method: string;
    /**
     * Request path
     * @type {string}
     * @memberof AdminAuditEvent
     */
    path: string;
    /**
     * @type {AdminAuditEventActionEnum}
     * @memberof AdminAuditEvent
     */
    action: AdminAuditEventActionEnum;
    /**
     * Resource domain (smart-apps, healthcare-users, …)
     * @type {string}
     * @memberof AdminAuditEvent
     */
    resource: string;
    /**
     * Target resource identifier
     * @type {string}
     * @memberof AdminAuditEvent
     */
    resourceId?: string;
    /**
     * HTTP response status code
     * @type {number}
     * @memberof AdminAuditEvent
     */
    statusCode: number;
    /**
     * Whether the request succeeded (2xx)
     * @type {boolean}
     * @memberof AdminAuditEvent
     */
    success: boolean;
    /**
     * Request duration in milliseconds
     * @type {number}
     * @memberof AdminAuditEvent
     */
    durationMs: number;
    /**
     * Client IP address
     * @type {string}
     * @memberof AdminAuditEvent
     */
    ipAddress?: string;
    /**
     * Human-readable summary of the action
     * @type {string}
     * @memberof AdminAuditEvent
     */
    detail?: string;
}

/**
 * @export
 */
export const AdminAuditEventActionEnum = {
    Create: 'create',
    Update: 'update',
    Delete: 'delete',
    Action: 'action',
    Read: 'read',
} as const;
export type AdminAuditEventActionEnum = typeof AdminAuditEventActionEnum[keyof typeof AdminAuditEventActionEnum];

/**
 * Check if a given object implements the AdminAuditEvent interface.
 */
export function instanceOfAdminAuditEvent(value: object): value is AdminAuditEvent {
    if (!('actor' in value) || value['actor'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('durationMs' in value) || value['durationMs'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('resource' in value) || value['resource'] === undefined) return false;
    return true;
}

export function AdminAuditEventFromJSON(json: any): AdminAuditEvent {
    return AdminAuditEventFromJSONTyped(json, false);
}

export function AdminAuditEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'actor': AdminAuditActorFromJSON(json['actor']),
        'method': json['method'],
        'path': json['path'],
        'action': json['action'],
        'resource': json['resource'],
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'statusCode': json['statusCode'],
        'success': json['success'],
        'durationMs': json['durationMs'],
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function AdminAuditEventToJSON(json: any): AdminAuditEvent {
    return AdminAuditEventToJSONTyped(json, false);
}

export function AdminAuditEventToJSONTyped(value?: AdminAuditEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'],
        'actor': AdminAuditActorToJSON(value['actor']),
        'method': value['method'],
        'path': value['path'],
        'action': value['action'],
        'resource': value['resource'],
        'resourceId': value['resourceId'],
        'statusCode': value['statusCode'],
        'success': value['success'],
        'durationMs': value['durationMs'],
        'ipAddress': value['ipAddress'],
        'detail': value['detail'],
    };
}
