/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAuditAnalyticsResponseTopActorsInner } from './AdminAuditAnalyticsResponseTopActorsInner';
import {
    AdminAuditAnalyticsResponseTopActorsInnerFromJSON,
    AdminAuditAnalyticsResponseTopActorsInnerFromJSONTyped,
    AdminAuditAnalyticsResponseTopActorsInnerToJSON,
    AdminAuditAnalyticsResponseTopActorsInnerToJSONTyped,
} from './AdminAuditAnalyticsResponseTopActorsInner';
import type { AdminAuditEvent } from './AdminAuditEvent';
import {
    AdminAuditEventFromJSON,
    AdminAuditEventFromJSONTyped,
    AdminAuditEventToJSON,
    AdminAuditEventToJSONTyped,
} from './AdminAuditEvent';
import type { AdminAuditHourlyStats } from './AdminAuditHourlyStats';
import {
    AdminAuditHourlyStatsFromJSON,
    AdminAuditHourlyStatsFromJSONTyped,
    AdminAuditHourlyStatsToJSON,
    AdminAuditHourlyStatsToJSONTyped,
} from './AdminAuditHourlyStats';

/**
 * @export
 * @interface AdminAuditAnalyticsResponse
 */
export interface AdminAuditAnalyticsResponse {
    /**
     * Total admin actions in the last 24 h
     * @type {number}
     * @memberof AdminAuditAnalyticsResponse
     */
    totalActions: number;
    /**
     * Success rate (%)
     * @type {number}
     * @memberof AdminAuditAnalyticsResponse
     */
    successRate: number;
    /**
     * Actions grouped by type
     * @type {{ [key: string]: number }}
     * @memberof AdminAuditAnalyticsResponse
     */
    actionsByType: { [key: string]: number };
    /**
     * Actions grouped by resource
     * @type {{ [key: string]: number }}
     * @memberof AdminAuditAnalyticsResponse
     */
    actionsByResource: { [key: string]: number };
    /**
     * Top actors by action count
     * @type {Array<AdminAuditAnalyticsResponseTopActorsInner>}
     * @memberof AdminAuditAnalyticsResponse
     */
    topActors: Array<AdminAuditAnalyticsResponseTopActorsInner>;
    /**
     * Hourly breakdown
     * @type {Array<AdminAuditHourlyStats>}
     * @memberof AdminAuditAnalyticsResponse
     */
    hourlyStats: Array<AdminAuditHourlyStats>;
    /**
     * Most recent failed actions
     * @type {Array<AdminAuditEvent>}
     * @memberof AdminAuditAnalyticsResponse
     */
    recentFailures: Array<AdminAuditEvent>;
    /**
     * Response timestamp
     * @type {string}
     * @memberof AdminAuditAnalyticsResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the AdminAuditAnalyticsResponse interface.
 */
export function instanceOfAdminAuditAnalyticsResponse(value: object): value is AdminAuditAnalyticsResponse {
    if (!('topActors' in value) || value['topActors'] === undefined) return false;
    if (!('actionsByResource' in value) || value['actionsByResource'] === undefined) return false;
    if (!('hourlyStats' in value) || value['hourlyStats'] === undefined) return false;
    if (!('recentFailures' in value) || value['recentFailures'] === undefined) return false;
    if (!('successRate' in value) || value['successRate'] === undefined) return false;
    if (!('totalActions' in value) || value['totalActions'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('actionsByType' in value) || value['actionsByType'] === undefined) return false;
    return true;
}

export function AdminAuditAnalyticsResponseFromJSON(json: any): AdminAuditAnalyticsResponse {
    return AdminAuditAnalyticsResponseFromJSONTyped(json, false);
}

export function AdminAuditAnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditAnalyticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalActions': json['totalActions'],
        'successRate': json['successRate'],
        'actionsByType': json['actionsByType'],
        'actionsByResource': json['actionsByResource'],
        'topActors': ((json['topActors'] as Array<any>).map(AdminAuditAnalyticsResponseTopActorsInnerFromJSON)),
        'hourlyStats': ((json['hourlyStats'] as Array<any>).map(AdminAuditHourlyStatsFromJSON)),
        'recentFailures': ((json['recentFailures'] as Array<any>).map(AdminAuditEventFromJSON)),
        'timestamp': json['timestamp'],
    };
}

export function AdminAuditAnalyticsResponseToJSON(json: any): AdminAuditAnalyticsResponse {
    return AdminAuditAnalyticsResponseToJSONTyped(json, false);
}

export function AdminAuditAnalyticsResponseToJSONTyped(value?: AdminAuditAnalyticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalActions': value['totalActions'],
        'successRate': value['successRate'],
        'actionsByType': value['actionsByType'],
        'actionsByResource': value['actionsByResource'],
        'topActors': value['topActors'] == null ? undefined : ((value['topActors'] as Array<any>).map(AdminAuditAnalyticsResponseTopActorsInnerToJSON)),
        'hourlyStats': value['hourlyStats'] == null ? undefined : ((value['hourlyStats'] as Array<any>).map(AdminAuditHourlyStatsToJSON)),
        'recentFailures': value['recentFailures'] == null ? undefined : ((value['recentFailures'] as Array<any>).map(AdminAuditEventToJSON)),
        'timestamp': value['timestamp'],
    };
}
