/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AdminAuditHourlyStats
 */
export interface AdminAuditHourlyStats {
    /**
     * Hour bucket (ISO 8601)
     * @type {string}
     * @memberof AdminAuditHourlyStats
     */
    hour: string;
    /**
     * Successful actions
     * @type {number}
     * @memberof AdminAuditHourlyStats
     */
    success: number;
    /**
     * Failed actions
     * @type {number}
     * @memberof AdminAuditHourlyStats
     */
    failure: number;
    /**
     * Total actions
     * @type {number}
     * @memberof AdminAuditHourlyStats
     */
    total: number;
}

/**
 * Check if a given object implements the AdminAuditHourlyStats interface.
 */
export function instanceOfAdminAuditHourlyStats(value: object): value is AdminAuditHourlyStats {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('failure' in value) || value['failure'] === undefined) return false;
    if (!('hour' in value) || value['hour'] === undefined) return false;
    return true;
}

export function AdminAuditHourlyStatsFromJSON(json: any): AdminAuditHourlyStats {
    return AdminAuditHourlyStatsFromJSONTyped(json, false);
}

export function AdminAuditHourlyStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditHourlyStats {
    if (json == null) {
        return json;
    }
    return {
        
        'hour': json['hour'],
        'success': json['success'],
        'failure': json['failure'],
        'total': json['total'],
    };
}

export function AdminAuditHourlyStatsToJSON(json: any): AdminAuditHourlyStats {
    return AdminAuditHourlyStatsToJSONTyped(json, false);
}

export function AdminAuditHourlyStatsToJSONTyped(value?: AdminAuditHourlyStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hour': value['hour'],
        'success': value['success'],
        'failure': value['failure'],
        'total': value['total'],
    };
}
