/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppStoreApp } from './AppStoreApp';
import {
    AppStoreAppFromJSON,
    AppStoreAppFromJSONTyped,
    AppStoreAppToJSON,
    AppStoreAppToJSONTyped,
} from './AppStoreApp';
import type { PublishedApp } from './PublishedApp';
import {
    PublishedAppFromJSON,
    PublishedAppFromJSONTyped,
    PublishedAppToJSON,
    PublishedAppToJSONTyped,
} from './PublishedApp';

/**
 * @export
 * @interface AppStoreListResponse
 */
export interface AppStoreListResponse {
    /**
     * @type {Array<AppStoreApp>}
     * @memberof AppStoreListResponse
     */
    apps: Array<AppStoreApp>;
    /**
     * @type {Array<PublishedApp>}
     * @memberof AppStoreListResponse
     */
    publishedApps: Array<PublishedApp>;
    /**
     * @type {Array<string>}
     * @memberof AppStoreListResponse
     */
    hiddenAppIds: Array<string>;
    /**
     * @type {string}
     * @memberof AppStoreListResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the AppStoreListResponse interface.
 */
export function instanceOfAppStoreListResponse(value: object): value is AppStoreListResponse {
    if (!('hiddenAppIds' in value) || value['hiddenAppIds'] === undefined) return false;
    if (!('apps' in value) || value['apps'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('publishedApps' in value) || value['publishedApps'] === undefined) return false;
    return true;
}

export function AppStoreListResponseFromJSON(json: any): AppStoreListResponse {
    return AppStoreListResponseFromJSONTyped(json, false);
}

export function AppStoreListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apps': ((json['apps'] as Array<any>).map(AppStoreAppFromJSON)),
        'publishedApps': ((json['publishedApps'] as Array<any>).map(PublishedAppFromJSON)),
        'hiddenAppIds': json['hiddenAppIds'],
        'updatedAt': json['updatedAt'],
    };
}

export function AppStoreListResponseToJSON(json: any): AppStoreListResponse {
    return AppStoreListResponseToJSONTyped(json, false);
}

export function AppStoreListResponseToJSONTyped(value?: AppStoreListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apps': value['apps'] == null ? undefined : ((value['apps'] as Array<any>).map(AppStoreAppToJSON)),
        'publishedApps': value['publishedApps'] == null ? undefined : ((value['publishedApps'] as Array<any>).map(PublishedAppToJSON)),
        'hiddenAppIds': value['hiddenAppIds'],
        'updatedAt': value['updatedAt'],
    };
}
