/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AssignDoorRequest
 */
export interface AssignDoorRequest {
    /**
     * Group ID
     * @type {string}
     * @memberof AssignDoorRequest
     */
    groupId: string;
    /**
     * Door ID
     * @type {string}
     * @memberof AssignDoorRequest
     */
    doorId: string;
}

/**
 * Check if a given object implements the AssignDoorRequest interface.
 */
export function instanceOfAssignDoorRequest(value: object): value is AssignDoorRequest {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('doorId' in value) || value['doorId'] === undefined) return false;
    return true;
}

export function AssignDoorRequestFromJSON(json: any): AssignDoorRequest {
    return AssignDoorRequestFromJSONTyped(json, false);
}

export function AssignDoorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignDoorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'doorId': json['doorId'],
    };
}

export function AssignDoorRequestToJSON(json: any): AssignDoorRequest {
    return AssignDoorRequestToJSONTyped(json, false);
}

export function AssignDoorRequestToJSONTyped(value?: AssignDoorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupId': value['groupId'],
        'doorId': value['doorId'],
    };
}
