/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthEvent } from './AuthEvent';
import {
    AuthEventFromJSON,
    AuthEventFromJSONTyped,
    AuthEventToJSON,
    AuthEventToJSONTyped,
} from './AuthEvent';

/**
 * @export
 * @interface AuthEventsResponse
 */
export interface AuthEventsResponse {
    /**
     * Array of auth events
     * @type {Array<AuthEvent>}
     * @memberof AuthEventsResponse
     */
    events: Array<AuthEvent>;
    /**
     * Total events returned
     * @type {number}
     * @memberof AuthEventsResponse
     */
    total: number;
    /**
     * Response timestamp
     * @type {string}
     * @memberof AuthEventsResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the AuthEventsResponse interface.
 */
export function instanceOfAuthEventsResponse(value: object): value is AuthEventsResponse {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function AuthEventsResponseFromJSON(json: any): AuthEventsResponse {
    return AuthEventsResponseFromJSONTyped(json, false);
}

export function AuthEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(AuthEventFromJSON)),
        'total': json['total'],
        'timestamp': json['timestamp'],
    };
}

export function AuthEventsResponseToJSON(json: any): AuthEventsResponse {
    return AuthEventsResponseToJSONTyped(json, false);
}

export function AuthEventsResponseToJSONTyped(value?: AuthEventsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(AuthEventToJSON)),
        'total': value['total'],
        'timestamp': value['timestamp'],
    };
}
