/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AuthTopClient
 */
export interface AuthTopClient {
    /**
     * OAuth client ID
     * @type {string}
     * @memberof AuthTopClient
     */
    clientId: string;
    /**
     * Number of events for this client
     * @type {number}
     * @memberof AuthTopClient
     */
    count: number;
}

/**
 * Check if a given object implements the AuthTopClient interface.
 */
export function instanceOfAuthTopClient(value: object): value is AuthTopClient {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function AuthTopClientFromJSON(json: any): AuthTopClient {
    return AuthTopClientFromJSONTyped(json, false);
}

export function AuthTopClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTopClient {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'],
        'count': json['count'],
    };
}

export function AuthTopClientToJSON(json: any): AuthTopClient {
    return AuthTopClientToJSONTyped(json, false);
}

export function AuthTopClientToJSONTyped(value?: AuthTopClient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientId': value['clientId'],
        'count': value['count'],
    };
}
