/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface AuthEvent
 */
export interface AuthEvent {
    /**
     * Unique event ID (from Keycloak or generated)
     * @type {string}
     * @memberof AuthEvent
     */
    id: string;
    /**
     * ISO 8601 timestamp
     * @type {string}
     * @memberof AuthEvent
     */
    timestamp: string;
    /**
     * Keycloak event type (LOGIN, LOGOUT, REGISTER, CODE_TO_TOKEN, …)
     * @type {string}
     * @memberof AuthEvent
     */
    type: string;
    /**
     * Keycloak user ID
     * @type {string}
     * @memberof AuthEvent
     */
    userId?: string;
    /**
     * OAuth client that triggered the event
     * @type {string}
     * @memberof AuthEvent
     */
    clientId?: string;
    /**
     * Keycloak session ID
     * @type {string}
     * @memberof AuthEvent
     */
    sessionId?: string;
    /**
     * IP address of the request
     * @type {string}
     * @memberof AuthEvent
     */
    ipAddress?: string;
    /**
     * Error message if the event failed
     * @type {string}
     * @memberof AuthEvent
     */
    error?: string;
    /**
     * Whether the auth action succeeded
     * @type {boolean}
     * @memberof AuthEvent
     */
    success: boolean;
    /**
     * Additional event details from Keycloak
     * @type {{ [key: string]: string }}
     * @memberof AuthEvent
     */
    details?: { [key: string]: string };
}

/**
 * Check if a given object implements the AuthEvent interface.
 */
export function instanceOfAuthEvent(value: object): value is AuthEvent {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AuthEventFromJSON(json: any): AuthEvent {
    return AuthEventFromJSONTyped(json, false);
}

export function AuthEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'type': json['type'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'error': json['error'] == null ? undefined : json['error'],
        'success': json['success'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function AuthEventToJSON(json: any): AuthEvent {
    return AuthEventToJSONTyped(json, false);
}

export function AuthEventToJSONTyped(value?: AuthEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'],
        'type': value['type'],
        'userId': value['userId'],
        'clientId': value['clientId'],
        'sessionId': value['sessionId'],
        'ipAddress': value['ipAddress'],
        'error': value['error'],
        'success': value['success'],
        'details': value['details'],
    };
}
