/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAuditHourlyStats } from './AdminAuditHourlyStats';
import {
    AdminAuditHourlyStatsFromJSON,
    AdminAuditHourlyStatsFromJSONTyped,
    AdminAuditHourlyStatsToJSON,
    AdminAuditHourlyStatsToJSONTyped,
} from './AdminAuditHourlyStats';
import type { AuthEvent } from './AuthEvent';
import {
    AuthEventFromJSON,
    AuthEventFromJSONTyped,
    AuthEventToJSON,
    AuthEventToJSONTyped,
} from './AuthEvent';
import type { AuthTopClient } from './AuthTopClient';
import {
    AuthTopClientFromJSON,
    AuthTopClientFromJSONTyped,
    AuthTopClientToJSON,
    AuthTopClientToJSONTyped,
} from './AuthTopClient';

/**
 * @export
 * @interface AuthAnalyticsResponse
 */
export interface AuthAnalyticsResponse {
    /**
     * Total auth events in the last 24 h
     * @type {number}
     * @memberof AuthAnalyticsResponse
     */
    totalEvents: number;
    /**
     * Success rate (%)
     * @type {number}
     * @memberof AuthAnalyticsResponse
     */
    successRate: number;
    /**
     * Events grouped by type
     * @type {{ [key: string]: number }}
     * @memberof AuthAnalyticsResponse
     */
    eventsByType: { [key: string]: number };
    /**
     * Most recent failed events
     * @type {Array<AuthEvent>}
     * @memberof AuthAnalyticsResponse
     */
    recentErrors: Array<AuthEvent>;
    /**
     * Hourly breakdown
     * @type {Array<AdminAuditHourlyStats>}
     * @memberof AuthAnalyticsResponse
     */
    hourlyStats: Array<AdminAuditHourlyStats>;
    /**
     * Top 10 clients by event count
     * @type {Array<AuthTopClient>}
     * @memberof AuthAnalyticsResponse
     */
    topClients: Array<AuthTopClient>;
    /**
     * Response timestamp
     * @type {string}
     * @memberof AuthAnalyticsResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the AuthAnalyticsResponse interface.
 */
export function instanceOfAuthAnalyticsResponse(value: object): value is AuthAnalyticsResponse {
    if (!('topClients' in value) || value['topClients'] === undefined) return false;
    if (!('recentErrors' in value) || value['recentErrors'] === undefined) return false;
    if (!('eventsByType' in value) || value['eventsByType'] === undefined) return false;
    if (!('totalEvents' in value) || value['totalEvents'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('successRate' in value) || value['successRate'] === undefined) return false;
    if (!('hourlyStats' in value) || value['hourlyStats'] === undefined) return false;
    return true;
}

export function AuthAnalyticsResponseFromJSON(json: any): AuthAnalyticsResponse {
    return AuthAnalyticsResponseFromJSONTyped(json, false);
}

export function AuthAnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAnalyticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalEvents': json['totalEvents'],
        'successRate': json['successRate'],
        'eventsByType': json['eventsByType'],
        'recentErrors': ((json['recentErrors'] as Array<any>).map(AuthEventFromJSON)),
        'hourlyStats': ((json['hourlyStats'] as Array<any>).map(AdminAuditHourlyStatsFromJSON)),
        'topClients': ((json['topClients'] as Array<any>).map(AuthTopClientFromJSON)),
        'timestamp': json['timestamp'],
    };
}

export function AuthAnalyticsResponseToJSON(json: any): AuthAnalyticsResponse {
    return AuthAnalyticsResponseToJSONTyped(json, false);
}

export function AuthAnalyticsResponseToJSONTyped(value?: AuthAnalyticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalEvents': value['totalEvents'],
        'successRate': value['successRate'],
        'eventsByType': value['eventsByType'],
        'recentErrors': value['recentErrors'] == null ? undefined : ((value['recentErrors'] as Array<any>).map(AuthEventToJSON)),
        'hourlyStats': value['hourlyStats'] == null ? undefined : ((value['hourlyStats'] as Array<any>).map(AdminAuditHourlyStatsToJSON)),
        'topClients': value['topClients'] == null ? undefined : ((value['topClients'] as Array<any>).map(AuthTopClientToJSON)),
        'timestamp': value['timestamp'],
    };
}
