/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface BrandConfig
 */
export interface BrandConfig {
    /**
     * Brand display name
     * @type {string}
     * @memberof BrandConfig
     */
    name: string;
    /**
     * Brand website URL
     * @type {string}
     * @memberof BrandConfig
     */
    website: string;
    /**
     * Brand logo URL (SVG or 1024px PNG, transparent background)
     * @type {string | null}
     * @memberof BrandConfig
     */
    logoUrl: string | null;
    /**
     * Logo license URL
     * @type {string | null}
     * @memberof BrandConfig
     */
    logoLicenseUrl: string | null;
    /**
     * Alternative brand names
     * @type {Array<string>}
     * @memberof BrandConfig
     */
    aliases: Array<string>;
    /**
     * @type {BrandConfigCategoryEnum}
     * @memberof BrandConfig
     */
    category: BrandConfigCategoryEnum;
    /**
     * Patient-facing portal name
     * @type {string | null}
     * @memberof BrandConfig
     */
    portalName: string | null;
    /**
     * Patient-facing portal URL
     * @type {string | null}
     * @memberof BrandConfig
     */
    portalUrl: string | null;
    /**
     * Patient-facing portal description (Markdown)
     * @type {string | null}
     * @memberof BrandConfig
     */
    portalDescription: string | null;
    /**
     * Patient-facing portal logo URL
     * @type {string | null}
     * @memberof BrandConfig
     */
    portalLogoUrl: string | null;
    /**
     * Portal logo license URL
     * @type {string | null}
     * @memberof BrandConfig
     */
    portalLogoLicenseUrl: string | null;
    /**
     * Organization city
     * @type {string | null}
     * @memberof BrandConfig
     */
    addressCity: string | null;
    /**
     * Organization state/province
     * @type {string | null}
     * @memberof BrandConfig
     */
    addressState: string | null;
    /**
     * Organization postal code
     * @type {string | null}
     * @memberof BrandConfig
     */
    addressPostalCode: string | null;
    /**
     * Organization country
     * @type {string | null}
     * @memberof BrandConfig
     */
    addressCountry: string | null;
    /**
     * Brand identifier URI (typically the brand website URL)
     * @type {string}
     * @memberof BrandConfig
     */
    identifier: string;
}

/**
 * @export
 */
export const BrandConfigCategoryEnum = {
    Prov: 'prov',
    Ins: 'ins',
    Laboratory: 'laboratory',
    Imaging: 'imaging',
    Pharmacy: 'pharmacy',
    HealthInformationNetwork: 'health-information-network',
    HealthDataAggregator: 'health-data-aggregator',
} as const;
export type BrandConfigCategoryEnum = typeof BrandConfigCategoryEnum[keyof typeof BrandConfigCategoryEnum];

/**
 * Check if a given object implements the BrandConfig interface.
 */
export function instanceOfBrandConfig(value: object): value is BrandConfig {
    if (!('logoUrl' in value) || value['logoUrl'] === undefined) return false;
    if (!('aliases' in value) || value['aliases'] === undefined) return false;
    if (!('addressCity' in value) || value['addressCity'] === undefined) return false;
    if (!('portalLogoLicenseUrl' in value) || value['portalLogoLicenseUrl'] === undefined) return false;
    if (!('logoLicenseUrl' in value) || value['logoLicenseUrl'] === undefined) return false;
    if (!('portalDescription' in value) || value['portalDescription'] === undefined) return false;
    if (!('portalName' in value) || value['portalName'] === undefined) return false;
    if (!('portalLogoUrl' in value) || value['portalLogoUrl'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('addressPostalCode' in value) || value['addressPostalCode'] === undefined) return false;
    if (!('portalUrl' in value) || value['portalUrl'] === undefined) return false;
    if (!('addressCountry' in value) || value['addressCountry'] === undefined) return false;
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('addressState' in value) || value['addressState'] === undefined) return false;
    return true;
}

export function BrandConfigFromJSON(json: any): BrandConfig {
    return BrandConfigFromJSONTyped(json, false);
}

export function BrandConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'website': json['website'],
        'logoUrl': json['logoUrl'],
        'logoLicenseUrl': json['logoLicenseUrl'],
        'aliases': json['aliases'],
        'category': json['category'],
        'portalName': json['portalName'],
        'portalUrl': json['portalUrl'],
        'portalDescription': json['portalDescription'],
        'portalLogoUrl': json['portalLogoUrl'],
        'portalLogoLicenseUrl': json['portalLogoLicenseUrl'],
        'addressCity': json['addressCity'],
        'addressState': json['addressState'],
        'addressPostalCode': json['addressPostalCode'],
        'addressCountry': json['addressCountry'],
        'identifier': json['identifier'],
    };
}

export function BrandConfigToJSON(json: any): BrandConfig {
    return BrandConfigToJSONTyped(json, false);
}

export function BrandConfigToJSONTyped(value?: BrandConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'website': value['website'],
        'logoUrl': value['logoUrl'],
        'logoLicenseUrl': value['logoLicenseUrl'],
        'aliases': value['aliases'],
        'category': value['category'],
        'portalName': value['portalName'],
        'portalUrl': value['portalUrl'],
        'portalDescription': value['portalDescription'],
        'portalLogoUrl': value['portalLogoUrl'],
        'portalLogoLicenseUrl': value['portalLogoLicenseUrl'],
        'addressCity': value['addressCity'],
        'addressState': value['addressState'],
        'addressPostalCode': value['addressPostalCode'],
        'addressCountry': value['addressCountry'],
        'identifier': value['identifier'],
    };
}
