/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatResponseTokensUsed } from './ChatResponseTokensUsed';
import {
    ChatResponseTokensUsedFromJSON,
    ChatResponseTokensUsedFromJSONTyped,
    ChatResponseTokensUsedToJSON,
    ChatResponseTokensUsedToJSONTyped,
} from './ChatResponseTokensUsed';
import type { DocumentChunk } from './DocumentChunk';
import {
    DocumentChunkFromJSON,
    DocumentChunkFromJSONTyped,
    DocumentChunkToJSON,
    DocumentChunkToJSONTyped,
} from './DocumentChunk';
import type { ToolExecution } from './ToolExecution';
import {
    ToolExecutionFromJSON,
    ToolExecutionFromJSONTyped,
    ToolExecutionToJSON,
    ToolExecutionToJSONTyped,
} from './ToolExecution';

/**
 * @export
 * @interface ChatResponse
 */
export interface ChatResponse {
    /**
     * AI-generated response
     * @type {string}
     * @memberof ChatResponse
     */
    answer: string;
    /**
     * Conversation ID for follow-up
     * @type {string}
     * @memberof ChatResponse
     */
    conversationId: string;
    /**
     * Model used (e.g., gpt-5-mini)
     * @type {string}
     * @memberof ChatResponse
     */
    model: string;
    /**
     * RAG source documents used (optional for internal AI)
     * @type {Array<DocumentChunk>}
     * @memberof ChatResponse
     */
    sources?: Array<DocumentChunk>;
    /**
     * Details of all tools called during this request
     * @type {Array<ToolExecution>}
     * @memberof ChatResponse
     */
    toolsUsed?: Array<ToolExecution>;
    /**
     * Total request duration in milliseconds
     * @type {number}
     * @memberof ChatResponse
     */
    totalDuration?: number;
    /**
     * Token usage statistics (AI SDK format)
     * @type {ChatResponseTokensUsed}
     * @memberof ChatResponse
     */
    tokensUsed?: ChatResponseTokensUsed;
    /**
     * Response timestamp (ISO 8601)
     * @type {string}
     * @memberof ChatResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ChatResponse interface.
 */
export function instanceOfChatResponse(value: object): value is ChatResponse {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function ChatResponseFromJSON(json: any): ChatResponse {
    return ChatResponseFromJSONTyped(json, false);
}

export function ChatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'conversationId': json['conversationId'],
        'model': json['model'],
        'sources': json['sources'] == null ? undefined : ((json['sources'] as Array<any>).map(DocumentChunkFromJSON)),
        'toolsUsed': json['toolsUsed'] == null ? undefined : ((json['toolsUsed'] as Array<any>).map(ToolExecutionFromJSON)),
        'totalDuration': json['totalDuration'] == null ? undefined : json['totalDuration'],
        'tokensUsed': json['tokensUsed'] == null ? undefined : ChatResponseTokensUsedFromJSON(json['tokensUsed']),
        'timestamp': json['timestamp'],
    };
}

export function ChatResponseToJSON(json: any): ChatResponse {
    return ChatResponseToJSONTyped(json, false);
}

export function ChatResponseToJSONTyped(value?: ChatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'conversationId': value['conversationId'],
        'model': value['model'],
        'sources': value['sources'] == null ? undefined : ((value['sources'] as Array<any>).map(DocumentChunkToJSON)),
        'toolsUsed': value['toolsUsed'] == null ? undefined : ((value['toolsUsed'] as Array<any>).map(ToolExecutionToJSON)),
        'totalDuration': value['totalDuration'],
        'tokensUsed': ChatResponseTokensUsedToJSON(value['tokensUsed']),
        'timestamp': value['timestamp'],
    };
}
