/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface ConsentConfig
 */
export interface ConsentConfig {
    /**
     * Whether consent enforcement is enabled
     * @type {boolean}
     * @memberof ConsentConfig
     */
    enabled: boolean;
    /**
     * @type {ConsentConfigModeEnum}
     * @memberof ConsentConfig
     */
    mode: ConsentConfigModeEnum;
    /**
     * Cache TTL in milliseconds
     * @type {number}
     * @memberof ConsentConfig
     */
    cacheTtl: number;
    /**
     * Client IDs exempt from consent checks
     * @type {Array<string>}
     * @memberof ConsentConfig
     */
    exemptClients: Array<string>;
    /**
     * Resource types that require consent
     * @type {Array<string>}
     * @memberof ConsentConfig
     */
    requiredForResourceTypes: Array<string>;
    /**
     * Resource types exempt from consent checks
     * @type {Array<string>}
     * @memberof ConsentConfig
     */
    exemptResourceTypes: Array<string>;
}

/**
 * @export
 */
export const ConsentConfigModeEnum = {
    Enforce: 'enforce',
    AuditOnly: 'audit-only',
    Disabled: 'disabled',
} as const;
export type ConsentConfigModeEnum = typeof ConsentConfigModeEnum[keyof typeof ConsentConfigModeEnum];

/**
 * Check if a given object implements the ConsentConfig interface.
 */
export function instanceOfConsentConfig(value: object): value is ConsentConfig {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('exemptResourceTypes' in value) || value['exemptResourceTypes'] === undefined) return false;
    if (!('cacheTtl' in value) || value['cacheTtl'] === undefined) return false;
    if (!('exemptClients' in value) || value['exemptClients'] === undefined) return false;
    if (!('requiredForResourceTypes' in value) || value['requiredForResourceTypes'] === undefined) return false;
    return true;
}

export function ConsentConfigFromJSON(json: any): ConsentConfig {
    return ConsentConfigFromJSONTyped(json, false);
}

export function ConsentConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'mode': json['mode'],
        'cacheTtl': json['cacheTtl'],
        'exemptClients': json['exemptClients'],
        'requiredForResourceTypes': json['requiredForResourceTypes'],
        'exemptResourceTypes': json['exemptResourceTypes'],
    };
}

export function ConsentConfigToJSON(json: any): ConsentConfig {
    return ConsentConfigToJSONTyped(json, false);
}

export function ConsentConfigToJSONTyped(value?: ConsentConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'mode': value['mode'],
        'cacheTtl': value['cacheTtl'],
        'exemptClients': value['exemptClients'],
        'requiredForResourceTypes': value['requiredForResourceTypes'],
        'exemptResourceTypes': value['exemptResourceTypes'],
    };
}
