/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface ConsentCacheStatsEntriesInner
 */
export interface ConsentCacheStatsEntriesInner {
    /**
     * Cache key
     * @type {string}
     * @memberof ConsentCacheStatsEntriesInner
     */
    key: string;
    /**
     * Number of consents cached
     * @type {number}
     * @memberof ConsentCacheStatsEntriesInner
     */
    consentCount: number;
    /**
     * Seconds until expiration
     * @type {number}
     * @memberof ConsentCacheStatsEntriesInner
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the ConsentCacheStatsEntriesInner interface.
 */
export function instanceOfConsentCacheStatsEntriesInner(value: object): value is ConsentCacheStatsEntriesInner {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('consentCount' in value) || value['consentCount'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function ConsentCacheStatsEntriesInnerFromJSON(json: any): ConsentCacheStatsEntriesInner {
    return ConsentCacheStatsEntriesInnerFromJSONTyped(json, false);
}

export function ConsentCacheStatsEntriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentCacheStatsEntriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'consentCount': json['consentCount'],
        'expiresIn': json['expiresIn'],
    };
}

export function ConsentCacheStatsEntriesInnerToJSON(json: any): ConsentCacheStatsEntriesInner {
    return ConsentCacheStatsEntriesInnerToJSONTyped(json, false);
}

export function ConsentCacheStatsEntriesInnerToJSONTyped(value?: ConsentCacheStatsEntriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'consentCount': value['consentCount'],
        'expiresIn': value['expiresIn'],
    };
}
