/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsentCacheStatsEntriesInner } from './ConsentCacheStatsEntriesInner';
import {
    ConsentCacheStatsEntriesInnerFromJSON,
    ConsentCacheStatsEntriesInnerFromJSONTyped,
    ConsentCacheStatsEntriesInnerToJSON,
    ConsentCacheStatsEntriesInnerToJSONTyped,
} from './ConsentCacheStatsEntriesInner';

/**
 * @export
 * @interface ConsentCacheStats
 */
export interface ConsentCacheStats {
    /**
     * Number of entries in cache
     * @type {number}
     * @memberof ConsentCacheStats
     */
    size: number;
    /**
     * @type {Array<ConsentCacheStatsEntriesInner>}
     * @memberof ConsentCacheStats
     */
    entries: Array<ConsentCacheStatsEntriesInner>;
}

/**
 * Check if a given object implements the ConsentCacheStats interface.
 */
export function instanceOfConsentCacheStats(value: object): value is ConsentCacheStats {
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function ConsentCacheStatsFromJSON(json: any): ConsentCacheStats {
    return ConsentCacheStatsFromJSONTyped(json, false);
}

export function ConsentCacheStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentCacheStats {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'],
        'entries': ((json['entries'] as Array<any>).map(ConsentCacheStatsEntriesInnerFromJSON)),
    };
}

export function ConsentCacheStatsToJSON(json: any): ConsentCacheStats {
    return ConsentCacheStatsToJSONTyped(json, false);
}

export function ConsentCacheStatsToJSONTyped(value?: ConsentCacheStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(ConsentCacheStatsEntriesInnerToJSON)),
    };
}
