/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdentityProviderConfig } from './IdentityProviderConfig';
import {
    IdentityProviderConfigFromJSON,
    IdentityProviderConfigFromJSONTyped,
    IdentityProviderConfigToJSON,
    IdentityProviderConfigToJSONTyped,
} from './IdentityProviderConfig';

/**
 * @export
 * @interface CreateIdentityProviderRequest
 */
export interface CreateIdentityProviderRequest {
    /**
     * Provider alias (unique identifier)
     * @type {string}
     * @memberof CreateIdentityProviderRequest
     */
    alias: string;
    /**
     * Provider type (oidc, saml, etc.)
     * @type {string}
     * @memberof CreateIdentityProviderRequest
     */
    providerId: string;
    /**
     * Display name for UI
     * @type {string}
     * @memberof CreateIdentityProviderRequest
     */
    displayName?: string;
    /**
     * Whether to enable the provider
     * @type {boolean}
     * @memberof CreateIdentityProviderRequest
     */
    enabled?: boolean;
    /**
     * @type {IdentityProviderConfig}
     * @memberof CreateIdentityProviderRequest
     */
    config: IdentityProviderConfig;
    /**
     * Authentication flow for first broker login (e.g. "first broker login")
     * @type {string}
     * @memberof CreateIdentityProviderRequest
     */
    firstBrokerLoginFlowAlias?: string;
    /**
     * Authentication flow to run after broker login
     * @type {string}
     * @memberof CreateIdentityProviderRequest
     */
    postBrokerLoginFlowAlias?: string;
    /**
     * Trust email provided by this identity provider for automatic account linking
     * @type {boolean}
     * @memberof CreateIdentityProviderRequest
     */
    trustEmail?: boolean;
    /**
     * If true, users cannot log in through this provider, only link existing accounts
     * @type {boolean}
     * @memberof CreateIdentityProviderRequest
     */
    linkOnly?: boolean;
    /**
     * Hide this provider from the login page
     * @type {boolean}
     * @memberof CreateIdentityProviderRequest
     */
    hideOnLogin?: boolean;
}

/**
 * Check if a given object implements the CreateIdentityProviderRequest interface.
 */
export function instanceOfCreateIdentityProviderRequest(value: object): value is CreateIdentityProviderRequest {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    return true;
}

export function CreateIdentityProviderRequestFromJSON(json: any): CreateIdentityProviderRequest {
    return CreateIdentityProviderRequestFromJSONTyped(json, false);
}

export function CreateIdentityProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIdentityProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'providerId': json['providerId'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'config': IdentityProviderConfigFromJSON(json['config']),
        'firstBrokerLoginFlowAlias': json['firstBrokerLoginFlowAlias'] == null ? undefined : json['firstBrokerLoginFlowAlias'],
        'postBrokerLoginFlowAlias': json['postBrokerLoginFlowAlias'] == null ? undefined : json['postBrokerLoginFlowAlias'],
        'trustEmail': json['trustEmail'] == null ? undefined : json['trustEmail'],
        'linkOnly': json['linkOnly'] == null ? undefined : json['linkOnly'],
        'hideOnLogin': json['hideOnLogin'] == null ? undefined : json['hideOnLogin'],
    };
}

export function CreateIdentityProviderRequestToJSON(json: any): CreateIdentityProviderRequest {
    return CreateIdentityProviderRequestToJSONTyped(json, false);
}

export function CreateIdentityProviderRequestToJSONTyped(value?: CreateIdentityProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'providerId': value['providerId'],
        'displayName': value['displayName'],
        'enabled': value['enabled'],
        'config': IdentityProviderConfigToJSON(value['config']),
        'firstBrokerLoginFlowAlias': value['firstBrokerLoginFlowAlias'],
        'postBrokerLoginFlowAlias': value['postBrokerLoginFlowAlias'],
        'trustEmail': value['trustEmail'],
        'linkOnly': value['linkOnly'],
        'hideOnLogin': value['hideOnLogin'],
    };
}
