/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LdapConfig } from './LdapConfig';
import {
    LdapConfigFromJSON,
    LdapConfigFromJSONTyped,
    LdapConfigToJSON,
    LdapConfigToJSONTyped,
} from './LdapConfig';

/**
 * @export
 * @interface CreateUserFederationRequest
 */
export interface CreateUserFederationRequest {
    /**
     * Display name for this federation provider
     * @type {string}
     * @memberof CreateUserFederationRequest
     */
    name: string;
    /**
     * @type {LdapConfig}
     * @memberof CreateUserFederationRequest
     */
    config: LdapConfig;
}

/**
 * Check if a given object implements the CreateUserFederationRequest interface.
 */
export function instanceOfCreateUserFederationRequest(value: object): value is CreateUserFederationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function CreateUserFederationRequestFromJSON(json: any): CreateUserFederationRequest {
    return CreateUserFederationRequestFromJSONTyped(json, false);
}

export function CreateUserFederationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserFederationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'config': LdapConfigFromJSON(json['config']),
    };
}

export function CreateUserFederationRequestToJSON(json: any): CreateUserFederationRequest {
    return CreateUserFederationRequestToJSONTyped(json, false);
}

export function CreateUserFederationRequestToJSONTyped(value?: CreateUserFederationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'config': LdapConfigToJSON(value['config']),
    };
}
