/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface CreateGroupRequest
 */
export interface CreateGroupRequest {
    /**
     * Group name
     * @type {string}
     * @memberof CreateGroupRequest
     */
    name: string;
    /**
     * Group description
     * @type {string}
     * @memberof CreateGroupRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateGroupRequest interface.
 */
export function instanceOfCreateGroupRequest(value: object): value is CreateGroupRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateGroupRequestFromJSON(json: any): CreateGroupRequest {
    return CreateGroupRequestFromJSONTyped(json, false);
}

export function CreateGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateGroupRequestToJSON(json: any): CreateGroupRequest {
    return CreateGroupRequestToJSONTyped(json, false);
}

export function CreateGroupRequestToJSONTyped(value?: CreateGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}
