/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationDomain } from './OrganizationDomain';
import {
    OrganizationDomainFromJSON,
    OrganizationDomainFromJSONTyped,
    OrganizationDomainToJSON,
    OrganizationDomainToJSONTyped,
} from './OrganizationDomain';

/**
 * @export
 * @interface CreateOrganizationRequest
 */
export interface CreateOrganizationRequest {
    /**
     * Organization display name (required, unique)
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    name: string;
    /**
     * URL-friendly alias (auto-derived from name if omitted)
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    alias?: string;
    /**
     * Free-text description
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    description?: string;
    /**
     * Post-registration redirect URL
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    redirectUrl?: string;
    /**
     * Enabled state (defaults to true)
     * @type {boolean}
     * @memberof CreateOrganizationRequest
     */
    enabled?: boolean;
    /**
     * @type {{ [key: string]: Array<string> }}
     * @memberof CreateOrganizationRequest
     */
    attributes?: { [key: string]: Array<string> };
    /**
     * @type {Array<OrganizationDomain>}
     * @memberof CreateOrganizationRequest
     */
    domains?: Array<OrganizationDomain>;
}

/**
 * Check if a given object implements the CreateOrganizationRequest interface.
 */
export function instanceOfCreateOrganizationRequest(value: object): value is CreateOrganizationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateOrganizationRequestFromJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestFromJSONTyped(json, false);
}

export function CreateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'description': json['description'] == null ? undefined : json['description'],
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'domains': json['domains'] == null ? undefined : ((json['domains'] as Array<any>).map(OrganizationDomainFromJSON)),
    };
}

export function CreateOrganizationRequestToJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestToJSONTyped(json, false);
}

export function CreateOrganizationRequestToJSONTyped(value?: CreateOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'alias': value['alias'],
        'description': value['description'],
        'redirectUrl': value['redirectUrl'],
        'enabled': value['enabled'],
        'attributes': value['attributes'],
        'domains': value['domains'] == null ? undefined : ((value['domains'] as Array<any>).map(OrganizationDomainToJSON)),
    };
}
