/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface ExportResponse
 */
export interface ExportResponse {
    /**
     * Export format (json, csv)
     * @type {string}
     * @memberof ExportResponse
     */
    format: string;
    /**
     * @type {any}
     * @memberof ExportResponse
     */
    data: any;
}

/**
 * Check if a given object implements the ExportResponse interface.
 */
export function instanceOfExportResponse(value: object): value is ExportResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function ExportResponseFromJSON(json: any): ExportResponse {
    return ExportResponseFromJSONTyped(json, false);
}

export function ExportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'format': json['format'],
        'data': json['data'],
    };
}

export function ExportResponseToJSON(json: any): ExportResponse {
    return ExportResponseToJSONTyped(json, false);
}

export function ExportResponseToJSONTyped(value?: ExportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': value['format'],
        'data': value['data'],
    };
}
