/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface FhirHealthCheck
 */
export interface FhirHealthCheck {
    /**
     * Unique check ID
     * @type {string}
     * @memberof FhirHealthCheck
     */
    id: string;
    /**
     * Check timestamp (ISO 8601)
     * @type {string}
     * @memberof FhirHealthCheck
     */
    timestamp: string;
    /**
     * FHIR server display name
     * @type {string}
     * @memberof FhirHealthCheck
     */
    serverName: string;
    /**
     * FHIR server base URL
     * @type {string}
     * @memberof FhirHealthCheck
     */
    serverUrl: string;
    /**
     * Health status
     * @type {FhirHealthCheckStatusEnum}
     * @memberof FhirHealthCheck
     */
    status: FhirHealthCheckStatusEnum;
    /**
     * Response time in milliseconds
     * @type {number}
     * @memberof FhirHealthCheck
     */
    responseTimeMs: number;
    /**
     * Detected FHIR version
     * @type {string}
     * @memberof FhirHealthCheck
     */
    fhirVersion?: string;
    /**
     * Error message if unhealthy
     * @type {string}
     * @memberof FhirHealthCheck
     */
    error?: string;
}

/**
 * @export
 */
export const FhirHealthCheckStatusEnum = {
    Healthy: 'healthy',
    Degraded: 'degraded',
    Unhealthy: 'unhealthy',
} as const;
export type FhirHealthCheckStatusEnum = typeof FhirHealthCheckStatusEnum[keyof typeof FhirHealthCheckStatusEnum];

/**
 * Check if a given object implements the FhirHealthCheck interface.
 */
export function instanceOfFhirHealthCheck(value: object): value is FhirHealthCheck {
    if (!('serverName' in value) || value['serverName'] === undefined) return false;
    if (!('serverUrl' in value) || value['serverUrl'] === undefined) return false;
    if (!('responseTimeMs' in value) || value['responseTimeMs'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function FhirHealthCheckFromJSON(json: any): FhirHealthCheck {
    return FhirHealthCheckFromJSONTyped(json, false);
}

export function FhirHealthCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): FhirHealthCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'serverName': json['serverName'],
        'serverUrl': json['serverUrl'],
        'status': json['status'],
        'responseTimeMs': json['responseTimeMs'],
        'fhirVersion': json['fhirVersion'] == null ? undefined : json['fhirVersion'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FhirHealthCheckToJSON(json: any): FhirHealthCheck {
    return FhirHealthCheckToJSONTyped(json, false);
}

export function FhirHealthCheckToJSONTyped(value?: FhirHealthCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'],
        'serverName': value['serverName'],
        'serverUrl': value['serverUrl'],
        'status': value['status'],
        'responseTimeMs': value['responseTimeMs'],
        'fhirVersion': value['fhirVersion'],
        'error': value['error'],
    };
}
