/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface FhirProxyEvent
 */
export interface FhirProxyEvent {
    /**
     * Unique event ID
     * @type {string}
     * @memberof FhirProxyEvent
     */
    id: string;
    /**
     * Event timestamp (ISO 8601)
     * @type {string}
     * @memberof FhirProxyEvent
     */
    timestamp: string;
    /**
     * Target FHIR server name
     * @type {string}
     * @memberof FhirProxyEvent
     */
    serverName: string;
    /**
     * HTTP method (GET, POST, etc.)
     * @type {string}
     * @memberof FhirProxyEvent
     */
    method: string;
    /**
     * FHIR resource path
     * @type {string}
     * @memberof FhirProxyEvent
     */
    resourcePath: string;
    /**
     * FHIR resource type
     * @type {string}
     * @memberof FhirProxyEvent
     */
    resourceType: string;
    /**
     * HTTP response status code
     * @type {number}
     * @memberof FhirProxyEvent
     */
    statusCode: number;
    /**
     * Response time in milliseconds
     * @type {number}
     * @memberof FhirProxyEvent
     */
    responseTimeMs: number;
    /**
     * OAuth client ID
     * @type {string}
     * @memberof FhirProxyEvent
     */
    clientId?: string;
    /**
     * Error description
     * @type {string}
     * @memberof FhirProxyEvent
     */
    error?: string;
}

/**
 * Check if a given object implements the FhirProxyEvent interface.
 */
export function instanceOfFhirProxyEvent(value: object): value is FhirProxyEvent {
    if (!('serverName' in value) || value['serverName'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('resourcePath' in value) || value['resourcePath'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('responseTimeMs' in value) || value['responseTimeMs'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    return true;
}

export function FhirProxyEventFromJSON(json: any): FhirProxyEvent {
    return FhirProxyEventFromJSONTyped(json, false);
}

export function FhirProxyEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): FhirProxyEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'serverName': json['serverName'],
        'method': json['method'],
        'resourcePath': json['resourcePath'],
        'resourceType': json['resourceType'],
        'statusCode': json['statusCode'],
        'responseTimeMs': json['responseTimeMs'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FhirProxyEventToJSON(json: any): FhirProxyEvent {
    return FhirProxyEventToJSONTyped(json, false);
}

export function FhirProxyEventToJSONTyped(value?: FhirProxyEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'],
        'serverName': value['serverName'],
        'method': value['method'],
        'resourcePath': value['resourcePath'],
        'resourceType': value['resourceType'],
        'statusCode': value['statusCode'],
        'responseTimeMs': value['responseTimeMs'],
        'clientId': value['clientId'],
        'error': value['error'],
    };
}
