/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FhirUptimeSummary } from './FhirUptimeSummary';
import {
    FhirUptimeSummaryFromJSON,
    FhirUptimeSummaryFromJSONTyped,
    FhirUptimeSummaryToJSON,
    FhirUptimeSummaryToJSONTyped,
} from './FhirUptimeSummary';

/**
 * @export
 * @interface FhirUptimeSummariesResponse
 */
export interface FhirUptimeSummariesResponse {
    /**
     * Per-server uptime summaries
     * @type {Array<FhirUptimeSummary>}
     * @memberof FhirUptimeSummariesResponse
     */
    servers: Array<FhirUptimeSummary>;
    /**
     * Response timestamp
     * @type {string}
     * @memberof FhirUptimeSummariesResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the FhirUptimeSummariesResponse interface.
 */
export function instanceOfFhirUptimeSummariesResponse(value: object): value is FhirUptimeSummariesResponse {
    if (!('servers' in value) || value['servers'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function FhirUptimeSummariesResponseFromJSON(json: any): FhirUptimeSummariesResponse {
    return FhirUptimeSummariesResponseFromJSONTyped(json, false);
}

export function FhirUptimeSummariesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FhirUptimeSummariesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'servers': ((json['servers'] as Array<any>).map(FhirUptimeSummaryFromJSON)),
        'timestamp': json['timestamp'],
    };
}

export function FhirUptimeSummariesResponseToJSON(json: any): FhirUptimeSummariesResponse {
    return FhirUptimeSummariesResponseToJSONTyped(json, false);
}

export function FhirUptimeSummariesResponseToJSONTyped(value?: FhirUptimeSummariesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'servers': value['servers'] == null ? undefined : ((value['servers'] as Array<any>).map(FhirUptimeSummaryToJSON)),
        'timestamp': value['timestamp'],
    };
}
