/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FhirHealthCheck } from './FhirHealthCheck';
import {
    FhirHealthCheckFromJSON,
    FhirHealthCheckFromJSONTyped,
    FhirHealthCheckToJSON,
    FhirHealthCheckToJSONTyped,
} from './FhirHealthCheck';

/**
 * @export
 * @interface FhirHealthChecksResponse
 */
export interface FhirHealthChecksResponse {
    /**
     * Health check history
     * @type {Array<FhirHealthCheck>}
     * @memberof FhirHealthChecksResponse
     */
    checks: Array<FhirHealthCheck>;
    /**
     * Total checks returned
     * @type {number}
     * @memberof FhirHealthChecksResponse
     */
    total: number;
    /**
     * Response timestamp
     * @type {string}
     * @memberof FhirHealthChecksResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the FhirHealthChecksResponse interface.
 */
export function instanceOfFhirHealthChecksResponse(value: object): value is FhirHealthChecksResponse {
    if (!('checks' in value) || value['checks'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function FhirHealthChecksResponseFromJSON(json: any): FhirHealthChecksResponse {
    return FhirHealthChecksResponseFromJSONTyped(json, false);
}

export function FhirHealthChecksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FhirHealthChecksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'checks': ((json['checks'] as Array<any>).map(FhirHealthCheckFromJSON)),
        'total': json['total'],
        'timestamp': json['timestamp'],
    };
}

export function FhirHealthChecksResponseToJSON(json: any): FhirHealthChecksResponse {
    return FhirHealthChecksResponseToJSONTyped(json, false);
}

export function FhirHealthChecksResponseToJSONTyped(value?: FhirHealthChecksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checks': value['checks'] == null ? undefined : ((value['checks'] as Array<any>).map(FhirHealthCheckToJSON)),
        'total': value['total'],
        'timestamp': value['timestamp'],
    };
}
