/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FhirHealthCheck } from './FhirHealthCheck';
import {
    FhirHealthCheckFromJSON,
    FhirHealthCheckFromJSONTyped,
    FhirHealthCheckToJSON,
    FhirHealthCheckToJSONTyped,
} from './FhirHealthCheck';

/**
 * @export
 * @interface FhirUptimeSummary
 */
export interface FhirUptimeSummary {
    /**
     * FHIR server display name
     * @type {string}
     * @memberof FhirUptimeSummary
     */
    serverName: string;
    /**
     * FHIR server base URL
     * @type {string}
     * @memberof FhirUptimeSummary
     */
    serverUrl: string;
    /**
     * @type {FhirUptimeSummaryCurrentStatusEnum}
     * @memberof FhirUptimeSummary
     */
    currentStatus: FhirUptimeSummaryCurrentStatusEnum;
    /**
     * Uptime percentage over observation period
     * @type {number}
     * @memberof FhirUptimeSummary
     */
    uptimePercent: number;
    /**
     * Average response time in ms
     * @type {number}
     * @memberof FhirUptimeSummary
     */
    avgResponseTimeMs: number;
    /**
     * Total number of checks
     * @type {number}
     * @memberof FhirUptimeSummary
     */
    checksTotal: number;
    /**
     * Number of healthy checks
     * @type {number}
     * @memberof FhirUptimeSummary
     */
    checksHealthy: number;
    /**
     * Timestamp of last check (ISO 8601)
     * @type {string}
     * @memberof FhirUptimeSummary
     */
    lastChecked: string;
    /**
     * Most recent error message
     * @type {string}
     * @memberof FhirUptimeSummary
     */
    lastError?: string;
    /**
     * Recent health check results
     * @type {Array<FhirHealthCheck>}
     * @memberof FhirUptimeSummary
     */
    recentChecks: Array<FhirHealthCheck>;
}

/**
 * @export
 */
export const FhirUptimeSummaryCurrentStatusEnum = {
    Healthy: 'healthy',
    Degraded: 'degraded',
    Unhealthy: 'unhealthy',
} as const;
export type FhirUptimeSummaryCurrentStatusEnum = typeof FhirUptimeSummaryCurrentStatusEnum[keyof typeof FhirUptimeSummaryCurrentStatusEnum];

/**
 * Check if a given object implements the FhirUptimeSummary interface.
 */
export function instanceOfFhirUptimeSummary(value: object): value is FhirUptimeSummary {
    if (!('recentChecks' in value) || value['recentChecks'] === undefined) return false;
    if (!('checksHealthy' in value) || value['checksHealthy'] === undefined) return false;
    if (!('uptimePercent' in value) || value['uptimePercent'] === undefined) return false;
    if (!('checksTotal' in value) || value['checksTotal'] === undefined) return false;
    if (!('serverName' in value) || value['serverName'] === undefined) return false;
    if (!('avgResponseTimeMs' in value) || value['avgResponseTimeMs'] === undefined) return false;
    if (!('serverUrl' in value) || value['serverUrl'] === undefined) return false;
    if (!('lastChecked' in value) || value['lastChecked'] === undefined) return false;
    if (!('currentStatus' in value) || value['currentStatus'] === undefined) return false;
    return true;
}

export function FhirUptimeSummaryFromJSON(json: any): FhirUptimeSummary {
    return FhirUptimeSummaryFromJSONTyped(json, false);
}

export function FhirUptimeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FhirUptimeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'serverName': json['serverName'],
        'serverUrl': json['serverUrl'],
        'currentStatus': json['currentStatus'],
        'uptimePercent': json['uptimePercent'],
        'avgResponseTimeMs': json['avgResponseTimeMs'],
        'checksTotal': json['checksTotal'],
        'checksHealthy': json['checksHealthy'],
        'lastChecked': json['lastChecked'],
        'lastError': json['lastError'] == null ? undefined : json['lastError'],
        'recentChecks': ((json['recentChecks'] as Array<any>).map(FhirHealthCheckFromJSON)),
    };
}

export function FhirUptimeSummaryToJSON(json: any): FhirUptimeSummary {
    return FhirUptimeSummaryToJSONTyped(json, false);
}

export function FhirUptimeSummaryToJSONTyped(value?: FhirUptimeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverName': value['serverName'],
        'serverUrl': value['serverUrl'],
        'currentStatus': value['currentStatus'],
        'uptimePercent': value['uptimePercent'],
        'avgResponseTimeMs': value['avgResponseTimeMs'],
        'checksTotal': value['checksTotal'],
        'checksHealthy': value['checksHealthy'],
        'lastChecked': value['lastChecked'],
        'lastError': value['lastError'],
        'recentChecks': value['recentChecks'] == null ? undefined : ((value['recentChecks'] as Array<any>).map(FhirHealthCheckToJSON)),
    };
}
