/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface FhirProxyHourlyStat
 */
export interface FhirProxyHourlyStat {
    /**
     * Hour bucket (ISO 8601)
     * @type {string}
     * @memberof FhirProxyHourlyStat
     */
    hour: string;
    /**
     * @type {number}
     * @memberof FhirProxyHourlyStat
     */
    total: number;
    /**
     * @type {number}
     * @memberof FhirProxyHourlyStat
     */
    success: number;
    /**
     * @type {number}
     * @memberof FhirProxyHourlyStat
     */
    errors: number;
    /**
     * @type {number}
     * @memberof FhirProxyHourlyStat
     */
    rateLimited: number;
    /**
     * @type {number}
     * @memberof FhirProxyHourlyStat
     */
    avgMs: number;
}

/**
 * Check if a given object implements the FhirProxyHourlyStat interface.
 */
export function instanceOfFhirProxyHourlyStat(value: object): value is FhirProxyHourlyStat {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('avgMs' in value) || value['avgMs'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('rateLimited' in value) || value['rateLimited'] === undefined) return false;
    if (!('hour' in value) || value['hour'] === undefined) return false;
    return true;
}

export function FhirProxyHourlyStatFromJSON(json: any): FhirProxyHourlyStat {
    return FhirProxyHourlyStatFromJSONTyped(json, false);
}

export function FhirProxyHourlyStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): FhirProxyHourlyStat {
    if (json == null) {
        return json;
    }
    return {
        
        'hour': json['hour'],
        'total': json['total'],
        'success': json['success'],
        'errors': json['errors'],
        'rateLimited': json['rateLimited'],
        'avgMs': json['avgMs'],
    };
}

export function FhirProxyHourlyStatToJSON(json: any): FhirProxyHourlyStat {
    return FhirProxyHourlyStatToJSONTyped(json, false);
}

export function FhirProxyHourlyStatToJSONTyped(value?: FhirProxyHourlyStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hour': value['hour'],
        'total': value['total'],
        'success': value['success'],
        'errors': value['errors'],
        'rateLimited': value['rateLimited'],
        'avgMs': value['avgMs'],
    };
}
