/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IalConfig } from './IalConfig';
import {
    IalConfigFromJSON,
    IalConfigFromJSONTyped,
    IalConfigToJSON,
    IalConfigToJSONTyped,
} from './IalConfig';

/**
 * @export
 * @interface GetAdminConsentIal200Response
 */
export interface GetAdminConsentIal200Response {
    /**
     * @type {string}
     * @memberof GetAdminConsentIal200Response
     */
    message: string;
    /**
     * @type {IalConfig}
     * @memberof GetAdminConsentIal200Response
     */
    config: IalConfig;
    /**
     * @type {string}
     * @memberof GetAdminConsentIal200Response
     */
    timestamp: string;
}

/**
 * Check if a given object implements the GetAdminConsentIal200Response interface.
 */
export function instanceOfGetAdminConsentIal200Response(value: object): value is GetAdminConsentIal200Response {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetAdminConsentIal200ResponseFromJSON(json: any): GetAdminConsentIal200Response {
    return GetAdminConsentIal200ResponseFromJSONTyped(json, false);
}

export function GetAdminConsentIal200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminConsentIal200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'config': IalConfigFromJSON(json['config']),
        'timestamp': json['timestamp'],
    };
}

export function GetAdminConsentIal200ResponseToJSON(json: any): GetAdminConsentIal200Response {
    return GetAdminConsentIal200ResponseToJSONTyped(json, false);
}

export function GetAdminConsentIal200ResponseToJSONTyped(value?: GetAdminConsentIal200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'config': IalConfigToJSON(value['config']),
        'timestamp': value['timestamp'],
    };
}
