/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface GetAdminMcpServersByNameTools200ResponseToolsInner
 */
export interface GetAdminMcpServersByNameTools200ResponseToolsInner {
    /**
     * Tool name
     * @type {string}
     * @memberof GetAdminMcpServersByNameTools200ResponseToolsInner
     */
    name: string;
    /**
     * Tool description
     * @type {string}
     * @memberof GetAdminMcpServersByNameTools200ResponseToolsInner
     */
    description: string;
    /**
     * Tool parameters schema
     * @type {{ [key: string]: any }}
     * @memberof GetAdminMcpServersByNameTools200ResponseToolsInner
     */
    parameters: { [key: string]: any };
}

/**
 * Check if a given object implements the GetAdminMcpServersByNameTools200ResponseToolsInner interface.
 */
export function instanceOfGetAdminMcpServersByNameTools200ResponseToolsInner(value: object): value is GetAdminMcpServersByNameTools200ResponseToolsInner {
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GetAdminMcpServersByNameTools200ResponseToolsInnerFromJSON(json: any): GetAdminMcpServersByNameTools200ResponseToolsInner {
    return GetAdminMcpServersByNameTools200ResponseToolsInnerFromJSONTyped(json, false);
}

export function GetAdminMcpServersByNameTools200ResponseToolsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminMcpServersByNameTools200ResponseToolsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'parameters': json['parameters'],
    };
}

export function GetAdminMcpServersByNameTools200ResponseToolsInnerToJSON(json: any): GetAdminMcpServersByNameTools200ResponseToolsInner {
    return GetAdminMcpServersByNameTools200ResponseToolsInnerToJSONTyped(json, false);
}

export function GetAdminMcpServersByNameTools200ResponseToolsInnerToJSONTyped(value?: GetAdminMcpServersByNameTools200ResponseToolsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
    };
}
