/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAdminAiToolsSkills200ResponseSkillsInner } from './GetAdminAiToolsSkills200ResponseSkillsInner';
import {
    GetAdminAiToolsSkills200ResponseSkillsInnerFromJSON,
    GetAdminAiToolsSkills200ResponseSkillsInnerFromJSONTyped,
    GetAdminAiToolsSkills200ResponseSkillsInnerToJSON,
    GetAdminAiToolsSkills200ResponseSkillsInnerToJSONTyped,
} from './GetAdminAiToolsSkills200ResponseSkillsInner';

/**
 * @export
 * @interface GetAdminAiToolsSkills200Response
 */
export interface GetAdminAiToolsSkills200Response {
    /**
     * List of installed skills
     * @type {Array<GetAdminAiToolsSkills200ResponseSkillsInner>}
     * @memberof GetAdminAiToolsSkills200Response
     */
    skills: Array<GetAdminAiToolsSkills200ResponseSkillsInner>;
    /**
     * Total number of skills
     * @type {number}
     * @memberof GetAdminAiToolsSkills200Response
     */
    totalSkills: number;
}

/**
 * Check if a given object implements the GetAdminAiToolsSkills200Response interface.
 */
export function instanceOfGetAdminAiToolsSkills200Response(value: object): value is GetAdminAiToolsSkills200Response {
    if (!('totalSkills' in value) || value['totalSkills'] === undefined) return false;
    if (!('skills' in value) || value['skills'] === undefined) return false;
    return true;
}

export function GetAdminAiToolsSkills200ResponseFromJSON(json: any): GetAdminAiToolsSkills200Response {
    return GetAdminAiToolsSkills200ResponseFromJSONTyped(json, false);
}

export function GetAdminAiToolsSkills200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminAiToolsSkills200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'skills': ((json['skills'] as Array<any>).map(GetAdminAiToolsSkills200ResponseSkillsInnerFromJSON)),
        'totalSkills': json['totalSkills'],
    };
}

export function GetAdminAiToolsSkills200ResponseToJSON(json: any): GetAdminAiToolsSkills200Response {
    return GetAdminAiToolsSkills200ResponseToJSONTyped(json, false);
}

export function GetAdminAiToolsSkills200ResponseToJSONTyped(value?: GetAdminAiToolsSkills200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(GetAdminAiToolsSkills200ResponseSkillsInnerToJSON)),
        'totalSkills': value['totalSkills'],
    };
}
