/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface GetAdminMcpServersTemplates200Response
 */
export interface GetAdminMcpServersTemplates200Response {
    /**
     * @type {Array<any>}
     * @memberof GetAdminMcpServersTemplates200Response
     */
    templates: Array<any>;
    /**
     * @type {{ [key: string]: any }}
     * @memberof GetAdminMcpServersTemplates200Response
     */
    categories: { [key: string]: any };
    /**
     * @type {string}
     * @memberof GetAdminMcpServersTemplates200Response
     */
    version: string;
}

/**
 * Check if a given object implements the GetAdminMcpServersTemplates200Response interface.
 */
export function instanceOfGetAdminMcpServersTemplates200Response(value: object): value is GetAdminMcpServersTemplates200Response {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('templates' in value) || value['templates'] === undefined) return false;
    return true;
}

export function GetAdminMcpServersTemplates200ResponseFromJSON(json: any): GetAdminMcpServersTemplates200Response {
    return GetAdminMcpServersTemplates200ResponseFromJSONTyped(json, false);
}

export function GetAdminMcpServersTemplates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminMcpServersTemplates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': json['templates'],
        'categories': json['categories'],
        'version': json['version'],
    };
}

export function GetAdminMcpServersTemplates200ResponseToJSON(json: any): GetAdminMcpServersTemplates200Response {
    return GetAdminMcpServersTemplates200ResponseToJSONTyped(json, false);
}

export function GetAdminMcpServersTemplates200ResponseToJSONTyped(value?: GetAdminMcpServersTemplates200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': value['templates'],
        'categories': value['categories'],
        'version': value['version'],
    };
}
