/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
 */
export interface GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner {
    /**
     * Skill ID (owner/repo/name)
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    id: string;
    /**
     * Skill name
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    name: string;
    /**
     * Skill description
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    description: string;
    /**
     * GitHub owner
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    owner: string;
    /**
     * GitHub repository
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    repo: string;
    /**
     * Weekly install count
     * @type {number}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    installs: number;
    /**
     * GitHub URL
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    githubUrl: string;
    /**
     * skills.sh URL
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    skillsshUrl: string;
    /**
     * Whether already installed locally
     * @type {boolean}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    installed: boolean;
    /**
     * Whether compatible with HTTP-only agent runtime
     * @type {boolean}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    compatible: boolean;
    /**
     * Why the skill is incompatible
     * @type {string}
     * @memberof GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner
     */
    incompatibleReason?: string;
}

/**
 * Check if a given object implements the GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner interface.
 */
export function instanceOfGetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner(value: object): value is GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('githubUrl' in value) || value['githubUrl'] === undefined) return false;
    if (!('installs' in value) || value['installs'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('skillsshUrl' in value) || value['skillsshUrl'] === undefined) return false;
    if (!('installed' in value) || value['installed'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('compatible' in value) || value['compatible'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('repo' in value) || value['repo'] === undefined) return false;
    return true;
}

export function GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInnerFromJSON(json: any): GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner {
    return GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInnerFromJSONTyped(json, false);
}

export function GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'owner': json['owner'],
        'repo': json['repo'],
        'installs': json['installs'],
        'githubUrl': json['githubUrl'],
        'skillsshUrl': json['skillsshUrl'],
        'installed': json['installed'],
        'compatible': json['compatible'],
        'incompatibleReason': json['incompatibleReason'] == null ? undefined : json['incompatibleReason'],
    };
}

export function GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInnerToJSON(json: any): GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner {
    return GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInnerToJSONTyped(json, false);
}

export function GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInnerToJSONTyped(value?: GetAdminAiToolsSkillsRegistryBrowse200ResponseSkillsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'owner': value['owner'],
        'repo': value['repo'],
        'installs': value['installs'],
        'githubUrl': value['githubUrl'],
        'skillsshUrl': value['skillsshUrl'],
        'installed': value['installed'],
        'compatible': value['compatible'],
        'incompatibleReason': value['incompatibleReason'],
    };
}
