/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface GetAdminMcpServersRegistrySearch200ResponseServersInner
 */
export interface GetAdminMcpServersRegistrySearch200ResponseServersInner {
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    name: string;
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    title?: string;
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    description: string;
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    version: string;
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    url: string;
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    transport: string;
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    websiteUrl?: string;
    /**
     * @type {string}
     * @memberof GetAdminMcpServersRegistrySearch200ResponseServersInner
     */
    publishedAt?: string;
}

/**
 * Check if a given object implements the GetAdminMcpServersRegistrySearch200ResponseServersInner interface.
 */
export function instanceOfGetAdminMcpServersRegistrySearch200ResponseServersInner(value: object): value is GetAdminMcpServersRegistrySearch200ResponseServersInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('transport' in value) || value['transport'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GetAdminMcpServersRegistrySearch200ResponseServersInnerFromJSON(json: any): GetAdminMcpServersRegistrySearch200ResponseServersInner {
    return GetAdminMcpServersRegistrySearch200ResponseServersInnerFromJSONTyped(json, false);
}

export function GetAdminMcpServersRegistrySearch200ResponseServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminMcpServersRegistrySearch200ResponseServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'],
        'version': json['version'],
        'url': json['url'],
        'transport': json['transport'],
        'websiteUrl': json['websiteUrl'] == null ? undefined : json['websiteUrl'],
        'publishedAt': json['publishedAt'] == null ? undefined : json['publishedAt'],
    };
}

export function GetAdminMcpServersRegistrySearch200ResponseServersInnerToJSON(json: any): GetAdminMcpServersRegistrySearch200ResponseServersInner {
    return GetAdminMcpServersRegistrySearch200ResponseServersInnerToJSONTyped(json, false);
}

export function GetAdminMcpServersRegistrySearch200ResponseServersInnerToJSONTyped(value?: GetAdminMcpServersRegistrySearch200ResponseServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'version': value['version'],
        'url': value['url'],
        'transport': value['transport'],
        'websiteUrl': value['websiteUrl'],
        'publishedAt': value['publishedAt'],
    };
}
