/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface GetAdminMcpServersByNameHealth200Response
 */
export interface GetAdminMcpServersByNameHealth200Response {
    /**
     * Server name
     * @type {string}
     * @memberof GetAdminMcpServersByNameHealth200Response
     */
    name: string;
    /**
     * @type {GetAdminMcpServersByNameHealth200ResponseStatusEnum}
     * @memberof GetAdminMcpServersByNameHealth200Response
     */
    status: GetAdminMcpServersByNameHealth200ResponseStatusEnum;
    /**
     * Response time in milliseconds
     * @type {number}
     * @memberof GetAdminMcpServersByNameHealth200Response
     */
    responseTime?: number;
    /**
     * Number of available tools
     * @type {number}
     * @memberof GetAdminMcpServersByNameHealth200Response
     */
    toolCount?: number;
    /**
     * Error message if unhealthy
     * @type {string}
     * @memberof GetAdminMcpServersByNameHealth200Response
     */
    error?: string;
}

/**
 * @export
 */
export const GetAdminMcpServersByNameHealth200ResponseStatusEnum = {
    Healthy: 'healthy',
    Unhealthy: 'unhealthy',
    Unreachable: 'unreachable',
} as const;
export type GetAdminMcpServersByNameHealth200ResponseStatusEnum = typeof GetAdminMcpServersByNameHealth200ResponseStatusEnum[keyof typeof GetAdminMcpServersByNameHealth200ResponseStatusEnum];

/**
 * Check if a given object implements the GetAdminMcpServersByNameHealth200Response interface.
 */
export function instanceOfGetAdminMcpServersByNameHealth200Response(value: object): value is GetAdminMcpServersByNameHealth200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GetAdminMcpServersByNameHealth200ResponseFromJSON(json: any): GetAdminMcpServersByNameHealth200Response {
    return GetAdminMcpServersByNameHealth200ResponseFromJSONTyped(json, false);
}

export function GetAdminMcpServersByNameHealth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminMcpServersByNameHealth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': json['status'],
        'responseTime': json['responseTime'] == null ? undefined : json['responseTime'],
        'toolCount': json['toolCount'] == null ? undefined : json['toolCount'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetAdminMcpServersByNameHealth200ResponseToJSON(json: any): GetAdminMcpServersByNameHealth200Response {
    return GetAdminMcpServersByNameHealth200ResponseToJSONTyped(json, false);
}

export function GetAdminMcpServersByNameHealth200ResponseToJSONTyped(value?: GetAdminMcpServersByNameHealth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'status': value['status'],
        'responseTime': value['responseTime'],
        'toolCount': value['toolCount'],
        'error': value['error'],
    };
}
