/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAdminMcpServersRegistrySearch200ResponseServersInner } from './GetAdminMcpServersRegistrySearch200ResponseServersInner';
import {
    GetAdminMcpServersRegistrySearch200ResponseServersInnerFromJSON,
    GetAdminMcpServersRegistrySearch200ResponseServersInnerFromJSONTyped,
    GetAdminMcpServersRegistrySearch200ResponseServersInnerToJSON,
    GetAdminMcpServersRegistrySearch200ResponseServersInnerToJSONTyped,
} from './GetAdminMcpServersRegistrySearch200ResponseServersInner';

/**
 * @export
 * @interface GetAdminMcpServersRegistrySearch200Response
 */
export interface GetAdminMcpServersRegistrySearch200Response {
    /**
     * @type {Array<GetAdminMcpServersRegistrySearch200ResponseServersInner>}
     * @memberof GetAdminMcpServersRegistrySearch200Response
     */
    servers: Array<GetAdminMcpServersRegistrySearch200ResponseServersInner>;
    /**
     * @type {number}
     * @memberof GetAdminMcpServersRegistrySearch200Response
     */
    total: number;
    /**
     * @type {boolean}
     * @memberof GetAdminMcpServersRegistrySearch200Response
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the GetAdminMcpServersRegistrySearch200Response interface.
 */
export function instanceOfGetAdminMcpServersRegistrySearch200Response(value: object): value is GetAdminMcpServersRegistrySearch200Response {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('servers' in value) || value['servers'] === undefined) return false;
    return true;
}

export function GetAdminMcpServersRegistrySearch200ResponseFromJSON(json: any): GetAdminMcpServersRegistrySearch200Response {
    return GetAdminMcpServersRegistrySearch200ResponseFromJSONTyped(json, false);
}

export function GetAdminMcpServersRegistrySearch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminMcpServersRegistrySearch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'servers': ((json['servers'] as Array<any>).map(GetAdminMcpServersRegistrySearch200ResponseServersInnerFromJSON)),
        'total': json['total'],
        'hasMore': json['hasMore'],
    };
}

export function GetAdminMcpServersRegistrySearch200ResponseToJSON(json: any): GetAdminMcpServersRegistrySearch200Response {
    return GetAdminMcpServersRegistrySearch200ResponseToJSONTyped(json, false);
}

export function GetAdminMcpServersRegistrySearch200ResponseToJSONTyped(value?: GetAdminMcpServersRegistrySearch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'servers': value['servers'] == null ? undefined : ((value['servers'] as Array<any>).map(GetAdminMcpServersRegistrySearch200ResponseServersInnerToJSON)),
        'total': value['total'],
        'hasMore': value['hasMore'],
    };
}
