/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FhirPersonAssociation } from './FhirPersonAssociation';
import {
    FhirPersonAssociationFromJSON,
    FhirPersonAssociationFromJSONTyped,
    FhirPersonAssociationToJSON,
    FhirPersonAssociationToJSONTyped,
} from './FhirPersonAssociation';

/**
 * @export
 * @interface HealthcareUser
 */
export interface HealthcareUser {
    /**
     * User ID
     * @type {string}
     * @memberof HealthcareUser
     */
    id: string;
    /**
     * Username
     * @type {string}
     * @memberof HealthcareUser
     */
    username: string;
    /**
     * Email address
     * @type {string}
     * @memberof HealthcareUser
     */
    email: string;
    /**
     * First name
     * @type {string}
     * @memberof HealthcareUser
     */
    firstName: string;
    /**
     * Last name
     * @type {string}
     * @memberof HealthcareUser
     */
    lastName: string;
    /**
     * Whether the user is enabled
     * @type {boolean}
     * @memberof HealthcareUser
     */
    enabled: boolean;
    /**
     * @type {{ [key: string]: string | Array<string> }}
     * @memberof HealthcareUser
     */
    attributes?: { [key: string]: string | Array<string> };
    /**
     * Creation timestamp (Unix milliseconds)
     * @type {number}
     * @memberof HealthcareUser
     */
    createdTimestamp?: number;
    /**
     * Last login timestamp
     * @type {number | null}
     * @memberof HealthcareUser
     */
    lastLogin?: number | null;
    /**
     * Realm-level roles
     * @type {Array<string>}
     * @memberof HealthcareUser
     */
    realmRoles?: Array<string>;
    /**
     * @type {{ [key: string]: Array<string> }}
     * @memberof HealthcareUser
     */
    clientRoles?: { [key: string]: Array<string> };
    /**
     * Organization identifier
     * @type {string}
     * @memberof HealthcareUser
     */
    organization?: string;
    /**
     * FHIR Person associations across different servers
     * @type {Array<FhirPersonAssociation>}
     * @memberof HealthcareUser
     */
    fhirPersons?: Array<FhirPersonAssociation>;
    /**
     * Whether the email is verified
     * @type {boolean}
     * @memberof HealthcareUser
     */
    emailVerified?: boolean;
    /**
     * FHIR User identity reference (e.g. Patient/123 or Practitioner/456)
     * @type {string}
     * @memberof HealthcareUser
     */
    fhirUser?: string;
}

/**
 * Check if a given object implements the HealthcareUser interface.
 */
export function instanceOfHealthcareUser(value: object): value is HealthcareUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function HealthcareUserFromJSON(json: any): HealthcareUser {
    return HealthcareUserFromJSONTyped(json, false);
}

export function HealthcareUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthcareUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'enabled': json['enabled'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'createdTimestamp': json['createdTimestamp'] == null ? undefined : json['createdTimestamp'],
        'lastLogin': json['lastLogin'] == null ? undefined : json['lastLogin'],
        'realmRoles': json['realmRoles'] == null ? undefined : json['realmRoles'],
        'clientRoles': json['clientRoles'] == null ? undefined : json['clientRoles'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'fhirPersons': json['fhirPersons'] == null ? undefined : ((json['fhirPersons'] as Array<any>).map(FhirPersonAssociationFromJSON)),
        'emailVerified': json['emailVerified'] == null ? undefined : json['emailVerified'],
        'fhirUser': json['fhirUser'] == null ? undefined : json['fhirUser'],
    };
}

export function HealthcareUserToJSON(json: any): HealthcareUser {
    return HealthcareUserToJSONTyped(json, false);
}

export function HealthcareUserToJSONTyped(value?: HealthcareUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'enabled': value['enabled'],
        'attributes': value['attributes'],
        'createdTimestamp': value['createdTimestamp'],
        'lastLogin': value['lastLogin'],
        'realmRoles': value['realmRoles'],
        'clientRoles': value['clientRoles'],
        'organization': value['organization'],
        'fhirPersons': value['fhirPersons'] == null ? undefined : ((value['fhirPersons'] as Array<any>).map(FhirPersonAssociationToJSON)),
        'emailVerified': value['emailVerified'],
        'fhirUser': value['fhirUser'],
    };
}
