/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface KeycloakConfigResponse
 */
export interface KeycloakConfigResponse {
    /**
     * Keycloak base URL
     * @type {string | null}
     * @memberof KeycloakConfigResponse
     */
    baseUrl: string | null;
    /**
     * Keycloak realm name
     * @type {string | null}
     * @memberof KeycloakConfigResponse
     */
    realm: string | null;
    /**
     * Whether admin client credentials are configured
     * @type {boolean}
     * @memberof KeycloakConfigResponse
     */
    hasAdminClient: boolean;
    /**
     * Admin client ID (if configured)
     * @type {string | null}
     * @memberof KeycloakConfigResponse
     */
    adminClientId: string | null;
}

/**
 * Check if a given object implements the KeycloakConfigResponse interface.
 */
export function instanceOfKeycloakConfigResponse(value: object): value is KeycloakConfigResponse {
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    if (!('hasAdminClient' in value) || value['hasAdminClient'] === undefined) return false;
    if (!('realm' in value) || value['realm'] === undefined) return false;
    if (!('adminClientId' in value) || value['adminClientId'] === undefined) return false;
    return true;
}

export function KeycloakConfigResponseFromJSON(json: any): KeycloakConfigResponse {
    return KeycloakConfigResponseFromJSONTyped(json, false);
}

export function KeycloakConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeycloakConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'baseUrl': json['baseUrl'],
        'realm': json['realm'],
        'hasAdminClient': json['hasAdminClient'],
        'adminClientId': json['adminClientId'],
    };
}

export function KeycloakConfigResponseToJSON(json: any): KeycloakConfigResponse {
    return KeycloakConfigResponseToJSONTyped(json, false);
}

export function KeycloakConfigResponseToJSONTyped(value?: KeycloakConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseUrl': value['baseUrl'],
        'realm': value['realm'],
        'hasAdminClient': value['hasAdminClient'],
        'adminClientId': value['adminClientId'],
    };
}
