/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface MtlsConfigHasCertificates
 */
export interface MtlsConfigHasCertificates {
    /**
     * Whether client certificate is uploaded
     * @type {boolean}
     * @memberof MtlsConfigHasCertificates
     */
    clientCert: boolean;
    /**
     * Whether client private key is uploaded
     * @type {boolean}
     * @memberof MtlsConfigHasCertificates
     */
    clientKey: boolean;
    /**
     * Whether CA certificate is uploaded
     * @type {boolean}
     * @memberof MtlsConfigHasCertificates
     */
    caCert: boolean;
}

/**
 * Check if a given object implements the MtlsConfigHasCertificates interface.
 */
export function instanceOfMtlsConfigHasCertificates(value: object): value is MtlsConfigHasCertificates {
    if (!('caCert' in value) || value['caCert'] === undefined) return false;
    if (!('clientKey' in value) || value['clientKey'] === undefined) return false;
    if (!('clientCert' in value) || value['clientCert'] === undefined) return false;
    return true;
}

export function MtlsConfigHasCertificatesFromJSON(json: any): MtlsConfigHasCertificates {
    return MtlsConfigHasCertificatesFromJSONTyped(json, false);
}

export function MtlsConfigHasCertificatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MtlsConfigHasCertificates {
    if (json == null) {
        return json;
    }
    return {
        
        'clientCert': json['clientCert'],
        'clientKey': json['clientKey'],
        'caCert': json['caCert'],
    };
}

export function MtlsConfigHasCertificatesToJSON(json: any): MtlsConfigHasCertificates {
    return MtlsConfigHasCertificatesToJSONTyped(json, false);
}

export function MtlsConfigHasCertificatesToJSONTyped(value?: MtlsConfigHasCertificates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientCert': value['clientCert'],
        'clientKey': value['clientKey'],
        'caCert': value['caCert'],
    };
}
