/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationDomain } from './OrganizationDomain';
import {
    OrganizationDomainFromJSON,
    OrganizationDomainFromJSONTyped,
    OrganizationDomainToJSON,
    OrganizationDomainToJSONTyped,
} from './OrganizationDomain';

/**
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * Keycloak organization ID (UUID)
     * @type {string}
     * @memberof Organization
     */
    id?: string;
    /**
     * Organization display name (unique within realm)
     * @type {string}
     * @memberof Organization
     */
    name?: string;
    /**
     * URL-friendly alias (immutable after creation)
     * @type {string}
     * @memberof Organization
     */
    alias?: string;
    /**
     * Free-text description
     * @type {string}
     * @memberof Organization
     */
    description?: string;
    /**
     * Redirect URL after registration/invitation
     * @type {string}
     * @memberof Organization
     */
    redirectUrl?: string;
    /**
     * Whether the organization is enabled
     * @type {boolean}
     * @memberof Organization
     */
    enabled?: boolean;
    /**
     * Arbitrary key→value[] metadata (includes fhir_organization_id for sync)
     * @type {{ [key: string]: Array<string> }}
     * @memberof Organization
     */
    attributes?: { [key: string]: Array<string> };
    /**
     * Email domains owned by this organization
     * @type {Array<OrganizationDomain>}
     * @memberof Organization
     */
    domains?: Array<OrganizationDomain>;
}

/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): value is Organization {
    return true;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'description': json['description'] == null ? undefined : json['description'],
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'domains': json['domains'] == null ? undefined : ((json['domains'] as Array<any>).map(OrganizationDomainFromJSON)),
    };
}

export function OrganizationToJSON(json: any): Organization {
    return OrganizationToJSONTyped(json, false);
}

export function OrganizationToJSONTyped(value?: Organization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'alias': value['alias'],
        'description': value['description'],
        'redirectUrl': value['redirectUrl'],
        'enabled': value['enabled'],
        'attributes': value['attributes'],
        'domains': value['domains'] == null ? undefined : ((value['domains'] as Array<any>).map(OrganizationDomainToJSON)),
    };
}
