/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface OrgBrandConfig
 */
export interface OrgBrandConfig {
    /**
     * Brand display name
     * @type {string}
     * @memberof OrgBrandConfig
     */
    name?: string;
    /**
     * Brand website URL
     * @type {string}
     * @memberof OrgBrandConfig
     */
    website?: string;
    /**
     * Brand logo URL (SVG or 1024px PNG, transparent background)
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    logoUrl?: string | null;
    /**
     * Logo license URL
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    logoLicenseUrl?: string | null;
    /**
     * Alternative brand names
     * @type {Array<string>}
     * @memberof OrgBrandConfig
     */
    aliases?: Array<string>;
    /**
     * @type {OrgBrandConfigCategoryEnum}
     * @memberof OrgBrandConfig
     */
    category?: OrgBrandConfigCategoryEnum;
    /**
     * Patient-facing portal name
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    portalName?: string | null;
    /**
     * Patient-facing portal URL
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    portalUrl?: string | null;
    /**
     * Patient-facing portal description (Markdown)
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    portalDescription?: string | null;
    /**
     * Patient-facing portal logo URL
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    portalLogoUrl?: string | null;
    /**
     * Portal logo license URL
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    portalLogoLicenseUrl?: string | null;
    /**
     * Organization city
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    addressCity?: string | null;
    /**
     * Organization state/province
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    addressState?: string | null;
    /**
     * Organization postal code
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    addressPostalCode?: string | null;
    /**
     * Organization country
     * @type {string | null}
     * @memberof OrgBrandConfig
     */
    addressCountry?: string | null;
    /**
     * Brand identifier URI (typically the brand website URL)
     * @type {string}
     * @memberof OrgBrandConfig
     */
    identifier?: string;
}

/**
 * @export
 */
export const OrgBrandConfigCategoryEnum = {
    Prov: 'prov',
    Ins: 'ins',
    Laboratory: 'laboratory',
    Imaging: 'imaging',
    Pharmacy: 'pharmacy',
    HealthInformationNetwork: 'health-information-network',
    HealthDataAggregator: 'health-data-aggregator',
} as const;
export type OrgBrandConfigCategoryEnum = typeof OrgBrandConfigCategoryEnum[keyof typeof OrgBrandConfigCategoryEnum];

/**
 * Check if a given object implements the OrgBrandConfig interface.
 */
export function instanceOfOrgBrandConfig(value: object): value is OrgBrandConfig {
    return true;
}

export function OrgBrandConfigFromJSON(json: any): OrgBrandConfig {
    return OrgBrandConfigFromJSONTyped(json, false);
}

export function OrgBrandConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgBrandConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'website': json['website'] == null ? undefined : json['website'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'logoLicenseUrl': json['logoLicenseUrl'] == null ? undefined : json['logoLicenseUrl'],
        'aliases': json['aliases'] == null ? undefined : json['aliases'],
        'category': json['category'] == null ? undefined : json['category'],
        'portalName': json['portalName'] == null ? undefined : json['portalName'],
        'portalUrl': json['portalUrl'] == null ? undefined : json['portalUrl'],
        'portalDescription': json['portalDescription'] == null ? undefined : json['portalDescription'],
        'portalLogoUrl': json['portalLogoUrl'] == null ? undefined : json['portalLogoUrl'],
        'portalLogoLicenseUrl': json['portalLogoLicenseUrl'] == null ? undefined : json['portalLogoLicenseUrl'],
        'addressCity': json['addressCity'] == null ? undefined : json['addressCity'],
        'addressState': json['addressState'] == null ? undefined : json['addressState'],
        'addressPostalCode': json['addressPostalCode'] == null ? undefined : json['addressPostalCode'],
        'addressCountry': json['addressCountry'] == null ? undefined : json['addressCountry'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
    };
}

export function OrgBrandConfigToJSON(json: any): OrgBrandConfig {
    return OrgBrandConfigToJSONTyped(json, false);
}

export function OrgBrandConfigToJSONTyped(value?: OrgBrandConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'website': value['website'],
        'logoUrl': value['logoUrl'],
        'logoLicenseUrl': value['logoLicenseUrl'],
        'aliases': value['aliases'],
        'category': value['category'],
        'portalName': value['portalName'],
        'portalUrl': value['portalUrl'],
        'portalDescription': value['portalDescription'],
        'portalLogoUrl': value['portalLogoUrl'],
        'portalLogoLicenseUrl': value['portalLogoLicenseUrl'],
        'addressCity': value['addressCity'],
        'addressState': value['addressState'],
        'addressPostalCode': value['addressPostalCode'],
        'addressCountry': value['addressCountry'],
        'identifier': value['identifier'],
    };
}
