/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrgBrandConfig } from './OrgBrandConfig';
import {
    OrgBrandConfigFromJSON,
    OrgBrandConfigFromJSONTyped,
    OrgBrandConfigToJSON,
    OrgBrandConfigToJSONTyped,
} from './OrgBrandConfig';

/**
 * @export
 * @interface OrgBrandConfigResponse
 */
export interface OrgBrandConfigResponse {
    /**
     * @type {string}
     * @memberof OrgBrandConfigResponse
     */
    message: string;
    /**
     * @type {string}
     * @memberof OrgBrandConfigResponse
     */
    orgId: string;
    /**
     * @type {OrgBrandConfig}
     * @memberof OrgBrandConfigResponse
     */
    config: OrgBrandConfig;
    /**
     * @type {string}
     * @memberof OrgBrandConfigResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the OrgBrandConfigResponse interface.
 */
export function instanceOfOrgBrandConfigResponse(value: object): value is OrgBrandConfigResponse {
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function OrgBrandConfigResponseFromJSON(json: any): OrgBrandConfigResponse {
    return OrgBrandConfigResponseFromJSONTyped(json, false);
}

export function OrgBrandConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgBrandConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'orgId': json['orgId'],
        'config': OrgBrandConfigFromJSON(json['config']),
        'timestamp': json['timestamp'],
    };
}

export function OrgBrandConfigResponseToJSON(json: any): OrgBrandConfigResponse {
    return OrgBrandConfigResponseToJSONTyped(json, false);
}

export function OrgBrandConfigResponseToJSONTyped(value?: OrgBrandConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'orgId': value['orgId'],
        'config': OrgBrandConfigToJSON(value['config']),
        'timestamp': value['timestamp'],
    };
}
