/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface PatchAdminMcpEndpointRequest
 */
export interface PatchAdminMcpEndpointRequest {
    /**
     * Enable or disable MCP endpoint
     * @type {boolean}
     * @memberof PatchAdminMcpEndpointRequest
     */
    enabled?: boolean;
    /**
     * Tools to block from MCP exposure
     * @type {Array<string>}
     * @memberof PatchAdminMcpEndpointRequest
     */
    disabledTools?: Array<string>;
    /**
     * Tools to allow (null = blocklist mode)
     * @type {Array<string> | null}
     * @memberof PatchAdminMcpEndpointRequest
     */
    enabledTools?: Array<string> | null;
    /**
     * Whether to also expose read-only GET resources as MCP tools with readOnlyHint
     * @type {boolean}
     * @memberof PatchAdminMcpEndpointRequest
     */
    exposeResourcesAsTools?: boolean;
}

/**
 * Check if a given object implements the PatchAdminMcpEndpointRequest interface.
 */
export function instanceOfPatchAdminMcpEndpointRequest(value: object): value is PatchAdminMcpEndpointRequest {
    return true;
}

export function PatchAdminMcpEndpointRequestFromJSON(json: any): PatchAdminMcpEndpointRequest {
    return PatchAdminMcpEndpointRequestFromJSONTyped(json, false);
}

export function PatchAdminMcpEndpointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchAdminMcpEndpointRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'disabledTools': json['disabledTools'] == null ? undefined : json['disabledTools'],
        'enabledTools': json['enabledTools'] == null ? undefined : json['enabledTools'],
        'exposeResourcesAsTools': json['exposeResourcesAsTools'] == null ? undefined : json['exposeResourcesAsTools'],
    };
}

export function PatchAdminMcpEndpointRequestToJSON(json: any): PatchAdminMcpEndpointRequest {
    return PatchAdminMcpEndpointRequestToJSONTyped(json, false);
}

export function PatchAdminMcpEndpointRequestToJSONTyped(value?: PatchAdminMcpEndpointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'disabledTools': value['disabledTools'],
        'enabledTools': value['enabledTools'],
        'exposeResourcesAsTools': value['exposeResourcesAsTools'],
    };
}
