/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAdminConsentWebhookRequestResourcePatient } from './PostAdminConsentWebhookRequestResourcePatient';
import {
    PostAdminConsentWebhookRequestResourcePatientFromJSON,
    PostAdminConsentWebhookRequestResourcePatientFromJSONTyped,
    PostAdminConsentWebhookRequestResourcePatientToJSON,
    PostAdminConsentWebhookRequestResourcePatientToJSONTyped,
} from './PostAdminConsentWebhookRequestResourcePatient';

/**
 * @export
 * @interface PostAdminConsentWebhookRequestResource
 */
export interface PostAdminConsentWebhookRequestResource {
    /**
     * @type {PostAdminConsentWebhookRequestResourcePatient}
     * @memberof PostAdminConsentWebhookRequestResource
     */
    patient?: PostAdminConsentWebhookRequestResourcePatient;
}

/**
 * Check if a given object implements the PostAdminConsentWebhookRequestResource interface.
 */
export function instanceOfPostAdminConsentWebhookRequestResource(value: object): value is PostAdminConsentWebhookRequestResource {
    return true;
}

export function PostAdminConsentWebhookRequestResourceFromJSON(json: any): PostAdminConsentWebhookRequestResource {
    return PostAdminConsentWebhookRequestResourceFromJSONTyped(json, false);
}

export function PostAdminConsentWebhookRequestResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminConsentWebhookRequestResource {
    if (json == null) {
        return json;
    }
    return {
        
        'patient': json['patient'] == null ? undefined : PostAdminConsentWebhookRequestResourcePatientFromJSON(json['patient']),
    };
}

export function PostAdminConsentWebhookRequestResourceToJSON(json: any): PostAdminConsentWebhookRequestResource {
    return PostAdminConsentWebhookRequestResourceToJSONTyped(json, false);
}

export function PostAdminConsentWebhookRequestResourceToJSONTyped(value?: PostAdminConsentWebhookRequestResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patient': PostAdminConsentWebhookRequestResourcePatientToJSON(value['patient']),
    };
}
