/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface PostAdminOrganizationsByOrgIdMembersRequest
 */
export interface PostAdminOrganizationsByOrgIdMembersRequest {
    /**
     * Keycloak user ID to add as member
     * @type {string}
     * @memberof PostAdminOrganizationsByOrgIdMembersRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the PostAdminOrganizationsByOrgIdMembersRequest interface.
 */
export function instanceOfPostAdminOrganizationsByOrgIdMembersRequest(value: object): value is PostAdminOrganizationsByOrgIdMembersRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function PostAdminOrganizationsByOrgIdMembersRequestFromJSON(json: any): PostAdminOrganizationsByOrgIdMembersRequest {
    return PostAdminOrganizationsByOrgIdMembersRequestFromJSONTyped(json, false);
}

export function PostAdminOrganizationsByOrgIdMembersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminOrganizationsByOrgIdMembersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function PostAdminOrganizationsByOrgIdMembersRequestToJSON(json: any): PostAdminOrganizationsByOrgIdMembersRequest {
    return PostAdminOrganizationsByOrgIdMembersRequestToJSONTyped(json, false);
}

export function PostAdminOrganizationsByOrgIdMembersRequestToJSONTyped(value?: PostAdminOrganizationsByOrgIdMembersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}
