/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface PostAdminAiToolsSkillsRequest
 */
export interface PostAdminAiToolsSkillsRequest {
    /**
     * Skill name (unique identifier)
     * @type {string}
     * @memberof PostAdminAiToolsSkillsRequest
     */
    name: string;
    /**
     * Skill description
     * @type {string}
     * @memberof PostAdminAiToolsSkillsRequest
     */
    description?: string;
    /**
     * Source URL (e.g. GitHub repo)
     * @type {string}
     * @memberof PostAdminAiToolsSkillsRequest
     */
    sourceUrl?: string;
}

/**
 * Check if a given object implements the PostAdminAiToolsSkillsRequest interface.
 */
export function instanceOfPostAdminAiToolsSkillsRequest(value: object): value is PostAdminAiToolsSkillsRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PostAdminAiToolsSkillsRequestFromJSON(json: any): PostAdminAiToolsSkillsRequest {
    return PostAdminAiToolsSkillsRequestFromJSONTyped(json, false);
}

export function PostAdminAiToolsSkillsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminAiToolsSkillsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'sourceUrl': json['sourceUrl'] == null ? undefined : json['sourceUrl'],
    };
}

export function PostAdminAiToolsSkillsRequestToJSON(json: any): PostAdminAiToolsSkillsRequest {
    return PostAdminAiToolsSkillsRequestToJSONTyped(json, false);
}

export function PostAdminAiToolsSkillsRequestToJSONTyped(value?: PostAdminAiToolsSkillsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'sourceUrl': value['sourceUrl'],
    };
}
