/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface PostAdminDocumentImport200ResponseResourcesInner
 */
export interface PostAdminDocumentImport200ResponseResourcesInner {
    /**
     * @type {string}
     * @memberof PostAdminDocumentImport200ResponseResourcesInner
     */
    resourceType: string;
    /**
     * Validated FHIR R4 resource — POST to your FHIR proxy
     * @type {any}
     * @memberof PostAdminDocumentImport200ResponseResourcesInner
     */
    resource: any;
    /**
     * @type {number}
     * @memberof PostAdminDocumentImport200ResponseResourcesInner
     */
    retriesNeeded: number;
    /**
     * @type {Array<string>}
     * @memberof PostAdminDocumentImport200ResponseResourcesInner
     */
    warnings: Array<string>;
}

/**
 * Check if a given object implements the PostAdminDocumentImport200ResponseResourcesInner interface.
 */
export function instanceOfPostAdminDocumentImport200ResponseResourcesInner(value: object): value is PostAdminDocumentImport200ResponseResourcesInner {
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    if (!('retriesNeeded' in value) || value['retriesNeeded'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('resource' in value) || value['resource'] === undefined) return false;
    return true;
}

export function PostAdminDocumentImport200ResponseResourcesInnerFromJSON(json: any): PostAdminDocumentImport200ResponseResourcesInner {
    return PostAdminDocumentImport200ResponseResourcesInnerFromJSONTyped(json, false);
}

export function PostAdminDocumentImport200ResponseResourcesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminDocumentImport200ResponseResourcesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceType': json['resourceType'],
        'resource': json['resource'],
        'retriesNeeded': json['retriesNeeded'],
        'warnings': json['warnings'],
    };
}

export function PostAdminDocumentImport200ResponseResourcesInnerToJSON(json: any): PostAdminDocumentImport200ResponseResourcesInner {
    return PostAdminDocumentImport200ResponseResourcesInnerToJSONTyped(json, false);
}

export function PostAdminDocumentImport200ResponseResourcesInnerToJSONTyped(value?: PostAdminDocumentImport200ResponseResourcesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resourceType': value['resourceType'],
        'resource': value['resource'],
        'retriesNeeded': value['retriesNeeded'],
        'warnings': value['warnings'],
    };
}
