/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAdminDocumentImport200ResponseFailedInner } from './PostAdminDocumentImport200ResponseFailedInner';
import {
    PostAdminDocumentImport200ResponseFailedInnerFromJSON,
    PostAdminDocumentImport200ResponseFailedInnerFromJSONTyped,
    PostAdminDocumentImport200ResponseFailedInnerToJSON,
    PostAdminDocumentImport200ResponseFailedInnerToJSONTyped,
} from './PostAdminDocumentImport200ResponseFailedInner';
import type { PostAdminDocumentImport200ResponseResourcesInner } from './PostAdminDocumentImport200ResponseResourcesInner';
import {
    PostAdminDocumentImport200ResponseResourcesInnerFromJSON,
    PostAdminDocumentImport200ResponseResourcesInnerFromJSONTyped,
    PostAdminDocumentImport200ResponseResourcesInnerToJSON,
    PostAdminDocumentImport200ResponseResourcesInnerToJSONTyped,
} from './PostAdminDocumentImport200ResponseResourcesInner';

/**
 * @export
 * @interface PostAdminDocumentImport200Response
 */
export interface PostAdminDocumentImport200Response {
    /**
     * @type {boolean}
     * @memberof PostAdminDocumentImport200Response
     */
    success: boolean;
    /**
     * @type {string}
     * @memberof PostAdminDocumentImport200Response
     */
    fileName: string;
    /**
     * @type {number}
     * @memberof PostAdminDocumentImport200Response
     */
    pagesProcessed: number;
    /**
     * @type {string}
     * @memberof PostAdminDocumentImport200Response
     */
    engine: string;
    /**
     * @type {Array<PostAdminDocumentImport200ResponseResourcesInner>}
     * @memberof PostAdminDocumentImport200Response
     */
    resources: Array<PostAdminDocumentImport200ResponseResourcesInner>;
    /**
     * @type {Array<PostAdminDocumentImport200ResponseFailedInner>}
     * @memberof PostAdminDocumentImport200Response
     */
    failed: Array<PostAdminDocumentImport200ResponseFailedInner>;
    /**
     * FHIR DocumentReference wrapping the original PDF
     * @type {any}
     * @memberof PostAdminDocumentImport200Response
     */
    documentReference: any;
    /**
     * @type {number}
     * @memberof PostAdminDocumentImport200Response
     */
    processingTimeMs: number;
}

/**
 * Check if a given object implements the PostAdminDocumentImport200Response interface.
 */
export function instanceOfPostAdminDocumentImport200Response(value: object): value is PostAdminDocumentImport200Response {
    if (!('engine' in value) || value['engine'] === undefined) return false;
    if (!('processingTimeMs' in value) || value['processingTimeMs'] === undefined) return false;
    if (!('documentReference' in value) || value['documentReference'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('pagesProcessed' in value) || value['pagesProcessed'] === undefined) return false;
    if (!('resources' in value) || value['resources'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function PostAdminDocumentImport200ResponseFromJSON(json: any): PostAdminDocumentImport200Response {
    return PostAdminDocumentImport200ResponseFromJSONTyped(json, false);
}

export function PostAdminDocumentImport200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminDocumentImport200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'fileName': json['fileName'],
        'pagesProcessed': json['pagesProcessed'],
        'engine': json['engine'],
        'resources': ((json['resources'] as Array<any>).map(PostAdminDocumentImport200ResponseResourcesInnerFromJSON)),
        'failed': ((json['failed'] as Array<any>).map(PostAdminDocumentImport200ResponseFailedInnerFromJSON)),
        'documentReference': json['documentReference'],
        'processingTimeMs': json['processingTimeMs'],
    };
}

export function PostAdminDocumentImport200ResponseToJSON(json: any): PostAdminDocumentImport200Response {
    return PostAdminDocumentImport200ResponseToJSONTyped(json, false);
}

export function PostAdminDocumentImport200ResponseToJSONTyped(value?: PostAdminDocumentImport200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'fileName': value['fileName'],
        'pagesProcessed': value['pagesProcessed'],
        'engine': value['engine'],
        'resources': value['resources'] == null ? undefined : ((value['resources'] as Array<any>).map(PostAdminDocumentImport200ResponseResourcesInnerToJSON)),
        'failed': value['failed'] == null ? undefined : ((value['failed'] as Array<any>).map(PostAdminDocumentImport200ResponseFailedInnerToJSON)),
        'documentReference': value['documentReference'],
        'processingTimeMs': value['processingTimeMs'],
    };
}
