/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface PostAdminConsentCacheInvalidate200Response
 */
export interface PostAdminConsentCacheInvalidate200Response {
    /**
     * @type {string}
     * @memberof PostAdminConsentCacheInvalidate200Response
     */
    message: string;
    /**
     * @type {number}
     * @memberof PostAdminConsentCacheInvalidate200Response
     */
    entriesInvalidated: number;
    /**
     * @type {string}
     * @memberof PostAdminConsentCacheInvalidate200Response
     */
    timestamp: string;
}

/**
 * Check if a given object implements the PostAdminConsentCacheInvalidate200Response interface.
 */
export function instanceOfPostAdminConsentCacheInvalidate200Response(value: object): value is PostAdminConsentCacheInvalidate200Response {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('entriesInvalidated' in value) || value['entriesInvalidated'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostAdminConsentCacheInvalidate200ResponseFromJSON(json: any): PostAdminConsentCacheInvalidate200Response {
    return PostAdminConsentCacheInvalidate200ResponseFromJSONTyped(json, false);
}

export function PostAdminConsentCacheInvalidate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminConsentCacheInvalidate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'entriesInvalidated': json['entriesInvalidated'],
        'timestamp': json['timestamp'],
    };
}

export function PostAdminConsentCacheInvalidate200ResponseToJSON(json: any): PostAdminConsentCacheInvalidate200Response {
    return PostAdminConsentCacheInvalidate200ResponseToJSONTyped(json, false);
}

export function PostAdminConsentCacheInvalidate200ResponseToJSONTyped(value?: PostAdminConsentCacheInvalidate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'entriesInvalidated': value['entriesInvalidated'],
        'timestamp': value['timestamp'],
    };
}
