/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface PostAdminAccessControlDoorsByIdUnlock200Response
 */
export interface PostAdminAccessControlDoorsByIdUnlock200Response {
    /**
     * @type {string}
     * @memberof PostAdminAccessControlDoorsByIdUnlock200Response
     */
    message: string;
}

/**
 * Check if a given object implements the PostAdminAccessControlDoorsByIdUnlock200Response interface.
 */
export function instanceOfPostAdminAccessControlDoorsByIdUnlock200Response(value: object): value is PostAdminAccessControlDoorsByIdUnlock200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostAdminAccessControlDoorsByIdUnlock200ResponseFromJSON(json: any): PostAdminAccessControlDoorsByIdUnlock200Response {
    return PostAdminAccessControlDoorsByIdUnlock200ResponseFromJSONTyped(json, false);
}

export function PostAdminAccessControlDoorsByIdUnlock200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminAccessControlDoorsByIdUnlock200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function PostAdminAccessControlDoorsByIdUnlock200ResponseToJSON(json: any): PostAdminAccessControlDoorsByIdUnlock200Response {
    return PostAdminAccessControlDoorsByIdUnlock200ResponseToJSONTyped(json, false);
}

export function PostAdminAccessControlDoorsByIdUnlock200ResponseToJSONTyped(value?: PostAdminAccessControlDoorsByIdUnlock200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}
