/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAdminOrganizations200ResponseInnerDomainsInner } from './GetAdminOrganizations200ResponseInnerDomainsInner';
import {
    GetAdminOrganizations200ResponseInnerDomainsInnerFromJSON,
    GetAdminOrganizations200ResponseInnerDomainsInnerFromJSONTyped,
    GetAdminOrganizations200ResponseInnerDomainsInnerToJSON,
    GetAdminOrganizations200ResponseInnerDomainsInnerToJSONTyped,
} from './GetAdminOrganizations200ResponseInnerDomainsInner';

/**
 * @export
 * @interface PutAdminOrganizationsByOrgIdRequest
 */
export interface PutAdminOrganizationsByOrgIdRequest {
    /**
     * Organization display name
     * @type {string}
     * @memberof PutAdminOrganizationsByOrgIdRequest
     */
    name?: string;
    /**
     * Free-text description
     * @type {string}
     * @memberof PutAdminOrganizationsByOrgIdRequest
     */
    description?: string;
    /**
     * Post-registration redirect URL
     * @type {string}
     * @memberof PutAdminOrganizationsByOrgIdRequest
     */
    redirectUrl?: string;
    /**
     * Enabled state
     * @type {boolean}
     * @memberof PutAdminOrganizationsByOrgIdRequest
     */
    enabled?: boolean;
    /**
     * @type {{ [key: string]: Array<string> }}
     * @memberof PutAdminOrganizationsByOrgIdRequest
     */
    attributes?: { [key: string]: Array<string> };
    /**
     * @type {Array<GetAdminOrganizations200ResponseInnerDomainsInner>}
     * @memberof PutAdminOrganizationsByOrgIdRequest
     */
    domains?: Array<GetAdminOrganizations200ResponseInnerDomainsInner>;
}

/**
 * Check if a given object implements the PutAdminOrganizationsByOrgIdRequest interface.
 */
export function instanceOfPutAdminOrganizationsByOrgIdRequest(value: object): value is PutAdminOrganizationsByOrgIdRequest {
    return true;
}

export function PutAdminOrganizationsByOrgIdRequestFromJSON(json: any): PutAdminOrganizationsByOrgIdRequest {
    return PutAdminOrganizationsByOrgIdRequestFromJSONTyped(json, false);
}

export function PutAdminOrganizationsByOrgIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAdminOrganizationsByOrgIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'domains': json['domains'] == null ? undefined : ((json['domains'] as Array<any>).map(GetAdminOrganizations200ResponseInnerDomainsInnerFromJSON)),
    };
}

export function PutAdminOrganizationsByOrgIdRequestToJSON(json: any): PutAdminOrganizationsByOrgIdRequest {
    return PutAdminOrganizationsByOrgIdRequestToJSONTyped(json, false);
}

export function PutAdminOrganizationsByOrgIdRequestToJSONTyped(value?: PutAdminOrganizationsByOrgIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'redirectUrl': value['redirectUrl'],
        'enabled': value['enabled'],
        'attributes': value['attributes'],
        'domains': value['domains'] == null ? undefined : ((value['domains'] as Array<any>).map(GetAdminOrganizations200ResponseInnerDomainsInnerToJSON)),
    };
}
