/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface ScopeMapperFixResponse
 */
export interface ScopeMapperFixResponse {
    /**
     * @type {string}
     * @memberof ScopeMapperFixResponse
     */
    message: string;
    /**
     * Number of scopes scanned
     * @type {number}
     * @memberof ScopeMapperFixResponse
     */
    scanned: number;
    /**
     * Number of mappers created
     * @type {number}
     * @memberof ScopeMapperFixResponse
     */
    created: number;
    /**
     * Any errors encountered
     * @type {Array<string>}
     * @memberof ScopeMapperFixResponse
     */
    errors: Array<string>;
    /**
     * @type {string}
     * @memberof ScopeMapperFixResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ScopeMapperFixResponse interface.
 */
export function instanceOfScopeMapperFixResponse(value: object): value is ScopeMapperFixResponse {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('scanned' in value) || value['scanned'] === undefined) return false;
    return true;
}

export function ScopeMapperFixResponseFromJSON(json: any): ScopeMapperFixResponse {
    return ScopeMapperFixResponseFromJSONTyped(json, false);
}

export function ScopeMapperFixResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScopeMapperFixResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'scanned': json['scanned'],
        'created': json['created'],
        'errors': json['errors'],
        'timestamp': json['timestamp'],
    };
}

export function ScopeMapperFixResponseToJSON(json: any): ScopeMapperFixResponse {
    return ScopeMapperFixResponseToJSONTyped(json, false);
}

export function ScopeMapperFixResponseToJSONTyped(value?: ScopeMapperFixResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'scanned': value['scanned'],
        'created': value['created'],
        'errors': value['errors'],
        'timestamp': value['timestamp'],
    };
}
