/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface ScopeMapperEntry
 */
export interface ScopeMapperEntry {
    /**
     * Keycloak mapper ID
     * @type {string}
     * @memberof ScopeMapperEntry
     */
    id?: string;
    /**
     * Mapper name
     * @type {string}
     * @memberof ScopeMapperEntry
     */
    name: string;
    /**
     * Token claim name
     * @type {string}
     * @memberof ScopeMapperEntry
     */
    claimName: string;
    /**
     * User attribute source
     * @type {string}
     * @memberof ScopeMapperEntry
     */
    userAttribute: string;
    /**
     * Include in access token
     * @type {boolean}
     * @memberof ScopeMapperEntry
     */
    accessTokenClaim: boolean;
    /**
     * Include in ID token
     * @type {boolean}
     * @memberof ScopeMapperEntry
     */
    idTokenClaim: boolean;
    /**
     * Include in userinfo
     * @type {boolean}
     * @memberof ScopeMapperEntry
     */
    userinfoTokenClaim: boolean;
}

/**
 * Check if a given object implements the ScopeMapperEntry interface.
 */
export function instanceOfScopeMapperEntry(value: object): value is ScopeMapperEntry {
    if (!('accessTokenClaim' in value) || value['accessTokenClaim'] === undefined) return false;
    if (!('idTokenClaim' in value) || value['idTokenClaim'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('userAttribute' in value) || value['userAttribute'] === undefined) return false;
    if (!('claimName' in value) || value['claimName'] === undefined) return false;
    if (!('userinfoTokenClaim' in value) || value['userinfoTokenClaim'] === undefined) return false;
    return true;
}

export function ScopeMapperEntryFromJSON(json: any): ScopeMapperEntry {
    return ScopeMapperEntryFromJSONTyped(json, false);
}

export function ScopeMapperEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScopeMapperEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'claimName': json['claimName'],
        'userAttribute': json['userAttribute'],
        'accessTokenClaim': json['accessTokenClaim'],
        'idTokenClaim': json['idTokenClaim'],
        'userinfoTokenClaim': json['userinfoTokenClaim'],
    };
}

export function ScopeMapperEntryToJSON(json: any): ScopeMapperEntry {
    return ScopeMapperEntryToJSONTyped(json, false);
}

export function ScopeMapperEntryToJSONTyped(value?: ScopeMapperEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'claimName': value['claimName'],
        'userAttribute': value['userAttribute'],
        'accessTokenClaim': value['accessTokenClaim'],
        'idTokenClaim': value['idTokenClaim'],
        'userinfoTokenClaim': value['userinfoTokenClaim'],
    };
}
