/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface SetIntentRequest
 */
export interface SetIntentRequest {
    /**
     * Intent string (e.g., reconcile-medications)
     * @type {string}
     * @memberof SetIntentRequest
     */
    intent: string;
}

/**
 * Check if a given object implements the SetIntentRequest interface.
 */
export function instanceOfSetIntentRequest(value: object): value is SetIntentRequest {
    if (!('intent' in value) || value['intent'] === undefined) return false;
    return true;
}

export function SetIntentRequestFromJSON(json: any): SetIntentRequest {
    return SetIntentRequestFromJSONTyped(json, false);
}

export function SetIntentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetIntentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'intent': json['intent'],
    };
}

export function SetIntentRequestToJSON(json: any): SetIntentRequest {
    return SetIntentRequestToJSONTyped(json, false);
}

export function SetIntentRequestToJSONTyped(value?: SetIntentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'intent': value['intent'],
    };
}
