/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface SetSmartStyleUrlRequest
 */
export interface SetSmartStyleUrlRequest {
    /**
     * URL to CSS stylesheet for styling
     * @type {string}
     * @memberof SetSmartStyleUrlRequest
     */
    styleUrl: string;
}

/**
 * Check if a given object implements the SetSmartStyleUrlRequest interface.
 */
export function instanceOfSetSmartStyleUrlRequest(value: object): value is SetSmartStyleUrlRequest {
    if (!('styleUrl' in value) || value['styleUrl'] === undefined) return false;
    return true;
}

export function SetSmartStyleUrlRequestFromJSON(json: any): SetSmartStyleUrlRequest {
    return SetSmartStyleUrlRequestFromJSONTyped(json, false);
}

export function SetSmartStyleUrlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetSmartStyleUrlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'styleUrl': json['styleUrl'],
    };
}

export function SetSmartStyleUrlRequestToJSON(json: any): SetSmartStyleUrlRequest {
    return SetSmartStyleUrlRequestToJSONTyped(json, false);
}

export function SetSmartStyleUrlRequestToJSONTyped(value?: SetSmartStyleUrlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'styleUrl': value['styleUrl'],
    };
}
