/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface SetStrictCapabilitiesRequest
 */
export interface SetStrictCapabilitiesRequest {
    /**
     * Whether to enforce the FHIR CapabilityStatement strictly
     * @type {boolean}
     * @memberof SetStrictCapabilitiesRequest
     */
    strict: boolean;
}

/**
 * Check if a given object implements the SetStrictCapabilitiesRequest interface.
 */
export function instanceOfSetStrictCapabilitiesRequest(value: object): value is SetStrictCapabilitiesRequest {
    if (!('strict' in value) || value['strict'] === undefined) return false;
    return true;
}

export function SetStrictCapabilitiesRequestFromJSON(json: any): SetStrictCapabilitiesRequest {
    return SetStrictCapabilitiesRequestFromJSONTyped(json, false);
}

export function SetStrictCapabilitiesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetStrictCapabilitiesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'strict': json['strict'],
    };
}

export function SetStrictCapabilitiesRequestToJSON(json: any): SetStrictCapabilitiesRequest {
    return SetStrictCapabilitiesRequestToJSONTyped(json, false);
}

export function SetStrictCapabilitiesRequestToJSONTyped(value?: SetStrictCapabilitiesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strict': value['strict'],
    };
}
