/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface TestKeycloakConnectionResponse
 */
export interface TestKeycloakConnectionResponse {
    /**
     * Whether the connection test succeeded
     * @type {boolean}
     * @memberof TestKeycloakConnectionResponse
     */
    success: boolean;
    /**
     * Success message
     * @type {string}
     * @memberof TestKeycloakConnectionResponse
     */
    message?: string;
    /**
     * Error message if connection failed
     * @type {string}
     * @memberof TestKeycloakConnectionResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the TestKeycloakConnectionResponse interface.
 */
export function instanceOfTestKeycloakConnectionResponse(value: object): value is TestKeycloakConnectionResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function TestKeycloakConnectionResponseFromJSON(json: any): TestKeycloakConnectionResponse {
    return TestKeycloakConnectionResponseFromJSONTyped(json, false);
}

export function TestKeycloakConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestKeycloakConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function TestKeycloakConnectionResponseToJSON(json: any): TestKeycloakConnectionResponse {
    return TestKeycloakConnectionResponseToJSONTyped(json, false);
}

export function TestKeycloakConnectionResponseToJSONTyped(value?: TestKeycloakConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'error': value['error'],
    };
}
