/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface TokenRequest
 */
export interface TokenRequest {
    /**
     * OAuth2 grant type (authorization_code, refresh_token, client_credentials, password, urn:ietf:params:oauth:grant-type:token-exchange)
     * @type {string}
     * @memberof TokenRequest
     */
    grantType: string;
    /**
     * Authorization code (for authorization_code grant)
     * @type {string}
     * @memberof TokenRequest
     */
    code?: string;
    /**
     * Redirect URI used in authorization request
     * @type {string}
     * @memberof TokenRequest
     */
    redirectUri?: string;
    /**
     * OAuth2 client ID
     * @type {string}
     * @memberof TokenRequest
     */
    clientId?: string;
    /**
     * OAuth2 client secret
     * @type {string}
     * @memberof TokenRequest
     */
    clientSecret?: string;
    /**
     * PKCE code verifier
     * @type {string}
     * @memberof TokenRequest
     */
    codeVerifier?: string;
    /**
     * Refresh token (for refresh_token grant)
     * @type {string}
     * @memberof TokenRequest
     */
    refreshToken?: string;
    /**
     * Requested scopes (space-separated)
     * @type {string}
     * @memberof TokenRequest
     */
    scope?: string;
    /**
     * Target audience for the token
     * @type {string}
     * @memberof TokenRequest
     */
    audience?: string;
    /**
     * Target resource URI (RFC 8707 Resource Indicators)
     * @type {string}
     * @memberof TokenRequest
     */
    resource?: string;
    /**
     * Username (for password grant)
     * @type {string}
     * @memberof TokenRequest
     */
    username?: string;
    /**
     * Password (for password grant)
     * @type {string}
     * @memberof TokenRequest
     */
    password?: string;
    /**
     * Client assertion type for JWT authentication
     * @type {string}
     * @memberof TokenRequest
     */
    clientAssertionType?: string;
    /**
     * Client assertion JWT for authentication
     * @type {string}
     * @memberof TokenRequest
     */
    clientAssertion?: string;
    /**
     * Security token to be exchanged (for token-exchange grant)
     * @type {string}
     * @memberof TokenRequest
     */
    subjectToken?: string;
    /**
     * Type of subject_token (urn:ietf:params:oauth:token-type:access_token)
     * @type {string}
     * @memberof TokenRequest
     */
    subjectTokenType?: string;
    /**
     * Type of requested token (urn:ietf:params:oauth:token-type:access_token)
     * @type {string}
     * @memberof TokenRequest
     */
    requestedTokenType?: string;
}

/**
 * Check if a given object implements the TokenRequest interface.
 */
export function instanceOfTokenRequest(value: object): value is TokenRequest {
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    return true;
}

export function TokenRequestFromJSON(json: any): TokenRequest {
    return TokenRequestFromJSONTyped(json, false);
}

export function TokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'grantType': json['grant_type'],
        'code': json['code'] == null ? undefined : json['code'],
        'redirectUri': json['redirect_uri'] == null ? undefined : json['redirect_uri'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
        'codeVerifier': json['code_verifier'] == null ? undefined : json['code_verifier'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'audience': json['audience'] == null ? undefined : json['audience'],
        'resource': json['resource'] == null ? undefined : json['resource'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'clientAssertionType': json['client_assertion_type'] == null ? undefined : json['client_assertion_type'],
        'clientAssertion': json['client_assertion'] == null ? undefined : json['client_assertion'],
        'subjectToken': json['subject_token'] == null ? undefined : json['subject_token'],
        'subjectTokenType': json['subject_token_type'] == null ? undefined : json['subject_token_type'],
        'requestedTokenType': json['requested_token_type'] == null ? undefined : json['requested_token_type'],
    };
}

export function TokenRequestToJSON(json: any): TokenRequest {
    return TokenRequestToJSONTyped(json, false);
}

export function TokenRequestToJSONTyped(value?: TokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grant_type': value['grantType'],
        'code': value['code'],
        'redirect_uri': value['redirectUri'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'code_verifier': value['codeVerifier'],
        'refresh_token': value['refreshToken'],
        'scope': value['scope'],
        'audience': value['audience'],
        'resource': value['resource'],
        'username': value['username'],
        'password': value['password'],
        'client_assertion_type': value['clientAssertionType'],
        'client_assertion': value['clientAssertion'],
        'subject_token': value['subjectToken'],
        'subject_token_type': value['subjectTokenType'],
        'requested_token_type': value['requestedTokenType'],
    };
}
