/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationDomain } from './OrganizationDomain';
import {
    OrganizationDomainFromJSON,
    OrganizationDomainFromJSONTyped,
    OrganizationDomainToJSON,
    OrganizationDomainToJSONTyped,
} from './OrganizationDomain';

/**
 * @export
 * @interface UpdateOrganizationRequest
 */
export interface UpdateOrganizationRequest {
    /**
     * Organization display name
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    name?: string;
    /**
     * Free-text description
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    description?: string;
    /**
     * Post-registration redirect URL
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    redirectUrl?: string;
    /**
     * Enabled state
     * @type {boolean}
     * @memberof UpdateOrganizationRequest
     */
    enabled?: boolean;
    /**
     * @type {{ [key: string]: Array<string> }}
     * @memberof UpdateOrganizationRequest
     */
    attributes?: { [key: string]: Array<string> };
    /**
     * @type {Array<OrganizationDomain>}
     * @memberof UpdateOrganizationRequest
     */
    domains?: Array<OrganizationDomain>;
}

/**
 * Check if a given object implements the UpdateOrganizationRequest interface.
 */
export function instanceOfUpdateOrganizationRequest(value: object): value is UpdateOrganizationRequest {
    return true;
}

export function UpdateOrganizationRequestFromJSON(json: any): UpdateOrganizationRequest {
    return UpdateOrganizationRequestFromJSONTyped(json, false);
}

export function UpdateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'domains': json['domains'] == null ? undefined : ((json['domains'] as Array<any>).map(OrganizationDomainFromJSON)),
    };
}

export function UpdateOrganizationRequestToJSON(json: any): UpdateOrganizationRequest {
    return UpdateOrganizationRequestToJSONTyped(json, false);
}

export function UpdateOrganizationRequestToJSONTyped(value?: UpdateOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'redirectUrl': value['redirectUrl'],
        'enabled': value['enabled'],
        'attributes': value['attributes'],
        'domains': value['domains'] == null ? undefined : ((value['domains'] as Array<any>).map(OrganizationDomainToJSON)),
    };
}
