/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142113.a183073f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface UpdateSmartAppRequest
 */
export interface UpdateSmartAppRequest {
    /**
     * Application name
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    name?: string;
    /**
     * Application description
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    description?: string;
    /**
     * Whether the app is enabled
     * @type {boolean}
     * @memberof UpdateSmartAppRequest
     */
    enabled?: boolean;
    /**
     * Whether this is a public client
     * @type {boolean}
     * @memberof UpdateSmartAppRequest
     */
    publicClient?: boolean;
    /**
     * Allowed redirect URIs
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    redirectUris?: Array<string>;
    /**
     * Allowed web origins
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    webOrigins?: Array<string>;
    /**
     * Default SMART scopes
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    defaultClientScopes?: Array<string>;
    /**
     * Optional SMART scopes
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    optionalClientScopes?: Array<string>;
    /**
     * SMART App Launch version
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    smartVersion?: string;
    /**
     * FHIR version
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    fhirVersion?: string;
    /**
     * @type {UpdateSmartAppRequestAppTypeEnum}
     * @memberof UpdateSmartAppRequest
     */
    appType?: UpdateSmartAppRequestAppTypeEnum;
    /**
     * @type {UpdateSmartAppRequestClientTypeEnum}
     * @memberof UpdateSmartAppRequest
     */
    clientType?: UpdateSmartAppRequestClientTypeEnum;
    /**
     * Client secret for symmetric authentication (only for confidential clients)
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    secret?: string;
    /**
     * Public key for JWT authentication (PEM format)
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    publicKey?: string;
    /**
     * JWKS URI for JWT authentication
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    jwksUri?: string;
    /**
     * Inline JWKS JSON string containing public keys for JWT authentication (alternative to jwksUri or publicKey)
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    jwksString?: string;
    /**
     * System-level scopes for backend services
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    systemScopes?: Array<string>;
    /**
     * SMART App launch URL
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    launchUrl?: string;
    /**
     * Logo URI for application display
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    logoUri?: string;
    /**
     * Terms of Service URI
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    tosUri?: string;
    /**
     * Privacy Policy URI
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    policyUri?: string;
    /**
     * Contact emails or names
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    contacts?: Array<string>;
    /**
     * FHIR server access control type
     * @type {UpdateSmartAppRequestServerAccessTypeEnum}
     * @memberof UpdateSmartAppRequest
     */
    serverAccessType?: UpdateSmartAppRequestServerAccessTypeEnum;
    /**
     * List of allowed FHIR server IDs
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    allowedServerIds?: Array<string>;
    /**
     * Reference to a predefined scope set configuration
     * @type {string}
     * @memberof UpdateSmartAppRequest
     */
    scopeSetId?: string;
    /**
     * Require PKCE for public clients
     * @type {boolean}
     * @memberof UpdateSmartAppRequest
     */
    requirePkce?: boolean;
    /**
     * Allow offline access (refresh tokens)
     * @type {boolean}
     * @memberof UpdateSmartAppRequest
     */
    allowOfflineAccess?: boolean;
    /**
     * MCP server access control type
     * @type {UpdateSmartAppRequestMcpAccessTypeEnum}
     * @memberof UpdateSmartAppRequest
     */
    mcpAccessType?: UpdateSmartAppRequestMcpAccessTypeEnum;
    /**
     * List of allowed MCP server names
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    allowedMcpServerNames?: Array<string>;
    /**
     * List of allowed skill names assigned to this app
     * @type {Array<string>}
     * @memberof UpdateSmartAppRequest
     */
    allowedSkillNames?: Array<string>;
}

/**
 * @export
 */
export const UpdateSmartAppRequestAppTypeEnum = {
    StandaloneApp: 'standalone-app',
    EhrLaunch: 'ehr-launch',
    BackendService: 'backend-service',
    Agent: 'agent',
} as const;
export type UpdateSmartAppRequestAppTypeEnum = typeof UpdateSmartAppRequestAppTypeEnum[keyof typeof UpdateSmartAppRequestAppTypeEnum];

/**
 * @export
 */
export const UpdateSmartAppRequestClientTypeEnum = {
    Public: 'public',
    Confidential: 'confidential',
    BackendService: 'backend-service',
} as const;
export type UpdateSmartAppRequestClientTypeEnum = typeof UpdateSmartAppRequestClientTypeEnum[keyof typeof UpdateSmartAppRequestClientTypeEnum];

/**
 * @export
 */
export const UpdateSmartAppRequestServerAccessTypeEnum = {
    AllServers: 'all-servers',
    SelectedServers: 'selected-servers',
    UserPersonServers: 'user-person-servers',
} as const;
export type UpdateSmartAppRequestServerAccessTypeEnum = typeof UpdateSmartAppRequestServerAccessTypeEnum[keyof typeof UpdateSmartAppRequestServerAccessTypeEnum];

/**
 * @export
 */
export const UpdateSmartAppRequestMcpAccessTypeEnum = {
    None: 'none',
    AllMcpServers: 'all-mcp-servers',
    SelectedMcpServers: 'selected-mcp-servers',
} as const;
export type UpdateSmartAppRequestMcpAccessTypeEnum = typeof UpdateSmartAppRequestMcpAccessTypeEnum[keyof typeof UpdateSmartAppRequestMcpAccessTypeEnum];

/**
 * Check if a given object implements the UpdateSmartAppRequest interface.
 */
export function instanceOfUpdateSmartAppRequest(value: object): value is UpdateSmartAppRequest {
    return true;
}

export function UpdateSmartAppRequestFromJSON(json: any): UpdateSmartAppRequest {
    return UpdateSmartAppRequestFromJSONTyped(json, false);
}

export function UpdateSmartAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSmartAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'publicClient': json['publicClient'] == null ? undefined : json['publicClient'],
        'redirectUris': json['redirectUris'] == null ? undefined : json['redirectUris'],
        'webOrigins': json['webOrigins'] == null ? undefined : json['webOrigins'],
        'defaultClientScopes': json['defaultClientScopes'] == null ? undefined : json['defaultClientScopes'],
        'optionalClientScopes': json['optionalClientScopes'] == null ? undefined : json['optionalClientScopes'],
        'smartVersion': json['smartVersion'] == null ? undefined : json['smartVersion'],
        'fhirVersion': json['fhirVersion'] == null ? undefined : json['fhirVersion'],
        'appType': json['appType'] == null ? undefined : json['appType'],
        'clientType': json['clientType'] == null ? undefined : json['clientType'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'publicKey': json['publicKey'] == null ? undefined : json['publicKey'],
        'jwksUri': json['jwksUri'] == null ? undefined : json['jwksUri'],
        'jwksString': json['jwksString'] == null ? undefined : json['jwksString'],
        'systemScopes': json['systemScopes'] == null ? undefined : json['systemScopes'],
        'launchUrl': json['launchUrl'] == null ? undefined : json['launchUrl'],
        'logoUri': json['logoUri'] == null ? undefined : json['logoUri'],
        'tosUri': json['tosUri'] == null ? undefined : json['tosUri'],
        'policyUri': json['policyUri'] == null ? undefined : json['policyUri'],
        'contacts': json['contacts'] == null ? undefined : json['contacts'],
        'serverAccessType': json['serverAccessType'] == null ? undefined : json['serverAccessType'],
        'allowedServerIds': json['allowedServerIds'] == null ? undefined : json['allowedServerIds'],
        'scopeSetId': json['scopeSetId'] == null ? undefined : json['scopeSetId'],
        'requirePkce': json['requirePkce'] == null ? undefined : json['requirePkce'],
        'allowOfflineAccess': json['allowOfflineAccess'] == null ? undefined : json['allowOfflineAccess'],
        'mcpAccessType': json['mcpAccessType'] == null ? undefined : json['mcpAccessType'],
        'allowedMcpServerNames': json['allowedMcpServerNames'] == null ? undefined : json['allowedMcpServerNames'],
        'allowedSkillNames': json['allowedSkillNames'] == null ? undefined : json['allowedSkillNames'],
    };
}

export function UpdateSmartAppRequestToJSON(json: any): UpdateSmartAppRequest {
    return UpdateSmartAppRequestToJSONTyped(json, false);
}

export function UpdateSmartAppRequestToJSONTyped(value?: UpdateSmartAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'enabled': value['enabled'],
        'publicClient': value['publicClient'],
        'redirectUris': value['redirectUris'],
        'webOrigins': value['webOrigins'],
        'defaultClientScopes': value['defaultClientScopes'],
        'optionalClientScopes': value['optionalClientScopes'],
        'smartVersion': value['smartVersion'],
        'fhirVersion': value['fhirVersion'],
        'appType': value['appType'],
        'clientType': value['clientType'],
        'secret': value['secret'],
        'publicKey': value['publicKey'],
        'jwksUri': value['jwksUri'],
        'jwksString': value['jwksString'],
        'systemScopes': value['systemScopes'],
        'launchUrl': value['launchUrl'],
        'logoUri': value['logoUri'],
        'tosUri': value['tosUri'],
        'policyUri': value['policyUri'],
        'contacts': value['contacts'],
        'serverAccessType': value['serverAccessType'],
        'allowedServerIds': value['allowedServerIds'],
        'scopeSetId': value['scopeSetId'],
        'requirePkce': value['requirePkce'],
        'allowOfflineAccess': value['allowOfflineAccess'],
        'mcpAccessType': value['mcpAccessType'],
        'allowedMcpServerNames': value['allowedMcpServerNames'],
        'allowedSkillNames': value['allowedSkillNames'],
    };
}
