/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LdapConfig } from './LdapConfig';
import {
    LdapConfigFromJSON,
    LdapConfigFromJSONTyped,
    LdapConfigToJSON,
    LdapConfigToJSONTyped,
} from './LdapConfig';

/**
 * @export
 * @interface UpdateUserFederationRequest
 */
export interface UpdateUserFederationRequest {
    /**
     * Display name for this federation provider
     * @type {string}
     * @memberof UpdateUserFederationRequest
     */
    name?: string;
    /**
     * @type {LdapConfig}
     * @memberof UpdateUserFederationRequest
     */
    config?: LdapConfig;
}

/**
 * Check if a given object implements the UpdateUserFederationRequest interface.
 */
export function instanceOfUpdateUserFederationRequest(value: object): value is UpdateUserFederationRequest {
    return true;
}

export function UpdateUserFederationRequestFromJSON(json: any): UpdateUserFederationRequest {
    return UpdateUserFederationRequestFromJSONTyped(json, false);
}

export function UpdateUserFederationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserFederationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'config': json['config'] == null ? undefined : LdapConfigFromJSON(json['config']),
    };
}

export function UpdateUserFederationRequestToJSON(json: any): UpdateUserFederationRequest {
    return UpdateUserFederationRequestToJSONTyped(json, false);
}

export function UpdateUserFederationRequestToJSONTyped(value?: UpdateUserFederationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'config': LdapConfigToJSON(value['config']),
    };
}
