/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface UserName
 */
export interface UserName {
    /**
     * Display name
     * @type {string}
     * @memberof UserName
     */
    text: string;
}

/**
 * Check if a given object implements the UserName interface.
 */
export function instanceOfUserName(value: object): value is UserName {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function UserNameFromJSON(json: any): UserName {
    return UserNameFromJSONTyped(json, false);
}

export function UserNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserName {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function UserNameToJSON(json: any): UserName {
    return UserNameToJSONTyped(json, false);
}

export function UserNameToJSONTyped(value?: UserName | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}
