/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface UserFederationProviderResponse
 */
export interface UserFederationProviderResponse {
    /**
     * Component ID
     * @type {string}
     * @memberof UserFederationProviderResponse
     */
    id?: string;
    /**
     * Provider name
     * @type {string}
     * @memberof UserFederationProviderResponse
     */
    name?: string;
    /**
     * Provider type (ldap)
     * @type {string}
     * @memberof UserFederationProviderResponse
     */
    providerId?: string;
    /**
     * Provider class
     * @type {string}
     * @memberof UserFederationProviderResponse
     */
    providerType?: string;
    /**
     * Parent realm ID
     * @type {string}
     * @memberof UserFederationProviderResponse
     */
    parentId?: string;
    /**
     * @type {{ [key: string]: any }}
     * @memberof UserFederationProviderResponse
     */
    config?: { [key: string]: any };
}

/**
 * Check if a given object implements the UserFederationProviderResponse interface.
 */
export function instanceOfUserFederationProviderResponse(value: object): value is UserFederationProviderResponse {
    return true;
}

export function UserFederationProviderResponseFromJSON(json: any): UserFederationProviderResponse {
    return UserFederationProviderResponseFromJSONTyped(json, false);
}

export function UserFederationProviderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFederationProviderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'providerType': json['providerType'] == null ? undefined : json['providerType'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function UserFederationProviderResponseToJSON(json: any): UserFederationProviderResponse {
    return UserFederationProviderResponseToJSONTyped(json, false);
}

export function UserFederationProviderResponseToJSONTyped(value?: UserFederationProviderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'providerId': value['providerId'],
        'providerType': value['providerType'],
        'parentId': value['parentId'],
        'config': value['config'],
    };
}
