/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface UserFederationSyncRequest
 */
export interface UserFederationSyncRequest {
    /**
     * @type {UserFederationSyncRequestActionEnum}
     * @memberof UserFederationSyncRequest
     */
    action: UserFederationSyncRequestActionEnum;
}

/**
 * @export
 */
export const UserFederationSyncRequestActionEnum = {
    TriggerFullSync: 'triggerFullSync',
    TriggerChangedUsersSync: 'triggerChangedUsersSync',
} as const;
export type UserFederationSyncRequestActionEnum = typeof UserFederationSyncRequestActionEnum[keyof typeof UserFederationSyncRequestActionEnum];

/**
 * Check if a given object implements the UserFederationSyncRequest interface.
 */
export function instanceOfUserFederationSyncRequest(value: object): value is UserFederationSyncRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function UserFederationSyncRequestFromJSON(json: any): UserFederationSyncRequest {
    return UserFederationSyncRequestFromJSONTyped(json, false);
}

export function UserFederationSyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFederationSyncRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function UserFederationSyncRequestToJSON(json: any): UserFederationSyncRequest {
    return UserFederationSyncRequestToJSONTyped(json, false);
}

export function UserFederationSyncRequestToJSONTyped(value?: UserFederationSyncRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
    };
}
