/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Input } from './Input';
import {
    InputFromJSON,
    InputFromJSONTyped,
    InputToJSON,
    InputToJSONTyped,
} from './Input';

/**
 * @export
 * @interface Argument
 */
export interface Argument {
    /**
     * A list of possible values for the input. If provided, the user must select one of these values.
     * @type {Array<string> | null}
     * @memberof Argument
     */
    choices?: Array<string> | null;
    /**
     * The default value for the input. This should be a valid value for the input. If you want to provide input examples or guidance, use the placeholder field instead.
     * @type {string}
     * @memberof Argument
     */
    default?: string;
    /**
     * A description of the input, which clients can use to provide context to the user.
     * @type {string}
     * @memberof Argument
     */
    description?: string;
    /**
     * Specifies the input format. Supported values include filepath, which should be interpreted as a file on the user's filesystem.
     * @type {ArgumentFormatEnum}
     * @memberof Argument
     */
    format?: ArgumentFormatEnum;
    /**
     * Whether the argument can be repeated multiple times.
     * @type {boolean}
     * @memberof Argument
     */
    isRepeated?: boolean;
    /**
     * Whether the input is required
     * @type {boolean}
     * @memberof Argument
     */
    isRequired?: boolean;
    /**
     * Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
     * @type {boolean}
     * @memberof Argument
     */
    isSecret?: boolean;
    /**
     * The flag name (for named arguments), including any leading dashes. Empty for positional arguments.
     * @type {string}
     * @memberof Argument
     */
    name?: string;
    /**
     * A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input.
     * @type {string}
     * @memberof Argument
     */
    placeholder?: string;
    /**
     * Argument type: 'positional' or 'named'
     * @type {string}
     * @memberof Argument
     */
    type: string;
    /**
     * The value for the input. If this is not set, the user may be prompted to provide a value. Identifiers wrapped in {curly_braces} will be replaced with the corresponding properties from the input variables map.
     * @type {string}
     * @memberof Argument
     */
    value?: string;
    /**
     * An identifier for positional arguments. Used in transport URL variable substitution.
     * @type {string}
     * @memberof Argument
     */
    valueHint?: string;
    /**
     * A map of variable names to their values. Keys in the input value that are wrapped in {curly_braces} will be replaced with the corresponding variable values.
     * @type {{ [key: string]: Input }}
     * @memberof Argument
     */
    variables?: { [key: string]: Input };
}

/**
 * @export
 */
export const ArgumentFormatEnum = {
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Filepath: 'filepath',
} as const;
export type ArgumentFormatEnum = typeof ArgumentFormatEnum[keyof typeof ArgumentFormatEnum];

/**
 * Check if a given object implements the Argument interface.
 */
export function instanceOfArgument(value: object): value is Argument {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ArgumentFromJSON(json: any): Argument {
    return ArgumentFromJSONTyped(json, false);
}

export function ArgumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Argument {
    if (json == null) {
        return json;
    }
    return {
        
        'choices': json['choices'] == null ? undefined : json['choices'],
        'default': json['default'] == null ? undefined : json['default'],
        'description': json['description'] == null ? undefined : json['description'],
        'format': json['format'] == null ? undefined : json['format'],
        'isRepeated': json['isRepeated'] == null ? undefined : json['isRepeated'],
        'isRequired': json['isRequired'] == null ? undefined : json['isRequired'],
        'isSecret': json['isSecret'] == null ? undefined : json['isSecret'],
        'name': json['name'] == null ? undefined : json['name'],
        'placeholder': json['placeholder'] == null ? undefined : json['placeholder'],
        'type': json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'valueHint': json['valueHint'] == null ? undefined : json['valueHint'],
        'variables': json['variables'] == null ? undefined : json['variables'],
    };
}

export function ArgumentToJSON(json: any): Argument {
    return ArgumentToJSONTyped(json, false);
}

export function ArgumentToJSONTyped(value?: Argument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'choices': value['choices'],
        'default': value['default'],
        'description': value['description'],
        'format': value['format'],
        'isRepeated': value['isRepeated'],
        'isRequired': value['isRequired'],
        'isSecret': value['isSecret'],
        'name': value['name'],
        'placeholder': value['placeholder'],
        'type': value['type'],
        'value': value['value'],
        'valueHint': value['valueHint'],
        'variables': value['variables'],
    };
}
