/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface HealthBody
 */
export interface HealthBody {
    /**
     * GitHub OAuth App Client ID
     * @type {string}
     * @memberof HealthBody
     */
    githubClientId?: string;
    /**
     * Health status
     * @type {string}
     * @memberof HealthBody
     */
    status: string;
}

/**
 * Check if a given object implements the HealthBody interface.
 */
export function instanceOfHealthBody(value: object): value is HealthBody {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthBodyFromJSON(json: any): HealthBody {
    return HealthBodyFromJSONTyped(json, false);
}

export function HealthBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthBody {
    if (json == null) {
        return json;
    }
    return {
        
        'githubClientId': json['github_client_id'] == null ? undefined : json['github_client_id'],
        'status': json['status'],
    };
}

export function HealthBodyToJSON(json: any): HealthBody {
    return HealthBodyToJSONTyped(json, false);
}

export function HealthBodyToJSONTyped(value?: HealthBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'github_client_id': value['githubClientId'],
        'status': value['status'],
    };
}
