/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface Input
 */
export interface Input {
    /**
     * A list of possible values for the input. If provided, the user must select one of these values.
     * @type {Array<string> | null}
     * @memberof Input
     */
    choices?: Array<string> | null;
    /**
     * The default value for the input. This should be a valid value for the input. If you want to provide input examples or guidance, use the placeholder field instead.
     * @type {string}
     * @memberof Input
     */
    default?: string;
    /**
     * A description of the input, which clients can use to provide context to the user.
     * @type {string}
     * @memberof Input
     */
    description?: string;
    /**
     * Specifies the input format. Supported values include filepath, which should be interpreted as a file on the user's filesystem.
     * @type {InputFormatEnum}
     * @memberof Input
     */
    format?: InputFormatEnum;
    /**
     * Whether the input is required
     * @type {boolean}
     * @memberof Input
     */
    isRequired?: boolean;
    /**
     * Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
     * @type {boolean}
     * @memberof Input
     */
    isSecret?: boolean;
    /**
     * A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input.
     * @type {string}
     * @memberof Input
     */
    placeholder?: string;
    /**
     * The value for the input. If this is not set, the user may be prompted to provide a value. Identifiers wrapped in {curly_braces} will be replaced with the corresponding properties from the input variables map.
     * @type {string}
     * @memberof Input
     */
    value?: string;
}

/**
 * @export
 */
export const InputFormatEnum = {
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Filepath: 'filepath',
} as const;
export type InputFormatEnum = typeof InputFormatEnum[keyof typeof InputFormatEnum];

/**
 * Check if a given object implements the Input interface.
 */
export function instanceOfInput(value: object): value is Input {
    return true;
}

export function InputFromJSON(json: any): Input {
    return InputFromJSONTyped(json, false);
}

export function InputFromJSONTyped(json: any, ignoreDiscriminator: boolean): Input {
    if (json == null) {
        return json;
    }
    return {
        
        'choices': json['choices'] == null ? undefined : json['choices'],
        'default': json['default'] == null ? undefined : json['default'],
        'description': json['description'] == null ? undefined : json['description'],
        'format': json['format'] == null ? undefined : json['format'],
        'isRequired': json['isRequired'] == null ? undefined : json['isRequired'],
        'isSecret': json['isSecret'] == null ? undefined : json['isSecret'],
        'placeholder': json['placeholder'] == null ? undefined : json['placeholder'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function InputToJSON(json: any): Input {
    return InputToJSONTyped(json, false);
}

export function InputToJSONTyped(value?: Input | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'choices': value['choices'],
        'default': value['default'],
        'description': value['description'],
        'format': value['format'],
        'isRequired': value['isRequired'],
        'isSecret': value['isSecret'],
        'placeholder': value['placeholder'],
        'value': value['value'],
    };
}
