/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * Number of items in current page
     * @type {number}
     * @memberof Metadata
     */
    count: number;
    /**
     * Pagination cursor for retrieving the next page of results. Use this exact value in the cursor query parameter of your next request.
     * @type {string}
     * @memberof Metadata
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the Metadata interface.
 */
export function instanceOfMetadata(value: object): value is Metadata {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function MetadataFromJSON(json: any): Metadata {
    return MetadataFromJSONTyped(json, false);
}

export function MetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metadata {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
    };
}

export function MetadataToJSON(json: any): Metadata {
    return MetadataToJSONTyped(json, false);
}

export function MetadataToJSONTyped(value?: Metadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'nextCursor': value['nextCursor'],
    };
}
