/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface OIDCTokenExchangeInputBody
 */
export interface OIDCTokenExchangeInputBody {
    /**
     * OIDC ID token from any provider
     * @type {string}
     * @memberof OIDCTokenExchangeInputBody
     */
    oidcToken: string;
}

/**
 * Check if a given object implements the OIDCTokenExchangeInputBody interface.
 */
export function instanceOfOIDCTokenExchangeInputBody(value: object): value is OIDCTokenExchangeInputBody {
    if (!('oidcToken' in value) || value['oidcToken'] === undefined) return false;
    return true;
}

export function OIDCTokenExchangeInputBodyFromJSON(json: any): OIDCTokenExchangeInputBody {
    return OIDCTokenExchangeInputBodyFromJSONTyped(json, false);
}

export function OIDCTokenExchangeInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OIDCTokenExchangeInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        'oidcToken': json['oidc_token'],
    };
}

export function OIDCTokenExchangeInputBodyToJSON(json: any): OIDCTokenExchangeInputBody {
    return OIDCTokenExchangeInputBodyToJSONTyped(json, false);
}

export function OIDCTokenExchangeInputBodyToJSONTyped(value?: OIDCTokenExchangeInputBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oidc_token': value['oidcToken'],
    };
}
