/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Argument } from './Argument';
import {
    ArgumentFromJSON,
    ArgumentFromJSONTyped,
    ArgumentToJSON,
    ArgumentToJSONTyped,
} from './Argument';
import type { KeyValueInput } from './KeyValueInput';
import {
    KeyValueInputFromJSON,
    KeyValueInputFromJSONTyped,
    KeyValueInputToJSON,
    KeyValueInputToJSONTyped,
} from './KeyValueInput';
import type { Transport } from './Transport';
import {
    TransportFromJSON,
    TransportFromJSONTyped,
    TransportToJSON,
    TransportToJSONTyped,
} from './Transport';

/**
 * @export
 * @interface Package
 */
export interface Package {
    /**
     * A mapping of environment variables to be set when running the package.
     * @type {Array<KeyValueInput> | null}
     * @memberof Package
     */
    environmentVariables?: Array<KeyValueInput> | null;
    /**
     * SHA-256 hash of the package file for integrity verification. Required for MCPB packages and optional for other package types. Authors are responsible for generating correct SHA-256 hashes when creating server.json. If present, MCP clients must validate the downloaded file matches the hash before running packages to ensure file integrity.
     * @type {string}
     * @memberof Package
     */
    fileSha256?: string;
    /**
     * Package identifier - either a package name (for registries) or URL (for direct downloads)
     * @type {string}
     * @memberof Package
     */
    identifier: string;
    /**
     * A list of arguments to be passed to the package's binary.
     * @type {Array<Argument> | null}
     * @memberof Package
     */
    packageArguments?: Array<Argument> | null;
    /**
     * Base URL of the package registry
     * @type {string}
     * @memberof Package
     */
    registryBaseUrl?: string;
    /**
     * Registry type indicating how to download packages (e.g., 'npm', 'pypi', 'oci', 'nuget', 'mcpb')
     * @type {string}
     * @memberof Package
     */
    registryType: string;
    /**
     * A list of arguments to be passed to the package's runtime command (such as docker or npx). The runtimeHint field should be provided when runtimeArguments are present.
     * @type {Array<Argument> | null}
     * @memberof Package
     */
    runtimeArguments?: Array<Argument> | null;
    /**
     * A hint to help clients determine the appropriate runtime for the package. This field should be provided when runtimeArguments are present.
     * @type {string}
     * @memberof Package
     */
    runtimeHint?: string;
    /**
     * Transport protocol configuration for the package
     * @type {Transport}
     * @memberof Package
     */
    transport: Transport;
    /**
     * Package version. Must be a specific version. Version ranges are rejected (e.g., '^1.2.3', '~1.2.3', '>=1.2.3', '1.x', '1.*').
     * @type {string}
     * @memberof Package
     */
    version?: string;
}

/**
 * Check if a given object implements the Package interface.
 */
export function instanceOfPackage(value: object): value is Package {
    if (!('transport' in value) || value['transport'] === undefined) return false;
    if (!('registryType' in value) || value['registryType'] === undefined) return false;
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    return true;
}

export function PackageFromJSON(json: any): Package {
    return PackageFromJSONTyped(json, false);
}

export function PackageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Package {
    if (json == null) {
        return json;
    }
    return {
        
        'environmentVariables': json['environmentVariables'] == null ? undefined : ((json['environmentVariables'] as Array<any>).map(KeyValueInputFromJSON)),
        'fileSha256': json['fileSha256'] == null ? undefined : json['fileSha256'],
        'identifier': json['identifier'],
        'packageArguments': json['packageArguments'] == null ? undefined : ((json['packageArguments'] as Array<any>).map(ArgumentFromJSON)),
        'registryBaseUrl': json['registryBaseUrl'] == null ? undefined : json['registryBaseUrl'],
        'registryType': json['registryType'],
        'runtimeArguments': json['runtimeArguments'] == null ? undefined : ((json['runtimeArguments'] as Array<any>).map(ArgumentFromJSON)),
        'runtimeHint': json['runtimeHint'] == null ? undefined : json['runtimeHint'],
        'transport': TransportFromJSON(json['transport']),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function PackageToJSON(json: any): Package {
    return PackageToJSONTyped(json, false);
}

export function PackageToJSONTyped(value?: Package | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'environmentVariables': value['environmentVariables'] == null ? undefined : ((value['environmentVariables'] as Array<any>).map(KeyValueInputToJSON)),
        'fileSha256': value['fileSha256'],
        'identifier': value['identifier'],
        'packageArguments': value['packageArguments'] == null ? undefined : ((value['packageArguments'] as Array<any>).map(ArgumentToJSON)),
        'registryBaseUrl': value['registryBaseUrl'],
        'registryType': value['registryType'],
        'runtimeArguments': value['runtimeArguments'] == null ? undefined : ((value['runtimeArguments'] as Array<any>).map(ArgumentToJSON)),
        'runtimeHint': value['runtimeHint'],
        'transport': TransportToJSON(value['transport']),
        'version': value['version'],
    };
}
