/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface PingBody
 */
export interface PingBody {
    /**
     * Ping response
     * @type {boolean}
     * @memberof PingBody
     */
    pong: boolean;
}

/**
 * Check if a given object implements the PingBody interface.
 */
export function instanceOfPingBody(value: object): value is PingBody {
    if (!('pong' in value) || value['pong'] === undefined) return false;
    return true;
}

export function PingBodyFromJSON(json: any): PingBody {
    return PingBodyFromJSONTyped(json, false);
}

export function PingBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingBody {
    if (json == null) {
        return json;
    }
    return {
        
        'pong': json['pong'],
    };
}

export function PingBodyToJSON(json: any): PingBody {
    return PingBodyToJSONTyped(json, false);
}

export function PingBodyToJSONTyped(value?: PingBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pong': value['pong'],
    };
}
