/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegistryExtensions } from './RegistryExtensions';
import {
    RegistryExtensionsFromJSON,
    RegistryExtensionsFromJSONTyped,
    RegistryExtensionsToJSON,
    RegistryExtensionsToJSONTyped,
} from './RegistryExtensions';

/**
 * @export
 * @interface ResponseMeta
 */
export interface ResponseMeta {
    /**
     * Official MCP registry metadata
     * @type {RegistryExtensions}
     * @memberof ResponseMeta
     */
    io_modelcontextprotocol_registry_official?: RegistryExtensions;
}

/**
 * Check if a given object implements the ResponseMeta interface.
 */
export function instanceOfResponseMeta(value: object): value is ResponseMeta {
    return true;
}

export function ResponseMetaFromJSON(json: any): ResponseMeta {
    return ResponseMetaFromJSONTyped(json, false);
}

export function ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'io_modelcontextprotocol_registry_official': json['io.modelcontextprotocol.registry/official'] == null ? undefined : RegistryExtensionsFromJSON(json['io.modelcontextprotocol.registry/official']),
    };
}

export function ResponseMetaToJSON(json: any): ResponseMeta {
    return ResponseMetaToJSONTyped(json, false);
}

export function ResponseMetaToJSONTyped(value?: ResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'io.modelcontextprotocol.registry/official': RegistryExtensionsToJSON(value['io_modelcontextprotocol_registry_official']),
    };
}
