/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { ServerJSON } from './ServerJSON';
import {
    ServerJSONFromJSON,
    ServerJSONFromJSONTyped,
    ServerJSONToJSON,
    ServerJSONToJSONTyped,
} from './ServerJSON';

/**
 * @export
 * @interface ServerResponse
 */
export interface ServerResponse {
    /**
     * Registry-managed metadata
     * @type {ResponseMeta}
     * @memberof ServerResponse
     */
    meta: ResponseMeta;
    /**
     * Server configuration and metadata
     * @type {ServerJSON}
     * @memberof ServerResponse
     */
    server: ServerJSON;
}

/**
 * Check if a given object implements the ServerResponse interface.
 */
export function instanceOfServerResponse(value: object): value is ServerResponse {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('server' in value) || value['server'] === undefined) return false;
    return true;
}

export function ServerResponseFromJSON(json: any): ServerResponse {
    return ServerResponseFromJSONTyped(json, false);
}

export function ServerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ResponseMetaFromJSON(json['_meta']),
        'server': ServerJSONFromJSON(json['server']),
    };
}

export function ServerResponseToJSON(json: any): ServerResponse {
    return ServerResponseToJSONTyped(json, false);
}

export function ServerResponseToJSONTyped(value?: ServerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_meta': ResponseMetaToJSON(value['meta']),
        'server': ServerJSONToJSON(value['server']),
    };
}
