/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Input } from './Input';
import {
    InputFromJSON,
    InputFromJSONTyped,
    InputToJSON,
    InputToJSONTyped,
} from './Input';
import type { KeyValueInput } from './KeyValueInput';
import {
    KeyValueInputFromJSON,
    KeyValueInputFromJSONTyped,
    KeyValueInputToJSON,
    KeyValueInputToJSONTyped,
} from './KeyValueInput';

/**
 * @export
 * @interface Transport
 */
export interface Transport {
    /**
     * HTTP headers for streamable-http or sse transports
     * @type {Array<KeyValueInput> | null}
     * @memberof Transport
     */
    headers?: Array<KeyValueInput> | null;
    /**
     * Transport type (stdio, streamable-http, or sse)
     * @type {string}
     * @memberof Transport
     */
    type: string;
    /**
     * URL for streamable-http or sse transports
     * @type {string}
     * @memberof Transport
     */
    url?: string;
    /**
     * Variables for URL templating in remote transports
     * @type {{ [key: string]: Input }}
     * @memberof Transport
     */
    variables?: { [key: string]: Input };
}

/**
 * Check if a given object implements the Transport interface.
 */
export function instanceOfTransport(value: object): value is Transport {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TransportFromJSON(json: any): Transport {
    return TransportFromJSONTyped(json, false);
}

export function TransportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transport {
    if (json == null) {
        return json;
    }
    return {
        
        'headers': json['headers'] == null ? undefined : ((json['headers'] as Array<any>).map(KeyValueInputFromJSON)),
        'type': json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'variables': json['variables'] == null ? undefined : json['variables'],
    };
}

export function TransportToJSON(json: any): Transport {
    return TransportToJSONTyped(json, false);
}

export function TransportToJSONTyped(value?: Transport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headers': value['headers'] == null ? undefined : ((value['headers'] as Array<any>).map(KeyValueInputToJSON)),
        'type': value['type'],
        'url': value['url'],
        'variables': value['variables'],
    };
}
