/* tslint:disable */
/* eslint-disable */
/**
 * Official MCP Registry
 * A community driven registry service for Model Context Protocol (MCP) servers.

[GitHub repository](https://github.com/modelcontextprotocol/registry) | [Documentation](https://github.com/modelcontextprotocol/registry/tree/main/docs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * @export
 * @interface VersionBody
 */
export interface VersionBody {
    /**
     * Build timestamp
     * @type {string}
     * @memberof VersionBody
     */
    buildTime: string;
    /**
     * Git commit SHA
     * @type {string}
     * @memberof VersionBody
     */
    gitCommit: string;
    /**
     * Application version
     * @type {string}
     * @memberof VersionBody
     */
    version: string;
}

/**
 * Check if a given object implements the VersionBody interface.
 */
export function instanceOfVersionBody(value: object): value is VersionBody {
    if (!('buildTime' in value) || value['buildTime'] === undefined) return false;
    if (!('gitCommit' in value) || value['gitCommit'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function VersionBodyFromJSON(json: any): VersionBody {
    return VersionBodyFromJSONTyped(json, false);
}

export function VersionBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionBody {
    if (json == null) {
        return json;
    }
    return {
        
        'buildTime': json['build_time'],
        'gitCommit': json['git_commit'],
        'version': json['version'],
    };
}

export function VersionBodyToJSON(json: any): VersionBody {
    return VersionBodyToJSONTyped(json, false);
}

export function VersionBodyToJSONTyped(value?: VersionBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'build_time': value['buildTime'],
        'git_commit': value['gitCommit'],
        'version': value['version'],
    };
}
