/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminAuditAnalyticsResponse,
  AdminAuditEventsResponse,
} from '../models/index';
import {
    AdminAuditAnalyticsResponseFromJSON,
    AdminAuditAnalyticsResponseToJSON,
    AdminAuditEventsResponseFromJSON,
    AdminAuditEventsResponseToJSON,
} from '../models/index';

export interface GetMonitoringAdminAuditEventsStreamRequest {
    token?: string;
    authorization?: string;
}

export interface GetMonitoringAdminAuditAnalyticsStreamRequest {
    token?: string;
    authorization?: string;
}

export interface GetMonitoringAdminAuditEventsRequest {
    limit?: string;
    action?: string;
    resource?: string;
    actor?: string;
    success?: string;
    since?: string;
    authorization?: string;
}

export interface GetMonitoringAdminAuditAnalyticsRequest {
    authorization?: string;
}

export interface GetMonitoringAdminAuditEventsExportRequest {
    authorization?: string;
}

/**
 * 
 */
export class AdminAuditMonitoringApi extends runtime.BaseAPI {

    /**
     * SSE stream of real-time admin audit events (mutations only)
     * Admin Audit Events Stream
     */
    async getMonitoringAdminAuditEventsStreamRaw(requestParameters?: GetMonitoringAdminAuditEventsStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/admin-audit/events/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<object>(response);
    }

    /**
     * SSE stream of real-time admin audit events (mutations only)
     * Admin Audit Events Stream
     */
    async getMonitoringAdminAuditEventsStream(requestParameters?: GetMonitoringAdminAuditEventsStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMonitoringAdminAuditEventsStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * SSE stream of real-time admin audit analytics updates
     * Admin Audit Analytics Stream
     */
    async getMonitoringAdminAuditAnalyticsStreamRaw(requestParameters?: GetMonitoringAdminAuditAnalyticsStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/admin-audit/analytics/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<object>(response);
    }

    /**
     * SSE stream of real-time admin audit analytics updates
     * Admin Audit Analytics Stream
     */
    async getMonitoringAdminAuditAnalyticsStream(requestParameters?: GetMonitoringAdminAuditAnalyticsStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMonitoringAdminAuditAnalyticsStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve recent admin audit events with optional filtering by action, resource, actor, and success
     * Get Admin Audit Events
     */
    async getMonitoringAdminAuditEventsRaw(requestParameters?: GetMonitoringAdminAuditEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminAuditEventsResponse>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }
        if (requestParameters['resource'] != null) {
            queryParameters['resource'] = requestParameters['resource'];
        }
        if (requestParameters['actor'] != null) {
            queryParameters['actor'] = requestParameters['actor'];
        }
        if (requestParameters['success'] != null) {
            queryParameters['success'] = requestParameters['success'];
        }
        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/admin-audit/events`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminAuditEventsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve recent admin audit events with optional filtering by action, resource, actor, and success
     * Get Admin Audit Events
     */
    async getMonitoringAdminAuditEvents(requestParameters?: GetMonitoringAdminAuditEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminAuditEventsResponse> {
        const response = await this.getMonitoringAdminAuditEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current admin audit analytics (last 24 hours)
     * Get Admin Audit Analytics
     */
    async getMonitoringAdminAuditAnalyticsRaw(requestParameters?: GetMonitoringAdminAuditAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminAuditAnalyticsResponse>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/admin-audit/analytics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminAuditAnalyticsResponseFromJSON(jsonValue));
    }

    /**
     * Get current admin audit analytics (last 24 hours)
     * Get Admin Audit Analytics
     */
    async getMonitoringAdminAuditAnalytics(requestParameters?: GetMonitoringAdminAuditAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminAuditAnalyticsResponse> {
        const response = await this.getMonitoringAdminAuditAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download the full admin audit log as newline-delimited JSON (JSONL)
     * Export Admin Audit Log
     */
    async getMonitoringAdminAuditEventsExportRaw(requestParameters?: GetMonitoringAdminAuditEventsExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/admin-audit/events/export`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download the full admin audit log as newline-delimited JSON (JSONL)
     * Export Admin Audit Log
     */
    async getMonitoringAdminAuditEventsExport(requestParameters?: GetMonitoringAdminAuditEventsExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        const response = await this.getMonitoringAdminAuditEventsExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
