/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAdminAiToolsSkills200Response,
  GetAdminAiToolsSkills200ResponseSkillsInner,
  GetAdminAiToolsSkillsRegistryBrowse200Response,
  PostAdminAiToolsSkillsRegistryInstallRequest,
  PostAdminAiToolsSkillsRequest,
} from '../models/index';
import {
    GetAdminAiToolsSkills200ResponseFromJSON,
    GetAdminAiToolsSkills200ResponseToJSON,
    GetAdminAiToolsSkills200ResponseSkillsInnerFromJSON,
    GetAdminAiToolsSkills200ResponseSkillsInnerToJSON,
    GetAdminAiToolsSkillsRegistryBrowse200ResponseFromJSON,
    GetAdminAiToolsSkillsRegistryBrowse200ResponseToJSON,
    PostAdminAiToolsSkillsRegistryInstallRequestFromJSON,
    PostAdminAiToolsSkillsRegistryInstallRequestToJSON,
    PostAdminAiToolsSkillsRequestFromJSON,
    PostAdminAiToolsSkillsRequestToJSON,
} from '../models/index';

export interface PostAdminAiToolsSkillsOperationRequest {
    postAdminAiToolsSkillsRequest: PostAdminAiToolsSkillsRequest;
}

export interface DeleteAdminAiToolsSkillsByNameRequest {
    name: string;
}

export interface GetAdminAiToolsSkillsRegistryBrowseRequest {
    limit?: string;
}

export interface GetAdminAiToolsSkillsRegistrySearchRequest {
    q?: string;
    limit?: string;
}

export interface PostAdminAiToolsSkillsRegistryInstallOperationRequest {
    postAdminAiToolsSkillsRegistryInstallRequest: PostAdminAiToolsSkillsRegistryInstallRequest;
}

/**
 * 
 */
export class AiToolsApi extends runtime.BaseAPI {

    /**
     * Get list of installed AI skills
     * List installed skills
     */
    async getAdminAiToolsSkillsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminAiToolsSkills200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/ai-tools/skills/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminAiToolsSkills200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of installed AI skills
     * List installed skills
     */
    async getAdminAiToolsSkills(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminAiToolsSkills200Response> {
        const response = await this.getAdminAiToolsSkillsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Install a new AI skill package
     * Add a skill
     */
    async postAdminAiToolsSkillsRaw(requestParameters: PostAdminAiToolsSkillsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminAiToolsSkills200ResponseSkillsInner>> {
        if (requestParameters['postAdminAiToolsSkillsRequest'] == null) {
            throw new runtime.RequiredError(
                'postAdminAiToolsSkillsRequest',
                'Required parameter "postAdminAiToolsSkillsRequest" was null or undefined when calling postAdminAiToolsSkills().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/ai-tools/skills/`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAdminAiToolsSkillsRequestToJSON(requestParameters['postAdminAiToolsSkillsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminAiToolsSkills200ResponseSkillsInnerFromJSON(jsonValue));
    }

    /**
     * Install a new AI skill package
     * Add a skill
     */
    async postAdminAiToolsSkills(requestParameters: PostAdminAiToolsSkillsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminAiToolsSkills200ResponseSkillsInner> {
        const response = await this.postAdminAiToolsSkillsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove an installed skill
     * Delete a skill
     */
    async deleteAdminAiToolsSkillsByNameRaw(requestParameters: DeleteAdminAiToolsSkillsByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteAdminAiToolsSkillsByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/ai-tools/skills/{name}`;
        urlPath = urlPath.replace(`{name}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove an installed skill
     * Delete a skill
     */
    async deleteAdminAiToolsSkillsByName(requestParameters: DeleteAdminAiToolsSkillsByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        const response = await this.deleteAdminAiToolsSkillsByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Browse popular skills from the skills.sh public registry
     * Browse skills.sh registry
     */
    async getAdminAiToolsSkillsRegistryBrowseRaw(requestParameters?: GetAdminAiToolsSkillsRegistryBrowseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminAiToolsSkillsRegistryBrowse200Response>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/ai-tools/skills/registry/browse`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminAiToolsSkillsRegistryBrowse200ResponseFromJSON(jsonValue));
    }

    /**
     * Browse popular skills from the skills.sh public registry
     * Browse skills.sh registry
     */
    async getAdminAiToolsSkillsRegistryBrowse(requestParameters?: GetAdminAiToolsSkillsRegistryBrowseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminAiToolsSkillsRegistryBrowse200Response> {
        const response = await this.getAdminAiToolsSkillsRegistryBrowseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search skills from the skills.sh public registry by keyword
     * Search skills.sh registry
     */
    async getAdminAiToolsSkillsRegistrySearchRaw(requestParameters?: GetAdminAiToolsSkillsRegistrySearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminAiToolsSkillsRegistryBrowse200Response>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/ai-tools/skills/registry/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminAiToolsSkillsRegistryBrowse200ResponseFromJSON(jsonValue));
    }

    /**
     * Search skills from the skills.sh public registry by keyword
     * Search skills.sh registry
     */
    async getAdminAiToolsSkillsRegistrySearch(requestParameters?: GetAdminAiToolsSkillsRegistrySearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminAiToolsSkillsRegistryBrowse200Response> {
        const response = await this.getAdminAiToolsSkillsRegistrySearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Install a skill from the skills.sh public registry
     * Install from skills.sh
     */
    async postAdminAiToolsSkillsRegistryInstallRaw(requestParameters: PostAdminAiToolsSkillsRegistryInstallOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['postAdminAiToolsSkillsRegistryInstallRequest'] == null) {
            throw new runtime.RequiredError(
                'postAdminAiToolsSkillsRegistryInstallRequest',
                'Required parameter "postAdminAiToolsSkillsRegistryInstallRequest" was null or undefined when calling postAdminAiToolsSkillsRegistryInstall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/ai-tools/skills/registry/install`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAdminAiToolsSkillsRegistryInstallRequestToJSON(requestParameters['postAdminAiToolsSkillsRegistryInstallRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Install a skill from the skills.sh public registry
     * Install from skills.sh
     */
    async postAdminAiToolsSkillsRegistryInstall(requestParameters: PostAdminAiToolsSkillsRegistryInstallOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        const response = await this.postAdminAiToolsSkillsRegistryInstallRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
