/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.6-alpha.202604171740.60503a70
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppStoreListResponse,
  AppStorePublishResponse,
  AppStoreToggleResponse,
  PublishedApp,
} from '../models/index';
import {
    AppStoreListResponseFromJSON,
    AppStoreListResponseToJSON,
    AppStorePublishResponseFromJSON,
    AppStorePublishResponseToJSON,
    AppStoreToggleResponseFromJSON,
    AppStoreToggleResponseToJSON,
    PublishedAppFromJSON,
    PublishedAppToJSON,
} from '../models/index';

export interface PostAdminAppStoreByAppIdHideRequest {
    appId: string;
}

export interface PostAdminAppStoreByAppIdShowRequest {
    appId: string;
}

export interface PostAdminAppStorePublishRequest {
    publishedApp: PublishedApp;
}

export interface PostAdminAppStoreByAppIdUnpublishRequest {
    appId: string;
}

/**
 * 
 */
export class AppStoreApi extends runtime.BaseAPI {

    /**
     * List all discovered and published SMART apps with their visibility status
     * List App Store Apps
     */
    async getAdminAppStoreRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppStoreListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/app-store/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppStoreListResponseFromJSON(jsonValue));
    }

    /**
     * List all discovered and published SMART apps with their visibility status
     * List App Store Apps
     */
    async getAdminAppStore(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppStoreListResponse> {
        const response = await this.getAdminAppStoreRaw(initOverrides);
        return await response.value();
    }

    /**
     * Hide a SMART app from the public app store page
     * Hide App from Store
     */
    async postAdminAppStoreByAppIdHideRaw(requestParameters: PostAdminAppStoreByAppIdHideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppStoreToggleResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling postAdminAppStoreByAppIdHide().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/app-store/{appId}/hide`;
        urlPath = urlPath.replace(`{appId}`, encodeURIComponent(String(requestParameters['appId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppStoreToggleResponseFromJSON(jsonValue));
    }

    /**
     * Hide a SMART app from the public app store page
     * Hide App from Store
     */
    async postAdminAppStoreByAppIdHide(requestParameters: PostAdminAppStoreByAppIdHideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppStoreToggleResponse> {
        const response = await this.postAdminAppStoreByAppIdHideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show a previously hidden SMART app in the public app store page
     * Show App in Store
     */
    async postAdminAppStoreByAppIdShowRaw(requestParameters: PostAdminAppStoreByAppIdShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppStoreToggleResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling postAdminAppStoreByAppIdShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/app-store/{appId}/show`;
        urlPath = urlPath.replace(`{appId}`, encodeURIComponent(String(requestParameters['appId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppStoreToggleResponseFromJSON(jsonValue));
    }

    /**
     * Show a previously hidden SMART app in the public app store page
     * Show App in Store
     */
    async postAdminAppStoreByAppIdShow(requestParameters: PostAdminAppStoreByAppIdShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppStoreToggleResponse> {
        const response = await this.postAdminAppStoreByAppIdShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish a registered SMART app to the public app store
     * Publish App to Store
     */
    async postAdminAppStorePublishRaw(requestParameters: PostAdminAppStorePublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppStorePublishResponse>> {
        if (requestParameters['publishedApp'] == null) {
            throw new runtime.RequiredError(
                'publishedApp',
                'Required parameter "publishedApp" was null or undefined when calling postAdminAppStorePublish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/app-store/publish`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PublishedAppToJSON(requestParameters['publishedApp']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppStorePublishResponseFromJSON(jsonValue));
    }

    /**
     * Publish a registered SMART app to the public app store
     * Publish App to Store
     */
    async postAdminAppStorePublish(requestParameters: PostAdminAppStorePublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppStorePublishResponse> {
        const response = await this.postAdminAppStorePublishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a registered SMART app from the public app store
     * Unpublish App from Store
     */
    async postAdminAppStoreByAppIdUnpublishRaw(requestParameters: PostAdminAppStoreByAppIdUnpublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppStorePublishResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling postAdminAppStoreByAppIdUnpublish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/app-store/{appId}/unpublish`;
        urlPath = urlPath.replace(`{appId}`, encodeURIComponent(String(requestParameters['appId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppStorePublishResponseFromJSON(jsonValue));
    }

    /**
     * Remove a registered SMART app from the public app store
     * Unpublish App from Store
     */
    async postAdminAppStoreByAppIdUnpublish(requestParameters: PostAdminAppStoreByAppIdUnpublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppStorePublishResponse> {
        const response = await this.postAdminAppStoreByAppIdUnpublishRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
