/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604142009.f75bd474
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthConfigResponse,
  ClientRegistrationRequest,
  ClientRegistrationResponse,
  PublicIdentityProvider,
  TokenRequest,
  TokenResponse,
  UserInfoResponse,
} from '../models/index';
import {
    AuthConfigResponseFromJSON,
    AuthConfigResponseToJSON,
    ClientRegistrationRequestFromJSON,
    ClientRegistrationRequestToJSON,
    ClientRegistrationResponseFromJSON,
    ClientRegistrationResponseToJSON,
    PublicIdentityProviderFromJSON,
    PublicIdentityProviderToJSON,
    TokenRequestFromJSON,
    TokenRequestToJSON,
    TokenResponseFromJSON,
    TokenResponseToJSON,
    UserInfoResponseFromJSON,
    UserInfoResponseToJSON,
} from '../models/index';

export interface GetAuthAuthorizeRequest {
    responseType?: string;
    clientId?: string;
    redirectUri?: string;
    scope?: string;
    state?: string;
    codeChallenge?: string;
    codeChallengeMethod?: string;
    aud?: string;
    resource?: string;
    launch?: string;
    authorizationDetails?: string;
    kcIdpHint?: string;
}

export interface GetAuthLoginRequest {
    clientId?: string;
    redirectUri?: string;
    scope?: string;
    state?: string;
    codeChallenge?: string;
    codeChallengeMethod?: string;
    authorizationDetails?: string;
}

export interface GetAuthLogoutRequest {
    postLogoutRedirectUri?: string;
    idTokenHint?: string;
    clientId?: string;
}

export interface PostAuthTokenRequest {
    tokenRequest: TokenRequest;
}

export interface PostAuthIntrospectRequest {
    body: { [key: string]: string };
}

export interface GetAuthUserinfoRequest {
    authorization: string;
}

export interface PostAuthRegisterRequest {
    clientRegistrationRequest: ClientRegistrationRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Returns the current authentication configuration status
     * Get authentication configuration
     */
    async getAuthConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthConfigResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/config`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthConfigResponseFromJSON(jsonValue));
    }

    /**
     * Returns the current authentication configuration status
     * Get authentication configuration
     */
    async getAuthConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthConfigResponse> {
        const response = await this.getAuthConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Redirects to Keycloak authorization endpoint for OAuth flow with support for authorization details
     * OAuth Authorization Endpoint
     */
    async getAuthAuthorizeRaw(requestParameters?: GetAuthAuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['responseType'] != null) {
            queryParameters['response_type'] = requestParameters['responseType'];
        }
        if (requestParameters['clientId'] != null) {
            queryParameters['client_id'] = requestParameters['clientId'];
        }
        if (requestParameters['redirectUri'] != null) {
            queryParameters['redirect_uri'] = requestParameters['redirectUri'];
        }
        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }
        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }
        if (requestParameters['codeChallenge'] != null) {
            queryParameters['code_challenge'] = requestParameters['codeChallenge'];
        }
        if (requestParameters['codeChallengeMethod'] != null) {
            queryParameters['code_challenge_method'] = requestParameters['codeChallengeMethod'];
        }
        if (requestParameters['aud'] != null) {
            queryParameters['aud'] = requestParameters['aud'];
        }
        if (requestParameters['resource'] != null) {
            queryParameters['resource'] = requestParameters['resource'];
        }
        if (requestParameters['launch'] != null) {
            queryParameters['launch'] = requestParameters['launch'];
        }
        if (requestParameters['authorizationDetails'] != null) {
            queryParameters['authorization_details'] = requestParameters['authorizationDetails'];
        }
        if (requestParameters['kcIdpHint'] != null) {
            queryParameters['kc_idp_hint'] = requestParameters['kcIdpHint'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/authorize`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Redirects to Keycloak authorization endpoint for OAuth flow with support for authorization details
     * OAuth Authorization Endpoint
     */
    async getAuthAuthorize(requestParameters?: GetAuthAuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        const response = await this.getAuthAuthorizeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Simplified login endpoint that redirects to Keycloak with sensible defaults for UI applications
     * Login Page Redirect
     */
    async getAuthLoginRaw(requestParameters?: GetAuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['clientId'] != null) {
            queryParameters['client_id'] = requestParameters['clientId'];
        }
        if (requestParameters['redirectUri'] != null) {
            queryParameters['redirect_uri'] = requestParameters['redirectUri'];
        }
        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }
        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }
        if (requestParameters['codeChallenge'] != null) {
            queryParameters['code_challenge'] = requestParameters['codeChallenge'];
        }
        if (requestParameters['codeChallengeMethod'] != null) {
            queryParameters['code_challenge_method'] = requestParameters['codeChallengeMethod'];
        }
        if (requestParameters['authorizationDetails'] != null) {
            queryParameters['authorization_details'] = requestParameters['authorizationDetails'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Simplified login endpoint that redirects to Keycloak with sensible defaults for UI applications
     * Login Page Redirect
     */
    async getAuthLogin(requestParameters?: GetAuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        const response = await this.getAuthLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Proxies logout requests to Keycloak with sensible defaults
     * Logout Endpoint
     */
    async getAuthLogoutRaw(requestParameters?: GetAuthLogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['postLogoutRedirectUri'] != null) {
            queryParameters['post_logout_redirect_uri'] = requestParameters['postLogoutRedirectUri'];
        }
        if (requestParameters['idTokenHint'] != null) {
            queryParameters['id_token_hint'] = requestParameters['idTokenHint'];
        }
        if (requestParameters['clientId'] != null) {
            queryParameters['client_id'] = requestParameters['clientId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Proxies logout requests to Keycloak with sensible defaults
     * Logout Endpoint
     */
    async getAuthLogout(requestParameters?: GetAuthLogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        const response = await this.getAuthLogoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of enabled identity providers for login page (public endpoint)
     * Get Public Identity Providers
     */
    async getAuthIdentityProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicIdentityProvider>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/identity-providers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicIdentityProviderFromJSON));
    }

    /**
     * Get list of enabled identity providers for login page (public endpoint)
     * Get Public Identity Providers
     */
    async getAuthIdentityProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicIdentityProvider>> {
        const response = await this.getAuthIdentityProvidersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Exchange authorization code for access token with SMART launch context and authorization details for multiple FHIR servers
     * OAuth Token Exchange
     */
    async postAuthTokenRaw(requestParameters: PostAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        if (requestParameters['tokenRequest'] == null) {
            throw new runtime.RequiredError(
                'tokenRequest',
                'Required parameter "tokenRequest" was null or undefined when calling postAuthToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/token`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRequestToJSON(requestParameters['tokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Exchange authorization code for access token with SMART launch context and authorization details for multiple FHIR servers
     * OAuth Token Exchange
     */
    async postAuthToken(requestParameters: PostAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.postAuthTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validate and get information about an access token
     * Token Introspection
     */
    async postAuthIntrospectRaw(requestParameters: PostAuthIntrospectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling postAuthIntrospect().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/introspect`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        }, initOverrides);

        return new runtime.JSONApiResponse<{ [key: string]: any }>(response);
    }

    /**
     * Validate and get information about an access token
     * Token Introspection
     */
    async postAuthIntrospect(requestParameters: PostAuthIntrospectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any }> {
        const response = await this.postAuthIntrospectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get authenticated user profile information from JWT token
     * Get Current User Profile
     */
    async getAuthUserinfoRaw(requestParameters: GetAuthUserinfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfoResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getAuthUserinfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/userinfo`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInfoResponseFromJSON(jsonValue));
    }

    /**
     * Get authenticated user profile information from JWT token
     * Get Current User Profile
     */
    async getAuthUserinfo(requestParameters: GetAuthUserinfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfoResponse> {
        const response = await this.getAuthUserinfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a new OAuth2 client dynamically according to RFC 7591. This is a public endpoint that does not require authentication.
     * Dynamic Client Registration
     */
    async postAuthRegisterRaw(requestParameters: PostAuthRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientRegistrationResponse>> {
        if (requestParameters['clientRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'clientRegistrationRequest',
                'Required parameter "clientRegistrationRequest" was null or undefined when calling postAuthRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/register`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClientRegistrationRequestToJSON(requestParameters['clientRegistrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientRegistrationResponseFromJSON(jsonValue));
    }

    /**
     * Register a new OAuth2 client dynamically according to RFC 7591. This is a public endpoint that does not require authentication.
     * Dynamic Client Registration
     */
    async postAuthRegister(requestParameters: PostAuthRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientRegistrationResponse> {
        const response = await this.postAuthRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
