/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.3-alpha.202603262210.ca39219f
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FhirHealthChecksResponse,
  FhirUptimeSummariesResponse,
} from '../models/index';
import {
    FhirHealthChecksResponseFromJSON,
    FhirHealthChecksResponseToJSON,
    FhirUptimeSummariesResponseFromJSON,
    FhirUptimeSummariesResponseToJSON,
} from '../models/index';

export interface GetMonitoringFhirChecksStreamRequest {
    token?: string;
    authorization?: string;
}

export interface GetMonitoringFhirSummariesStreamRequest {
    token?: string;
    authorization?: string;
}

export interface GetMonitoringFhirChecksRequest {
    serverUrl?: string;
    limit?: string;
    since?: string;
    authorization?: string;
}

export interface GetMonitoringFhirSummariesRequest {
    authorization?: string;
}

/**
 * 
 */
export class FhirMonitoringApi extends runtime.BaseAPI {

    /**
     * SSE stream of real-time FHIR server health check results
     * FHIR Health Check Stream
     */
    async getMonitoringFhirChecksStreamRaw(requestParameters?: GetMonitoringFhirChecksStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/fhir/checks/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<object>(response);
    }

    /**
     * SSE stream of real-time FHIR server health check results
     * FHIR Health Check Stream
     */
    async getMonitoringFhirChecksStream(requestParameters?: GetMonitoringFhirChecksStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMonitoringFhirChecksStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * SSE stream of FHIR server uptime summaries, emitted after each check sweep
     * FHIR Uptime Summary Stream
     */
    async getMonitoringFhirSummariesStreamRaw(requestParameters?: GetMonitoringFhirSummariesStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/fhir/summaries/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<object>(response);
    }

    /**
     * SSE stream of FHIR server uptime summaries, emitted after each check sweep
     * FHIR Uptime Summary Stream
     */
    async getMonitoringFhirSummariesStream(requestParameters?: GetMonitoringFhirSummariesStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMonitoringFhirSummariesStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve recent FHIR server health check results with optional filtering
     * Get FHIR Health Checks
     */
    async getMonitoringFhirChecksRaw(requestParameters?: GetMonitoringFhirChecksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FhirHealthChecksResponse>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['serverUrl'] != null) {
            queryParameters['serverUrl'] = requestParameters['serverUrl'];
        }
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/fhir/checks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FhirHealthChecksResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve recent FHIR server health check results with optional filtering
     * Get FHIR Health Checks
     */
    async getMonitoringFhirChecks(requestParameters?: GetMonitoringFhirChecksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FhirHealthChecksResponse> {
        const response = await this.getMonitoringFhirChecksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Per-server uptime percentage, average response time, and recent check history
     * Get FHIR Uptime Summaries
     */
    async getMonitoringFhirSummariesRaw(requestParameters?: GetMonitoringFhirSummariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FhirUptimeSummariesResponse>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};
        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/monitoring/fhir/summaries`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FhirUptimeSummariesResponseFromJSON(jsonValue));
    }

    /**
     * Per-server uptime percentage, average response time, and recent check history
     * Get FHIR Uptime Summaries
     */
    async getMonitoringFhirSummaries(requestParameters?: GetMonitoringFhirSummariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FhirUptimeSummariesResponse> {
        const response = await this.getMonitoringFhirSummariesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
