/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CountResponse,
  GetAdminOrganizations200ResponseInner,
  GetAdminOrganizationsByOrgIdMembers200ResponseInner,
  OrgBrandConfig,
  OrgBrandConfigResponse,
  PostAdminOrganizationsByOrgIdMembersRequest,
  PostAdminOrganizationsRequest,
  PutAdminOrganizationsByOrgIdRequest,
  SuccessResponse,
} from '../models/index';
import {
    CountResponseFromJSON,
    CountResponseToJSON,
    GetAdminOrganizations200ResponseInnerFromJSON,
    GetAdminOrganizations200ResponseInnerToJSON,
    GetAdminOrganizationsByOrgIdMembers200ResponseInnerFromJSON,
    GetAdminOrganizationsByOrgIdMembers200ResponseInnerToJSON,
    OrgBrandConfigFromJSON,
    OrgBrandConfigToJSON,
    OrgBrandConfigResponseFromJSON,
    OrgBrandConfigResponseToJSON,
    PostAdminOrganizationsByOrgIdMembersRequestFromJSON,
    PostAdminOrganizationsByOrgIdMembersRequestToJSON,
    PostAdminOrganizationsRequestFromJSON,
    PostAdminOrganizationsRequestToJSON,
    PutAdminOrganizationsByOrgIdRequestFromJSON,
    PutAdminOrganizationsByOrgIdRequestToJSON,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
} from '../models/index';

export interface GetAdminOrganizationsRequest {
    limit?: string | number;
    offset?: string | number;
    search?: string;
}

export interface PostAdminOrganizationsOperationRequest {
    postAdminOrganizationsRequest: PostAdminOrganizationsRequest;
}

export interface GetAdminOrganizationsByOrgIdRequest {
    orgId: string;
}

export interface PutAdminOrganizationsByOrgIdOperationRequest {
    orgId: string;
    putAdminOrganizationsByOrgIdRequest: PutAdminOrganizationsByOrgIdRequest;
}

export interface DeleteAdminOrganizationsByOrgIdRequest {
    orgId: string;
}

export interface GetAdminOrganizationsByOrgIdMembersRequest {
    orgId: string;
    limit?: string | number;
    offset?: string | number;
    search?: string;
}

export interface PostAdminOrganizationsByOrgIdMembersOperationRequest {
    orgId: string;
    postAdminOrganizationsByOrgIdMembersRequest: PostAdminOrganizationsByOrgIdMembersRequest;
}

export interface DeleteAdminOrganizationsByOrgIdMembersByUserIdRequest {
    orgId: string;
    userId: string;
}

export interface GetAdminOrganizationsByOrgIdBrandingRequest {
    orgId: string;
}

export interface PutAdminOrganizationsByOrgIdBrandingRequest {
    orgId: string;
    orgBrandConfig: OrgBrandConfig;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * List all Keycloak organizations in the realm
     * List Organizations
     */
    async getAdminOrganizationsRaw(requestParameters?: GetAdminOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAdminOrganizations200ResponseInner>>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }
        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAdminOrganizations200ResponseInnerFromJSON));
    }

    /**
     * List all Keycloak organizations in the realm
     * List Organizations
     */
    async getAdminOrganizations(requestParameters?: GetAdminOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAdminOrganizations200ResponseInner>> {
        const response = await this.getAdminOrganizationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new Keycloak organization
     * Create Organization
     */
    async postAdminOrganizationsRaw(requestParameters: PostAdminOrganizationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminOrganizations200ResponseInner>> {
        if (requestParameters['postAdminOrganizationsRequest'] == null) {
            throw new runtime.RequiredError(
                'postAdminOrganizationsRequest',
                'Required parameter "postAdminOrganizationsRequest" was null or undefined when calling postAdminOrganizations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAdminOrganizationsRequestToJSON(requestParameters['postAdminOrganizationsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminOrganizations200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Create a new Keycloak organization
     * Create Organization
     */
    async postAdminOrganizations(requestParameters: PostAdminOrganizationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminOrganizations200ResponseInner> {
        const response = await this.postAdminOrganizationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the total number of organizations
     * Count Organizations
     */
    async getAdminOrganizationsCountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CountResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountResponseFromJSON(jsonValue));
    }

    /**
     * Get the total number of organizations
     * Count Organizations
     */
    async getAdminOrganizationsCount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CountResponse> {
        const response = await this.getAdminOrganizationsCountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a single organization by ID
     * Get Organization
     */
    async getAdminOrganizationsByOrgIdRaw(requestParameters: GetAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminOrganizations200ResponseInner>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getAdminOrganizationsByOrgId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminOrganizations200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Get a single organization by ID
     * Get Organization
     */
    async getAdminOrganizationsByOrgId(requestParameters: GetAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminOrganizations200ResponseInner> {
        const response = await this.getAdminOrganizationsByOrgIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing organization
     * Update Organization
     */
    async putAdminOrganizationsByOrgIdRaw(requestParameters: PutAdminOrganizationsByOrgIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminOrganizations200ResponseInner>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling putAdminOrganizationsByOrgId().'
            );
        }

        if (requestParameters['putAdminOrganizationsByOrgIdRequest'] == null) {
            throw new runtime.RequiredError(
                'putAdminOrganizationsByOrgIdRequest',
                'Required parameter "putAdminOrganizationsByOrgIdRequest" was null or undefined when calling putAdminOrganizationsByOrgId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PutAdminOrganizationsByOrgIdRequestToJSON(requestParameters['putAdminOrganizationsByOrgIdRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminOrganizations200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Update an existing organization
     * Update Organization
     */
    async putAdminOrganizationsByOrgId(requestParameters: PutAdminOrganizationsByOrgIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminOrganizations200ResponseInner> {
        const response = await this.putAdminOrganizationsByOrgIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an organization and all its managed members
     * Delete Organization
     */
    async deleteAdminOrganizationsByOrgIdRaw(requestParameters: DeleteAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteAdminOrganizationsByOrgId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete an organization and all its managed members
     * Delete Organization
     */
    async deleteAdminOrganizationsByOrgId(requestParameters: DeleteAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.deleteAdminOrganizationsByOrgIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all members of an organization
     * List Organization Members
     */
    async getAdminOrganizationsByOrgIdMembersRaw(requestParameters: GetAdminOrganizationsByOrgIdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAdminOrganizationsByOrgIdMembers200ResponseInner>>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getAdminOrganizationsByOrgIdMembers().'
            );
        }

        const queryParameters: any = {};
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }
        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/members`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAdminOrganizationsByOrgIdMembers200ResponseInnerFromJSON));
    }

    /**
     * List all members of an organization
     * List Organization Members
     */
    async getAdminOrganizationsByOrgIdMembers(requestParameters: GetAdminOrganizationsByOrgIdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAdminOrganizationsByOrgIdMembers200ResponseInner>> {
        const response = await this.getAdminOrganizationsByOrgIdMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add an existing realm user as an organization member
     * Add Member
     */
    async postAdminOrganizationsByOrgIdMembersRaw(requestParameters: PostAdminOrganizationsByOrgIdMembersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling postAdminOrganizationsByOrgIdMembers().'
            );
        }

        if (requestParameters['postAdminOrganizationsByOrgIdMembersRequest'] == null) {
            throw new runtime.RequiredError(
                'postAdminOrganizationsByOrgIdMembersRequest',
                'Required parameter "postAdminOrganizationsByOrgIdMembersRequest" was null or undefined when calling postAdminOrganizationsByOrgIdMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/members`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAdminOrganizationsByOrgIdMembersRequestToJSON(requestParameters['postAdminOrganizationsByOrgIdMembersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Add an existing realm user as an organization member
     * Add Member
     */
    async postAdminOrganizationsByOrgIdMembers(requestParameters: PostAdminOrganizationsByOrgIdMembersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.postAdminOrganizationsByOrgIdMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a member from an organization
     * Remove Member
     */
    async deleteAdminOrganizationsByOrgIdMembersByUserIdRaw(requestParameters: DeleteAdminOrganizationsByOrgIdMembersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteAdminOrganizationsByOrgIdMembersByUserId().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteAdminOrganizationsByOrgIdMembersByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/members/{userId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace(`{userId}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Remove a member from an organization
     * Remove Member
     */
    async deleteAdminOrganizationsByOrgIdMembersByUserId(requestParameters: DeleteAdminOrganizationsByOrgIdMembersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.deleteAdminOrganizationsByOrgIdMembersByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get per-organization brand overrides (fields not set cascade to realm defaults)
     * Get Organization Branding
     */
    async getAdminOrganizationsByOrgIdBrandingRaw(requestParameters: GetAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgBrandConfigResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getAdminOrganizationsByOrgIdBranding().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/branding`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgBrandConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get per-organization brand overrides (fields not set cascade to realm defaults)
     * Get Organization Branding
     */
    async getAdminOrganizationsByOrgIdBranding(requestParameters: GetAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgBrandConfigResponse> {
        const response = await this.getAdminOrganizationsByOrgIdBrandingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set per-organization brand overrides. Only provided fields are stored; omitted fields cascade to realm defaults.
     * Update Organization Branding
     */
    async putAdminOrganizationsByOrgIdBrandingRaw(requestParameters: PutAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgBrandConfigResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling putAdminOrganizationsByOrgIdBranding().'
            );
        }

        if (requestParameters['orgBrandConfig'] == null) {
            throw new runtime.RequiredError(
                'orgBrandConfig',
                'Required parameter "orgBrandConfig" was null or undefined when calling putAdminOrganizationsByOrgIdBranding().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/branding`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrgBrandConfigToJSON(requestParameters['orgBrandConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgBrandConfigResponseFromJSON(jsonValue));
    }

    /**
     * Set per-organization brand overrides. Only provided fields are stored; omitted fields cascade to realm defaults.
     * Update Organization Branding
     */
    async putAdminOrganizationsByOrgIdBranding(requestParameters: PutAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgBrandConfigResponse> {
        const response = await this.putAdminOrganizationsByOrgIdBrandingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
