/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151658.c3071eb4
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddMemberRequest,
  CountResponse,
  CreateOrganizationRequest,
  OrgBrandConfig,
  OrgBrandConfigResponse,
  Organization,
  OrganizationMember,
  SuccessResponse,
  UpdateOrganizationRequest,
} from '../models/index';
import {
    AddMemberRequestFromJSON,
    AddMemberRequestToJSON,
    CountResponseFromJSON,
    CountResponseToJSON,
    CreateOrganizationRequestFromJSON,
    CreateOrganizationRequestToJSON,
    OrgBrandConfigFromJSON,
    OrgBrandConfigToJSON,
    OrgBrandConfigResponseFromJSON,
    OrgBrandConfigResponseToJSON,
    OrganizationFromJSON,
    OrganizationToJSON,
    OrganizationMemberFromJSON,
    OrganizationMemberToJSON,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
    UpdateOrganizationRequestFromJSON,
    UpdateOrganizationRequestToJSON,
} from '../models/index';

export interface GetAdminOrganizationsRequest {
    limit?: string | number;
    offset?: string | number;
    search?: string;
}

export interface PostAdminOrganizationsRequest {
    createOrganizationRequest: CreateOrganizationRequest;
}

export interface GetAdminOrganizationsByOrgIdRequest {
    orgId: string;
}

export interface PutAdminOrganizationsByOrgIdRequest {
    orgId: string;
    updateOrganizationRequest: UpdateOrganizationRequest;
}

export interface DeleteAdminOrganizationsByOrgIdRequest {
    orgId: string;
}

export interface GetAdminOrganizationsByOrgIdMembersRequest {
    orgId: string;
    limit?: string | number;
    offset?: string | number;
    search?: string;
}

export interface PostAdminOrganizationsByOrgIdMembersRequest {
    orgId: string;
    addMemberRequest: AddMemberRequest;
}

export interface DeleteAdminOrganizationsByOrgIdMembersByUserIdRequest {
    orgId: string;
    userId: string;
}

export interface GetAdminOrganizationsByOrgIdBrandingRequest {
    orgId: string;
}

export interface PutAdminOrganizationsByOrgIdBrandingRequest {
    orgId: string;
    orgBrandConfig: OrgBrandConfig;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * List all Keycloak organizations in the realm
     * List Organizations
     */
    async getAdminOrganizationsRaw(requestParameters?: GetAdminOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Organization>>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }
        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationFromJSON));
    }

    /**
     * List all Keycloak organizations in the realm
     * List Organizations
     */
    async getAdminOrganizations(requestParameters?: GetAdminOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Organization>> {
        const response = await this.getAdminOrganizationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new Keycloak organization
     * Create Organization
     */
    async postAdminOrganizationsRaw(requestParameters: PostAdminOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        if (requestParameters['createOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationRequest',
                'Required parameter "createOrganizationRequest" was null or undefined when calling postAdminOrganizations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationRequestToJSON(requestParameters['createOrganizationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Create a new Keycloak organization
     * Create Organization
     */
    async postAdminOrganizations(requestParameters: PostAdminOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.postAdminOrganizationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the total number of organizations
     * Count Organizations
     */
    async getAdminOrganizationsCountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CountResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountResponseFromJSON(jsonValue));
    }

    /**
     * Get the total number of organizations
     * Count Organizations
     */
    async getAdminOrganizationsCount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CountResponse> {
        const response = await this.getAdminOrganizationsCountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a single organization by ID
     * Get Organization
     */
    async getAdminOrganizationsByOrgIdRaw(requestParameters: GetAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getAdminOrganizationsByOrgId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Get a single organization by ID
     * Get Organization
     */
    async getAdminOrganizationsByOrgId(requestParameters: GetAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.getAdminOrganizationsByOrgIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing organization
     * Update Organization
     */
    async putAdminOrganizationsByOrgIdRaw(requestParameters: PutAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling putAdminOrganizationsByOrgId().'
            );
        }

        if (requestParameters['updateOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizationRequest',
                'Required parameter "updateOrganizationRequest" was null or undefined when calling putAdminOrganizationsByOrgId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationRequestToJSON(requestParameters['updateOrganizationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Update an existing organization
     * Update Organization
     */
    async putAdminOrganizationsByOrgId(requestParameters: PutAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.putAdminOrganizationsByOrgIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an organization and all its managed members
     * Delete Organization
     */
    async deleteAdminOrganizationsByOrgIdRaw(requestParameters: DeleteAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteAdminOrganizationsByOrgId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete an organization and all its managed members
     * Delete Organization
     */
    async deleteAdminOrganizationsByOrgId(requestParameters: DeleteAdminOrganizationsByOrgIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.deleteAdminOrganizationsByOrgIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all members of an organization
     * List Organization Members
     */
    async getAdminOrganizationsByOrgIdMembersRaw(requestParameters: GetAdminOrganizationsByOrgIdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationMember>>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getAdminOrganizationsByOrgIdMembers().'
            );
        }

        const queryParameters: any = {};
        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }
        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }
        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/members`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationMemberFromJSON));
    }

    /**
     * List all members of an organization
     * List Organization Members
     */
    async getAdminOrganizationsByOrgIdMembers(requestParameters: GetAdminOrganizationsByOrgIdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationMember>> {
        const response = await this.getAdminOrganizationsByOrgIdMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add an existing realm user as an organization member
     * Add Member
     */
    async postAdminOrganizationsByOrgIdMembersRaw(requestParameters: PostAdminOrganizationsByOrgIdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling postAdminOrganizationsByOrgIdMembers().'
            );
        }

        if (requestParameters['addMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'addMemberRequest',
                'Required parameter "addMemberRequest" was null or undefined when calling postAdminOrganizationsByOrgIdMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/members`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddMemberRequestToJSON(requestParameters['addMemberRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Add an existing realm user as an organization member
     * Add Member
     */
    async postAdminOrganizationsByOrgIdMembers(requestParameters: PostAdminOrganizationsByOrgIdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.postAdminOrganizationsByOrgIdMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a member from an organization
     * Remove Member
     */
    async deleteAdminOrganizationsByOrgIdMembersByUserIdRaw(requestParameters: DeleteAdminOrganizationsByOrgIdMembersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteAdminOrganizationsByOrgIdMembersByUserId().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteAdminOrganizationsByOrgIdMembersByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/members/{userId}`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace(`{userId}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Remove a member from an organization
     * Remove Member
     */
    async deleteAdminOrganizationsByOrgIdMembersByUserId(requestParameters: DeleteAdminOrganizationsByOrgIdMembersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.deleteAdminOrganizationsByOrgIdMembersByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get per-organization brand overrides (fields not set cascade to realm defaults)
     * Get Organization Branding
     */
    async getAdminOrganizationsByOrgIdBrandingRaw(requestParameters: GetAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgBrandConfigResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getAdminOrganizationsByOrgIdBranding().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/branding`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgBrandConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get per-organization brand overrides (fields not set cascade to realm defaults)
     * Get Organization Branding
     */
    async getAdminOrganizationsByOrgIdBranding(requestParameters: GetAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgBrandConfigResponse> {
        const response = await this.getAdminOrganizationsByOrgIdBrandingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set per-organization brand overrides. Only provided fields are stored; omitted fields cascade to realm defaults.
     * Update Organization Branding
     */
    async putAdminOrganizationsByOrgIdBrandingRaw(requestParameters: PutAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgBrandConfigResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling putAdminOrganizationsByOrgIdBranding().'
            );
        }

        if (requestParameters['orgBrandConfig'] == null) {
            throw new runtime.RequiredError(
                'orgBrandConfig',
                'Required parameter "orgBrandConfig" was null or undefined when calling putAdminOrganizationsByOrgIdBranding().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/organizations/{orgId}/branding`;
        urlPath = urlPath.replace(`{orgId}`, encodeURIComponent(String(requestParameters['orgId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrgBrandConfigToJSON(requestParameters['orgBrandConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgBrandConfigResponseFromJSON(jsonValue));
    }

    /**
     * Set per-organization brand overrides. Only provided fields are stored; omitted fields cascade to realm defaults.
     * Update Organization Branding
     */
    async putAdminOrganizationsByOrgIdBranding(requestParameters: PutAdminOrganizationsByOrgIdBrandingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgBrandConfigResponse> {
        const response = await this.putAdminOrganizationsByOrgIdBrandingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
