/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthResponse,
  SystemStatusResponse,
} from '../models/index';
import {
    HealthResponseFromJSON,
    HealthResponseToJSON,
    SystemStatusResponseFromJSON,
    SystemStatusResponseToJSON,
} from '../models/index';

export interface GetHealthRequest {
    force?: string;
}

/**
 * 
 */
export class ServerApi extends runtime.BaseAPI {

    /**
     * Always returns 200 if the backend process is running. Subsystem health is in the response body. Use /status for detailed diagnostics.
     * Liveness Probe
     */
    async getHealthRaw(requestParameters?: GetHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        requestParameters = requestParameters || {};

        const queryParameters: any = {};
        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Always returns 200 if the backend process is running. Subsystem health is in the response body. Use /status for detailed diagnostics.
     * Liveness Probe
     */
    async getHealth(requestParameters?: GetHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.getHealthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Comprehensive system status (cached components)
     * System Status
     */
    async getStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemStatusResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemStatusResponseFromJSON(jsonValue));
    }

    /**
     * Comprehensive system status (cached components)
     * System Status
     */
    async getStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemStatusResponse> {
        const response = await this.getStatusRaw(initOverrides);
        return await response.value();
    }

}
