/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart Backend
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.5-alpha.202604151618.09324581
 *
 * NOTE: This class is auto generated by generate-ts-fetch-client.py
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddFhirServerRequest,
  AddFhirServerResponse,
  CertificateUpload,
  DeleteFhirServerResponse,
  FhirServerDetails,
  FhirServerList,
  MtlsConfig,
  RefreshFhirServerResponse,
  SetStrictCapabilitiesRequest,
  SetStrictCapabilitiesResponse,
  UpdateMtlsConfigRequest,
  UpdateMtlsConfigResponse,
  UploadCertificateRequest,
} from '../models/index';
import {
    AddFhirServerRequestFromJSON,
    AddFhirServerRequestToJSON,
    AddFhirServerResponseFromJSON,
    AddFhirServerResponseToJSON,
    CertificateUploadFromJSON,
    CertificateUploadToJSON,
    DeleteFhirServerResponseFromJSON,
    DeleteFhirServerResponseToJSON,
    FhirServerDetailsFromJSON,
    FhirServerDetailsToJSON,
    FhirServerListFromJSON,
    FhirServerListToJSON,
    MtlsConfigFromJSON,
    MtlsConfigToJSON,
    RefreshFhirServerResponseFromJSON,
    RefreshFhirServerResponseToJSON,
    SetStrictCapabilitiesRequestFromJSON,
    SetStrictCapabilitiesRequestToJSON,
    SetStrictCapabilitiesResponseFromJSON,
    SetStrictCapabilitiesResponseToJSON,
    UpdateMtlsConfigRequestFromJSON,
    UpdateMtlsConfigRequestToJSON,
    UpdateMtlsConfigResponseFromJSON,
    UpdateMtlsConfigResponseToJSON,
    UploadCertificateRequestFromJSON,
    UploadCertificateRequestToJSON,
} from '../models/index';

export interface PostFhirServersRequest {
    addFhirServerRequest: AddFhirServerRequest;
}

export interface GetFhirServersByServerIdRequest {
    serverId: string;
}

export interface PutFhirServersByServerIdRequest {
    serverId: string;
    addFhirServerRequest: AddFhirServerRequest;
}

export interface DeleteFhirServersByServerIdRequest {
    serverId: string;
}

export interface GetFhirServersByServerIdMtlsRequest {
    serverId: string;
}

export interface PutFhirServersByServerIdMtlsRequest {
    serverId: string;
    updateMtlsConfigRequest: UpdateMtlsConfigRequest;
}

export interface PostFhirServersByServerIdMtlsCertificatesRequest {
    serverId: string;
    uploadCertificateRequest: UploadCertificateRequest;
}

export interface PatchFhirServersByServerIdStrictCapabilitiesRequest {
    serverId: string;
    setStrictCapabilitiesRequest: SetStrictCapabilitiesRequest;
}

export interface PostFhirServersByServerIdRefreshRequest {
    serverId: string;
}

/**
 * 
 */
export class ServersApi extends runtime.BaseAPI {

    /**
     * Get a list of all configured FHIR servers with their connection information and endpoints
     * List Available FHIR Servers
     */
    async getFhirServersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FhirServerList>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FhirServerListFromJSON(jsonValue));
    }

    /**
     * Get a list of all configured FHIR servers with their connection information and endpoints
     * List Available FHIR Servers
     */
    async getFhirServers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FhirServerList> {
        const response = await this.getFhirServersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Add a new FHIR server to the system by providing its base URL
     * Add New FHIR Server
     */
    async postFhirServersRaw(requestParameters: PostFhirServersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddFhirServerResponse>> {
        if (requestParameters['addFhirServerRequest'] == null) {
            throw new runtime.RequiredError(
                'addFhirServerRequest',
                'Required parameter "addFhirServerRequest" was null or undefined when calling postFhirServers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/`;

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddFhirServerRequestToJSON(requestParameters['addFhirServerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddFhirServerResponseFromJSON(jsonValue));
    }

    /**
     * Add a new FHIR server to the system by providing its base URL
     * Add New FHIR Server
     */
    async postFhirServers(requestParameters: PostFhirServersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddFhirServerResponse> {
        const response = await this.postFhirServersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get detailed information about a specific FHIR server
     * Get Server Information
     */
    async getFhirServersByServerIdRaw(requestParameters: GetFhirServersByServerIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FhirServerDetails>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getFhirServersByServerId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FhirServerDetailsFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific FHIR server
     * Get Server Information
     */
    async getFhirServersByServerId(requestParameters: GetFhirServersByServerIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FhirServerDetails> {
        const response = await this.getFhirServersByServerIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing FHIR server by providing its new base URL
     * Update FHIR Server
     */
    async putFhirServersByServerIdRaw(requestParameters: PutFhirServersByServerIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddFhirServerResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling putFhirServersByServerId().'
            );
        }

        if (requestParameters['addFhirServerRequest'] == null) {
            throw new runtime.RequiredError(
                'addFhirServerRequest',
                'Required parameter "addFhirServerRequest" was null or undefined when calling putFhirServersByServerId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AddFhirServerRequestToJSON(requestParameters['addFhirServerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddFhirServerResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing FHIR server by providing its new base URL
     * Update FHIR Server
     */
    async putFhirServersByServerId(requestParameters: PutFhirServersByServerIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddFhirServerResponse> {
        const response = await this.putFhirServersByServerIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a FHIR server from the system. This does not delete any patient data on the FHIR server itself.
     * Delete FHIR Server
     */
    async deleteFhirServersByServerIdRaw(requestParameters: DeleteFhirServersByServerIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteFhirServerResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling deleteFhirServersByServerId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteFhirServerResponseFromJSON(jsonValue));
    }

    /**
     * Remove a FHIR server from the system. This does not delete any patient data on the FHIR server itself.
     * Delete FHIR Server
     */
    async deleteFhirServersByServerId(requestParameters: DeleteFhirServersByServerIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteFhirServerResponse> {
        const response = await this.deleteFhirServersByServerIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the mutual TLS configuration for a specific FHIR server
     * Get mTLS Configuration
     */
    async getFhirServersByServerIdMtlsRaw(requestParameters: GetFhirServersByServerIdMtlsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MtlsConfig>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getFhirServersByServerIdMtls().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}/mtls`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MtlsConfigFromJSON(jsonValue));
    }

    /**
     * Get the mutual TLS configuration for a specific FHIR server
     * Get mTLS Configuration
     */
    async getFhirServersByServerIdMtls(requestParameters: GetFhirServersByServerIdMtlsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MtlsConfig> {
        const response = await this.getFhirServersByServerIdMtlsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enable or disable mutual TLS for a specific FHIR server
     * Update mTLS Configuration
     */
    async putFhirServersByServerIdMtlsRaw(requestParameters: PutFhirServersByServerIdMtlsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateMtlsConfigResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling putFhirServersByServerIdMtls().'
            );
        }

        if (requestParameters['updateMtlsConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMtlsConfigRequest',
                'Required parameter "updateMtlsConfigRequest" was null or undefined when calling putFhirServersByServerIdMtls().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}/mtls`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMtlsConfigRequestToJSON(requestParameters['updateMtlsConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateMtlsConfigResponseFromJSON(jsonValue));
    }

    /**
     * Enable or disable mutual TLS for a specific FHIR server
     * Update mTLS Configuration
     */
    async putFhirServersByServerIdMtls(requestParameters: PutFhirServersByServerIdMtlsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateMtlsConfigResponse> {
        const response = await this.putFhirServersByServerIdMtlsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a certificate or private key for mTLS authentication
     * Upload Certificate
     */
    async postFhirServersByServerIdMtlsCertificatesRaw(requestParameters: PostFhirServersByServerIdMtlsCertificatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CertificateUpload>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling postFhirServersByServerIdMtlsCertificates().'
            );
        }

        if (requestParameters['uploadCertificateRequest'] == null) {
            throw new runtime.RequiredError(
                'uploadCertificateRequest',
                'Required parameter "uploadCertificateRequest" was null or undefined when calling postFhirServersByServerIdMtlsCertificates().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}/mtls/certificates`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadCertificateRequestToJSON(requestParameters['uploadCertificateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CertificateUploadFromJSON(jsonValue));
    }

    /**
     * Upload a certificate or private key for mTLS authentication
     * Upload Certificate
     */
    async postFhirServersByServerIdMtlsCertificates(requestParameters: PostFhirServersByServerIdMtlsCertificatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CertificateUpload> {
        const response = await this.postFhirServersByServerIdMtlsCertificatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enable or disable strict CapabilityStatement enforcement on the FHIR proxy for this server. When strict, the proxy rejects requests for interactions/operations not declared in the server's CapabilityStatement.
     * Toggle Strict Capability Enforcement
     */
    async patchFhirServersByServerIdStrictCapabilitiesRaw(requestParameters: PatchFhirServersByServerIdStrictCapabilitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetStrictCapabilitiesResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling patchFhirServersByServerIdStrictCapabilities().'
            );
        }

        if (requestParameters['setStrictCapabilitiesRequest'] == null) {
            throw new runtime.RequiredError(
                'setStrictCapabilitiesRequest',
                'Required parameter "setStrictCapabilitiesRequest" was null or undefined when calling patchFhirServersByServerIdStrictCapabilities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}/strict-capabilities`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SetStrictCapabilitiesRequestToJSON(requestParameters['setStrictCapabilitiesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetStrictCapabilitiesResponseFromJSON(jsonValue));
    }

    /**
     * Enable or disable strict CapabilityStatement enforcement on the FHIR proxy for this server. When strict, the proxy rejects requests for interactions/operations not declared in the server's CapabilityStatement.
     * Toggle Strict Capability Enforcement
     */
    async patchFhirServersByServerIdStrictCapabilities(requestParameters: PatchFhirServersByServerIdStrictCapabilitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetStrictCapabilitiesResponse> {
        const response = await this.patchFhirServersByServerIdStrictCapabilitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Re-fetch the CapabilityStatement from the FHIR server to update metadata like server name, version, and connection status.
     * Refresh FHIR Server Metadata
     */
    async postFhirServersByServerIdRefreshRaw(requestParameters: PostFhirServersByServerIdRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefreshFhirServerResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling postFhirServersByServerIdRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{server_id}/refresh`;
        urlPath = urlPath.replace(`{server_id}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefreshFhirServerResponseFromJSON(jsonValue));
    }

    /**
     * Re-fetch the CapabilityStatement from the FHIR server to update metadata like server name, version, and connection status.
     * Refresh FHIR Server Metadata
     */
    async postFhirServersByServerIdRefresh(requestParameters: PostFhirServersByServerIdRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefreshFhirServerResponse> {
        const response = await this.postFhirServersByServerIdRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
