/**
 * ValueSet Registry
 * Central registry of all loaded ValueSets with explicit codes
 */
import * as AdministrativeGender from './ValueSet-AdministrativeGender.js';
import * as AllergyIntoleranceCategory from './ValueSet-AllergyIntoleranceCategory.js';
import * as AllergyintoleranceClinical from './ValueSet-AllergyintoleranceClinical.js';
import * as AllergyIntoleranceCriticality from './ValueSet-AllergyIntoleranceCriticality.js';
import * as AllergyIntoleranceType from './ValueSet-AllergyIntoleranceType.js';
import * as AllergyintoleranceVerification from './ValueSet-AllergyintoleranceVerification.js';
import * as AllSecurityLabels from './ValueSet-AllSecurityLabels.js';
import * as BodySite from './ValueSet-BodySite.js';
import * as BodysiteLaterality from './ValueSet-BodysiteLaterality.js';
import * as BundleType from './ValueSet-BundleType.js';
import * as C80PracticeCodes from './ValueSet-C80PracticeCodes.js';
import * as ClinicalFindings from './ValueSet-ClinicalFindings.js';
import * as CommonTags from './ValueSet-CommonTags.js';
import * as CompositionAttestationMode from './ValueSet-CompositionAttestationMode.js';
import * as CompositionStatus from './ValueSet-CompositionStatus.js';
import * as ConditionClinical from './ValueSet-ConditionClinical.js';
import * as ConditionCode from './ValueSet-ConditionCode.js';
import * as ConditionSeverity from './ValueSet-ConditionSeverity.js';
import * as ConditionStage from './ValueSet-ConditionStage.js';
import * as ConditionStageType from './ValueSet-ConditionStageType.js';
import * as ConditionVerStatus from './ValueSet-ConditionVerStatus.js';
import * as ContactentityType from './ValueSet-ContactentityType.js';
import * as CurrentSmokingStatusUvIps from './ValueSet-CurrentSmokingStatusUvIps.js';
import * as DataAbsentReason from './ValueSet-DataAbsentReason.js';
import * as DaysOfWeek from './ValueSet-DaysOfWeek.js';
import * as DeviceNametype from './ValueSet-DeviceNametype.js';
import * as DeviceStatementStatus from './ValueSet-DeviceStatementStatus.js';
import * as DeviceStatus from './ValueSet-DeviceStatus.js';
import * as DeviceStatusReason from './ValueSet-DeviceStatusReason.js';
import * as DeviceType from './ValueSet-DeviceType.js';
import * as DiagnosticReportStatusUvIps from './ValueSet-DiagnosticReportStatusUvIps.js';
import * as DiagnosticServiceSections from './ValueSet-DiagnosticServiceSections.js';
import * as DocSectionCodes from './ValueSet-DocSectionCodes.js';
import * as DocumentClasscodes from './ValueSet-DocumentClasscodes.js';
import * as DocumentRelationshipType from './ValueSet-DocumentRelationshipType.js';
import * as DoseRateType from './ValueSet-DoseRateType.js';
import * as EventStatus from './ValueSet-EventStatus.js';
import * as FHIRDeviceTypes from './ValueSet-FHIRDeviceTypes.js';
import * as FHIRDocumentTypeCodes from './ValueSet-FHIRDocumentTypeCodes.js';
import * as FlagCategory from './ValueSet-FlagCategory.js';
import * as FlagCode from './ValueSet-FlagCode.js';
import * as FlagStatus from './ValueSet-FlagStatus.js';
import * as HttpVerb from './ValueSet-HttpVerb.js';
import * as ImagingStudyStatusUvIps from './ValueSet-ImagingStudyStatusUvIps.js';
import * as ImmunizationFunction from './ValueSet-ImmunizationFunction.js';
import * as ImmunizationFundingSource from './ValueSet-ImmunizationFundingSource.js';
import * as ImmunizationOrigin from './ValueSet-ImmunizationOrigin.js';
import * as ImmunizationProgramEligibility from './ValueSet-ImmunizationProgramEligibility.js';
import * as ImmunizationReason from './ValueSet-ImmunizationReason.js';
import * as ImmunizationStatus from './ValueSet-ImmunizationStatus.js';
import * as ImmunizationStatusReason from './ValueSet-ImmunizationStatusReason.js';
import * as ImmunizationSubpotentReason from './ValueSet-ImmunizationSubpotentReason.js';
import * as Languages from './ValueSet-Languages.js';
import * as LinkType from './ValueSet-LinkType.js';
import * as ListEmptyReason from './ValueSet-ListEmptyReason.js';
import * as ListMode from './ValueSet-ListMode.js';
import * as ListOrder from './ValueSet-ListOrder.js';
import * as ManifestationAndSymptomCodes from './ValueSet-ManifestationAndSymptomCodes.js';
import * as MaritalStatus from './ValueSet-MaritalStatus.js';
import * as MedicationrequestCategory from './ValueSet-MedicationrequestCategory.js';
import * as MedicationrequestCourseOfTherapy from './ValueSet-MedicationrequestCourseOfTherapy.js';
import * as MedicationrequestIntent from './ValueSet-MedicationrequestIntent.js';
import * as MedicationrequestStatus from './ValueSet-MedicationrequestStatus.js';
import * as MedicationrequestStatusReason from './ValueSet-MedicationrequestStatusReason.js';
import * as MedicationsExampleUvIps from './ValueSet-MedicationsExampleUvIps.js';
import * as MedicationStatementCategory from './ValueSet-MedicationStatementCategory.js';
import * as MedicationStatementStatus from './ValueSet-MedicationStatementStatus.js';
import * as MedicationStatus from './ValueSet-MedicationStatus.js';
import * as NameUse from './ValueSet-NameUse.js';
import * as ObservationCategory from './ValueSet-ObservationCategory.js';
import * as ObservationCodes from './ValueSet-ObservationCodes.js';
import * as ObservationInterpretation from './ValueSet-ObservationInterpretation.js';
import * as ObservationMethods from './ValueSet-ObservationMethods.js';
import * as ObservationStatus from './ValueSet-ObservationStatus.js';
import * as OrganizationType from './ValueSet-OrganizationType.js';
import * as PatientContactRelationship from './ValueSet-PatientContactRelationship.js';
import * as PersonalRelationshipUvIps from './ValueSet-PersonalRelationshipUvIps.js';
import * as PregnanciesSummaryUvIps from './ValueSet-PregnanciesSummaryUvIps.js';
import * as PregnancyExpectedDeliveryDateMethodUvIps from './ValueSet-PregnancyExpectedDeliveryDateMethodUvIps.js';
import * as PregnancyStatusUvIps from './ValueSet-PregnancyStatusUvIps.js';
import * as ProblemTypeLoinc from './ValueSet-ProblemTypeLoinc.js';
import * as ProblemTypeUvIps from './ValueSet-ProblemTypeUvIps.js';
import * as ProcedureCategory from './ValueSet-ProcedureCategory.js';
import * as ProcedureDeviceActionCodes from './ValueSet-ProcedureDeviceActionCodes.js';
import * as ProcedureFollowup from './ValueSet-ProcedureFollowup.js';
import * as ProcedureNotPerformedReasonSNOMEDCT from './ValueSet-ProcedureNotPerformedReasonSNOMEDCT.js';
import * as ProcedureOutcome from './ValueSet-ProcedureOutcome.js';
import * as ProcedurePerformerRoleCodes from './ValueSet-ProcedurePerformerRoleCodes.js';
import * as ProcedureReasonCodes from './ValueSet-ProcedureReasonCodes.js';
import * as ReactionEventSeverity from './ValueSet-ReactionEventSeverity.js';
import * as ReferencerangeAppliesto from './ValueSet-ReferencerangeAppliesto.js';
import * as ReferencerangeMeaning from './ValueSet-ReferencerangeMeaning.js';
import * as ReportCodes from './ValueSet-ReportCodes.js';
import * as RequestPriority from './ValueSet-RequestPriority.js';
import * as ResourceTypes from './ValueSet-ResourceTypes.js';
import * as ResultsRadiologyComponentUvIps from './ValueSet-ResultsRadiologyComponentUvIps.js';
import * as ResultsStatusUvIps from './ValueSet-ResultsStatusUvIps.js';
import * as SearchEntryMode from './ValueSet-SearchEntryMode.js';
import * as SeriesPerformerFunction from './ValueSet-SeriesPerformerFunction.js';
import * as SNOMEDCTAdditionalDosageInstructions from './ValueSet-SNOMEDCTAdditionalDosageInstructions.js';
import * as SNOMEDCTAdministrationMethodCodes from './ValueSet-SNOMEDCTAdministrationMethodCodes.js';
import * as SNOMEDCTAnatomicalStructureForAdministrationSiteCodes from './ValueSet-SNOMEDCTAnatomicalStructureForAdministrationSiteCodes.js';
import * as SNOMEDCTDrugTherapyStatusCodes from './ValueSet-SNOMEDCTDrugTherapyStatusCodes.js';
import * as SNOMEDCTFormCodes from './ValueSet-SNOMEDCTFormCodes.js';
import * as SNOMEDCTMedicationAsNeededReasonCodes from './ValueSet-SNOMEDCTMedicationAsNeededReasonCodes.js';
import * as SNOMEDCTRouteCodes from './ValueSet-SNOMEDCTRouteCodes.js';
import * as SpecimenContainerType from './ValueSet-SpecimenContainerType.js';
import * as SpecimenProcessingProcedure from './ValueSet-SpecimenProcessingProcedure.js';
import * as SpecimenStatus from './ValueSet-SpecimenStatus.js';
import * as SubstanceCode from './ValueSet-SubstanceCode.js';
import * as UdiEntryType from './ValueSet-UdiEntryType.js';
import * as V20371 from './ValueSet-V20371.js';
import * as V20493 from './ValueSet-V20493.js';
import * as V20916 from './ValueSet-V20916.js';
import * as V2270360 from './ValueSet-V2270360.js';
import * as V3ActCode from './ValueSet-V3ActCode.js';
import * as V3ActSubstanceAdminSubstitutionCode from './ValueSet-V3ActSubstanceAdminSubstitutionCode.js';
import * as V3ConfidentialityClassification from './ValueSet-V3ConfidentialityClassification.js';
import * as V3SubstanceAdminSubstitutionReason from './ValueSet-V3SubstanceAdminSubstitutionReason.js';
import * as VaccineTargetDiseasesUvIps from './ValueSet-VaccineTargetDiseasesUvIps.js';
export declare const ValueSetRegistry: {
    readonly AdministrativeGender: typeof AdministrativeGender;
    readonly AllergyIntoleranceCategory: typeof AllergyIntoleranceCategory;
    readonly AllergyintoleranceClinical: typeof AllergyintoleranceClinical;
    readonly AllergyIntoleranceCriticality: typeof AllergyIntoleranceCriticality;
    readonly AllergyIntoleranceType: typeof AllergyIntoleranceType;
    readonly AllergyintoleranceVerification: typeof AllergyintoleranceVerification;
    readonly AllSecurityLabels: typeof AllSecurityLabels;
    readonly BodySite: typeof BodySite;
    readonly BodysiteLaterality: typeof BodysiteLaterality;
    readonly BundleType: typeof BundleType;
    readonly C80PracticeCodes: typeof C80PracticeCodes;
    readonly ClinicalFindings: typeof ClinicalFindings;
    readonly CommonTags: typeof CommonTags;
    readonly CompositionAttestationMode: typeof CompositionAttestationMode;
    readonly CompositionStatus: typeof CompositionStatus;
    readonly ConditionClinical: typeof ConditionClinical;
    readonly ConditionCode: typeof ConditionCode;
    readonly ConditionSeverity: typeof ConditionSeverity;
    readonly ConditionStage: typeof ConditionStage;
    readonly ConditionStageType: typeof ConditionStageType;
    readonly ConditionVerStatus: typeof ConditionVerStatus;
    readonly ContactentityType: typeof ContactentityType;
    readonly CurrentSmokingStatusUvIps: typeof CurrentSmokingStatusUvIps;
    readonly DataAbsentReason: typeof DataAbsentReason;
    readonly DaysOfWeek: typeof DaysOfWeek;
    readonly DeviceNametype: typeof DeviceNametype;
    readonly DeviceStatementStatus: typeof DeviceStatementStatus;
    readonly DeviceStatus: typeof DeviceStatus;
    readonly DeviceStatusReason: typeof DeviceStatusReason;
    readonly DeviceType: typeof DeviceType;
    readonly DiagnosticReportStatusUvIps: typeof DiagnosticReportStatusUvIps;
    readonly DiagnosticServiceSections: typeof DiagnosticServiceSections;
    readonly DocSectionCodes: typeof DocSectionCodes;
    readonly DocumentClasscodes: typeof DocumentClasscodes;
    readonly DocumentRelationshipType: typeof DocumentRelationshipType;
    readonly DoseRateType: typeof DoseRateType;
    readonly EventStatus: typeof EventStatus;
    readonly FHIRDeviceTypes: typeof FHIRDeviceTypes;
    readonly FHIRDocumentTypeCodes: typeof FHIRDocumentTypeCodes;
    readonly FlagCategory: typeof FlagCategory;
    readonly FlagCode: typeof FlagCode;
    readonly FlagStatus: typeof FlagStatus;
    readonly HttpVerb: typeof HttpVerb;
    readonly ImagingStudyStatusUvIps: typeof ImagingStudyStatusUvIps;
    readonly ImmunizationFunction: typeof ImmunizationFunction;
    readonly ImmunizationFundingSource: typeof ImmunizationFundingSource;
    readonly ImmunizationOrigin: typeof ImmunizationOrigin;
    readonly ImmunizationProgramEligibility: typeof ImmunizationProgramEligibility;
    readonly ImmunizationReason: typeof ImmunizationReason;
    readonly ImmunizationStatus: typeof ImmunizationStatus;
    readonly ImmunizationStatusReason: typeof ImmunizationStatusReason;
    readonly ImmunizationSubpotentReason: typeof ImmunizationSubpotentReason;
    readonly Languages: typeof Languages;
    readonly LinkType: typeof LinkType;
    readonly ListEmptyReason: typeof ListEmptyReason;
    readonly ListMode: typeof ListMode;
    readonly ListOrder: typeof ListOrder;
    readonly ManifestationAndSymptomCodes: typeof ManifestationAndSymptomCodes;
    readonly MaritalStatus: typeof MaritalStatus;
    readonly MedicationrequestCategory: typeof MedicationrequestCategory;
    readonly MedicationrequestCourseOfTherapy: typeof MedicationrequestCourseOfTherapy;
    readonly MedicationrequestIntent: typeof MedicationrequestIntent;
    readonly MedicationrequestStatus: typeof MedicationrequestStatus;
    readonly MedicationrequestStatusReason: typeof MedicationrequestStatusReason;
    readonly MedicationsExampleUvIps: typeof MedicationsExampleUvIps;
    readonly MedicationStatementCategory: typeof MedicationStatementCategory;
    readonly MedicationStatementStatus: typeof MedicationStatementStatus;
    readonly MedicationStatus: typeof MedicationStatus;
    readonly NameUse: typeof NameUse;
    readonly ObservationCategory: typeof ObservationCategory;
    readonly ObservationCodes: typeof ObservationCodes;
    readonly ObservationInterpretation: typeof ObservationInterpretation;
    readonly ObservationMethods: typeof ObservationMethods;
    readonly ObservationStatus: typeof ObservationStatus;
    readonly OrganizationType: typeof OrganizationType;
    readonly PatientContactRelationship: typeof PatientContactRelationship;
    readonly PersonalRelationshipUvIps: typeof PersonalRelationshipUvIps;
    readonly PregnanciesSummaryUvIps: typeof PregnanciesSummaryUvIps;
    readonly PregnancyExpectedDeliveryDateMethodUvIps: typeof PregnancyExpectedDeliveryDateMethodUvIps;
    readonly PregnancyStatusUvIps: typeof PregnancyStatusUvIps;
    readonly ProblemTypeLoinc: typeof ProblemTypeLoinc;
    readonly ProblemTypeUvIps: typeof ProblemTypeUvIps;
    readonly ProcedureCategory: typeof ProcedureCategory;
    readonly ProcedureDeviceActionCodes: typeof ProcedureDeviceActionCodes;
    readonly ProcedureFollowup: typeof ProcedureFollowup;
    readonly ProcedureNotPerformedReasonSNOMEDCT: typeof ProcedureNotPerformedReasonSNOMEDCT;
    readonly ProcedureOutcome: typeof ProcedureOutcome;
    readonly ProcedurePerformerRoleCodes: typeof ProcedurePerformerRoleCodes;
    readonly ProcedureReasonCodes: typeof ProcedureReasonCodes;
    readonly ReactionEventSeverity: typeof ReactionEventSeverity;
    readonly ReferencerangeAppliesto: typeof ReferencerangeAppliesto;
    readonly ReferencerangeMeaning: typeof ReferencerangeMeaning;
    readonly ReportCodes: typeof ReportCodes;
    readonly RequestPriority: typeof RequestPriority;
    readonly ResourceTypes: typeof ResourceTypes;
    readonly ResultsRadiologyComponentUvIps: typeof ResultsRadiologyComponentUvIps;
    readonly ResultsStatusUvIps: typeof ResultsStatusUvIps;
    readonly SearchEntryMode: typeof SearchEntryMode;
    readonly SeriesPerformerFunction: typeof SeriesPerformerFunction;
    readonly SNOMEDCTAdditionalDosageInstructions: typeof SNOMEDCTAdditionalDosageInstructions;
    readonly SNOMEDCTAdministrationMethodCodes: typeof SNOMEDCTAdministrationMethodCodes;
    readonly SNOMEDCTAnatomicalStructureForAdministrationSiteCodes: typeof SNOMEDCTAnatomicalStructureForAdministrationSiteCodes;
    readonly SNOMEDCTDrugTherapyStatusCodes: typeof SNOMEDCTDrugTherapyStatusCodes;
    readonly SNOMEDCTFormCodes: typeof SNOMEDCTFormCodes;
    readonly SNOMEDCTMedicationAsNeededReasonCodes: typeof SNOMEDCTMedicationAsNeededReasonCodes;
    readonly SNOMEDCTRouteCodes: typeof SNOMEDCTRouteCodes;
    readonly SpecimenContainerType: typeof SpecimenContainerType;
    readonly SpecimenProcessingProcedure: typeof SpecimenProcessingProcedure;
    readonly SpecimenStatus: typeof SpecimenStatus;
    readonly SubstanceCode: typeof SubstanceCode;
    readonly UdiEntryType: typeof UdiEntryType;
    readonly V20371: typeof V20371;
    readonly V20493: typeof V20493;
    readonly V20916: typeof V20916;
    readonly V2270360: typeof V2270360;
    readonly V3ActCode: typeof V3ActCode;
    readonly V3ActSubstanceAdminSubstitutionCode: typeof V3ActSubstanceAdminSubstitutionCode;
    readonly V3ConfidentialityClassification: typeof V3ConfidentialityClassification;
    readonly V3SubstanceAdminSubstitutionReason: typeof V3SubstanceAdminSubstitutionReason;
    readonly VaccineTargetDiseasesUvIps: typeof VaccineTargetDiseasesUvIps;
};
export type ValueSetName = keyof typeof ValueSetRegistry;
export declare function getValueSet(name: ValueSetName): typeof AdministrativeGender | typeof AllergyIntoleranceCategory | typeof AllergyintoleranceClinical | typeof AllergyIntoleranceCriticality | typeof AllergyIntoleranceType | typeof AllergyintoleranceVerification | typeof AllSecurityLabels | typeof BodySite | typeof BodysiteLaterality | typeof BundleType | typeof C80PracticeCodes | typeof ClinicalFindings | typeof CommonTags | typeof CompositionAttestationMode | typeof CompositionStatus | typeof ConditionClinical | typeof ConditionCode | typeof ConditionSeverity | typeof ConditionStage | typeof ConditionStageType | typeof ConditionVerStatus | typeof ContactentityType | typeof CurrentSmokingStatusUvIps | typeof DataAbsentReason | typeof DaysOfWeek | typeof DeviceNametype | typeof DeviceStatementStatus | typeof DeviceStatus | typeof DeviceStatusReason | typeof DeviceType | typeof DiagnosticReportStatusUvIps | typeof DiagnosticServiceSections | typeof DocSectionCodes | typeof DocumentClasscodes | typeof DocumentRelationshipType | typeof DoseRateType | typeof EventStatus | typeof FHIRDeviceTypes | typeof FHIRDocumentTypeCodes | typeof FlagCategory | typeof FlagCode | typeof FlagStatus | typeof HttpVerb | typeof ImagingStudyStatusUvIps | typeof ImmunizationFunction | typeof ImmunizationFundingSource | typeof ImmunizationOrigin | typeof ImmunizationProgramEligibility | typeof ImmunizationReason | typeof ImmunizationStatus | typeof ImmunizationStatusReason | typeof ImmunizationSubpotentReason | typeof Languages | typeof LinkType | typeof ListEmptyReason | typeof ListMode | typeof ListOrder | typeof ManifestationAndSymptomCodes | typeof MaritalStatus | typeof MedicationrequestCategory | typeof MedicationrequestCourseOfTherapy | typeof MedicationrequestIntent | typeof MedicationrequestStatus | typeof MedicationrequestStatusReason | typeof MedicationsExampleUvIps | typeof MedicationStatementCategory | typeof MedicationStatementStatus | typeof MedicationStatus | typeof NameUse | typeof ObservationCategory | typeof ObservationCodes | typeof ObservationInterpretation | typeof ObservationMethods | typeof ObservationStatus | typeof OrganizationType | typeof PatientContactRelationship | typeof PersonalRelationshipUvIps | typeof PregnanciesSummaryUvIps | typeof PregnancyExpectedDeliveryDateMethodUvIps | typeof PregnancyStatusUvIps | typeof ProblemTypeLoinc | typeof ProblemTypeUvIps | typeof ProcedureCategory | typeof ProcedureDeviceActionCodes | typeof ProcedureFollowup | typeof ProcedureNotPerformedReasonSNOMEDCT | typeof ProcedureOutcome | typeof ProcedurePerformerRoleCodes | typeof ProcedureReasonCodes | typeof ReactionEventSeverity | typeof ReferencerangeAppliesto | typeof ReferencerangeMeaning | typeof ReportCodes | typeof RequestPriority | typeof ResourceTypes | typeof ResultsRadiologyComponentUvIps | typeof ResultsStatusUvIps | typeof SearchEntryMode | typeof SeriesPerformerFunction | typeof SNOMEDCTAdditionalDosageInstructions | typeof SNOMEDCTAdministrationMethodCodes | typeof SNOMEDCTAnatomicalStructureForAdministrationSiteCodes | typeof SNOMEDCTDrugTherapyStatusCodes | typeof SNOMEDCTFormCodes | typeof SNOMEDCTMedicationAsNeededReasonCodes | typeof SNOMEDCTRouteCodes | typeof SpecimenContainerType | typeof SpecimenProcessingProcedure | typeof SpecimenStatus | typeof SubstanceCode | typeof UdiEntryType | typeof V20371 | typeof V20493 | typeof V20916 | typeof V2270360 | typeof V3ActCode | typeof V3ActSubstanceAdminSubstitutionCode | typeof V3ConfidentialityClassification | typeof V3SubstanceAdminSubstitutionReason | typeof VaccineTargetDiseasesUvIps;
/** Map from ValueSet URL to registry name */
export declare const ValueSetUrlMap: Record<string, ValueSetName>;
/**
 * Get a random code from a ValueSet by URL
 * @param url - The canonical URL of the ValueSet (may include version like "|4.0.1")
 * @returns A random code string, or undefined if ValueSet not found
 */
export declare function getRandomCodeByUrl(url: string): string | undefined;
/**
 * Get a random concept (code, system, display) from a ValueSet by URL
 * @param url - The canonical URL of the ValueSet (may include version like "|4.0.1")
 * @returns A concept object with code, system, and optional display, or undefined if ValueSet not found
 */
export declare function getRandomConceptByUrl(url: string): {
    code: string;
    system: string;
    display?: string;
} | undefined;
